### ISSUE TITLE
[Feature] New components we could consider for the next development cycle

### ISSUE THREAD

**Issue by xiaoya-Esther** [hypertrons/hypertrons-crx#101]
Here are some new components we could consider for the next development cycle:
For Developer:
- Rader map to show event frequency of Star、Fork、Commit、OpenIssue、OpenPR、PR review (event types can be further discussed) for the half-past year.
- Commit language distribution for the half-past year.

For Repo:
- Open/Closed Issue per week/month for the half-past year.
- Code Changed Lines per week/month for the half-past year.

Note these components are expected to be attached with prices when published.

**Comment by heming6666** [comment]
Thanks @xiaoya-Esther for raising the discussion about these great and interesting components.

> For Developer:
> Rader map to show event frequency of Star、Fork、Commit、OpenIssue、OpenPR、PR review (event types can be further discussed) for the half-past year.

I think `Star` and `Fork` are more like `Repo` metrics, right?
