### ISSUE TITLE
[Community] Idea list for Summer 2021 of Open Source Promotion Plan

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#103]
Summer 2021 of Open Source Promotion Plan is coming!

### Introduction

Open Source Promotion Plan encourages everyone to pay close attention to open source software and open source community, aiming to cultivate and explore more outstanding developers. `Summer 2021` will be held in this summer. We will collaborate closely with the open source community to provide one-to-one mentor guidance and invite some specialists to conduct free online lectures. In order to promote the development of open source software and facilitate the construction of excellent open source software community, we encourage researchers, open source enthusiasts, professors as well as students to participate in the development and maintenance of open source software. Furthermore, `Summer 2021` is supposed to increase the activity of open source projects, and promote the development of open source ecology.

Home：https://summer.iscas.ac.cn/
Help：https://summer.iscas.ac.cn/help/

### Hypertrons community

`Hypertrons` has been accepted as the community of Summer 2021. 

Here's the full list of communities in Summer 2021: https://summer.iscas.ac.cn/help/communities-list/

![image](https://user-images.githubusercontent.com/26642280/115498514-4a4d9e80-a2a0-11eb-9f4c-f8700c6cab79.png)

### Ideas list for Hypertrons-crx

As a part of `Hypertrons` community, `Hypertrons-crx` will provide some ideas for Summer 2021. If you have any ideas, please comment in this issue. We really appreciate it :) @LiuChangFreeman @frank-zsy @xiaoya-Esther @wengzhenjie @Wence-May

**Comment by heming6666** [comment]
### 1. Customized React chart library

- Description

  - As an extension and important part of the function of `hypertrons`, `hypertrons-crx` can insert dashboards into specific `GitHub` pages to help users gain the insight into developers and projects. The project currently uses `Echarts` and `Antv` as visualization tools. In order to provide a good interactive experience and simplify the configuration process, it is necessary to encapsulate and customize the charts used in the project (e.g. graph, radar and table). We can implement the `React` component based on Echarts, Antv or other visualization engines.

- Expected outcomes

  - Customized React chart library.
  - Related documentation.

- Skills required

  - Git
  - TypeScript
  - React
  - Echarts / Antv
  - Fluent-ui

- Mentor

  - Haiming Lin <<lhming23@outlook.com>>
  - Chang Liu <<liuchangfreeman@live.com>>

- Difficulty

  - High

- Repositories

- [hypertrons/hypertrons-crx](https://github.com/hypertrons/hypertrons-crx)

**Comment by heming6666** [comment]
2. Build website for hypertrons-crx and improve the documentation

- Description

  - To help users understand `hypertrons-crx` project and know how to install our product, we need to build the website for `hypertrons-crx`, including project introduction, installation guide and other information.
  - To help developers understand how `hypertrons-crx` works and help them participate in the project, we need to improve the documentation and add more details about the architecure, components and apis of this project.

- Expected outcomes

  - Official website
  - Documentation

- Skills required

  - JavaScript / TypeScript
  - Markdown

- Mentor

  - Haiming Lin <<lhming23@outlook.com>>
  - Shengyu Zhao <<frank_zsy@hypertrons.io>>

- Difficulty

  - Medium

- Repositories

  - [hypertrons/hypertrons-crx](https://github.com/hypertrons/hypertrons-crx)

**Comment by xiaoya-Esther** [comment]
### 3. Crx Page Design and Enhancement (Non-code contributions)
- Description

  - Hypertrons-crx is expected to have an eye-catching component layout and color consistency for the perceptor page, profile page, pop-out and setting pages. The project idea is about enhancing the page style by designing tools, as well as providing the exact color and distance for every single and micro element.

- Expected outcomes
  - A fully designed product prototype

- Skills require
  - Designing Tools, i.e.Figma
  - HTML, CSS
  - Markdown

- Difficulty
  - Medium

**Comment by heming6666** [comment]
### Update
All of these three ideas have been accepted and you can see them in: https://summer.iscas.ac.cn/#/org/orgdetail/hyportrons.

**Comment by heming6666** [comment]
If you are interested in these ideas, please comment in this issue. And if you have trouble when running the project, don't hesitate to write it down.

**Comment by Aju100** [comment]
Hi @heming6666 ,

I would love to contribute and participate on Summer OSPP on  Build website for hypertrons-crx and improve the documentation.

**Comment by heming6666** [comment]
Hi @Aju100, thanks for your interest. You can go through our available documents (readme, installation guilde and let us know if you have any problems.

**Comment by AmosChenYQ** [comment]
Hi @heming6666 
What should I if I want to participate this summer code plan? I have already registered and submitted the project customized react chart library.

**Comment by heming6666** [comment]
> Hi @heming6666
> What should I if I want to participate this summer code plan? I have already registered and submitted the project customized react chart library.

Hi @AmosChenYQ , thanks for your interest. You can check these microtasks (#155 )to help you get familiar with `hypertrons-crx`.  

Besides, it seems that we don't received your application in the management system. Please check your submission again and let us know if you have any problems.

**Comment by heming6666** [comment]
> Hi @heming6666 ,
> 
> I would love to contribute and participate on Summer OSPP on Build website for hypertrons-crx and improve the documentation.

Hi @Aju100 , if you are interest in this idea (Build website for hypertrons-crx and improve the documentation), you can try  these microtasks (#156) to help you get familiar with `hypertrons-crx`.

**Comment by AmosChenYQ** [comment]
> > Hi @heming6666
> > What should I if I want to participate this summer code plan? I have already registered and submitted the project customized react chart library.
> 
> Hi @AmosChenYQ , thanks for your interest. You can check these microtasks (#155 )to help you get familiar with `hypertrons-crx`.
> 
> Besides, it seems that we don't received your application in the management system. Please check your submission again and let us know if you have any problems.

![image](https://user-images.githubusercontent.com/31386769/120918116-486f5b80-c6e5-11eb-85b1-3b377d8c0bc7.png)

I have applied in the management system. And this is my application but the proposal is not ready yet...

**Comment by Gaoxiao-ting** [comment]
I would like to know if you have a wechat group chat for further communication.

**Comment by heming6666** [comment]
> I would like to know if you have a wechat group chat for further communication.

@Gaoxiao-ting  Yes, you can join the wechat group through this QR code.

![image](https://user-images.githubusercontent.com/26642280/121807414-9b698580-cc86-11eb-9dc4-50245583328a.png)
