### ISSUE TITLE
[Community] We need icon and promotional image for hypertrons-crx

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#117]
We need icon and promotional image for `hypertrons-crx` community: 

- [x] App icon (logo)
  - 128x128 px
  - Work well on both light and dark backgrounds.
 
- [ ] Promotional image
  - 440x280 or 440x280 or 920x680 px

We can check https://developer.chrome.com/docs/webstore/images/ for some requirements for the images.

**Comment by will-ww** [comment]
Any progress? @heming6666

**Comment by heming6666** [comment]
> Any progress? @heming6666

We can use the following image as our logo:

![hypertrons-logo-128](https://user-images.githubusercontent.com/26642280/120014944-40445b80-c015-11eb-8574-a917408bfcb3.jpg)

**Comment by heming6666** [comment]
Closed.

We can reopen it if needed.
