### ISSUE TITLE
[Community][Discussion] Add code names to our releases.

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#125]
<!-- hypertronsMetaData: {"choices":["Andromeda","Antlia","Apus","Aquarius","Aquila","Ara","Aries","Auriga"],"participants":["anyone"],"duration":518400000,"launchTime":1622218899634,"comment_id":850529744} --!>
Semantic versioning has a lot of technical benefits for developers and users.

- Adding version code names speeds up discussions around version numbers and makes working more efficient. 
- People remember names better than they do numbers. The releases also become more memorable, and people are able to recall them quicker.

There are huge releases of software that already implement version code names (e.g. Android, Ubuntu). We can also add some interesting version code names to make our releases more memorable.

**Comment by will-ww** [comment]
I think we can name our release version in alphabetical order (1.0 A***, 2.0 B***, etc.). For example, combined with constellation situation, the following names are availabie as candidates:

- Andromeda
- Antlia
- Apus
- Aquarius
- Aquila
- Ara
- Aries
- Auriga

More information can be found: [https://en.wikipedia.org/wiki/Lists_of_stars_by_constellation](url)

Any other suggestions ?

**Comment by heming6666** [comment]
Great. Thanks @will-ww !

/start-vote Andromeda,Antlia,Apus,Aquarius,Aquila,Ara,Aries,Auriga anyone 6d

**Comment by heming6666** [comment]
We use `hypertrons Vote` component to count the vote. You can join the vote by `/vote your-choice`.

You can also refer to https://www.hypertrons.io/#/component/vote to see more information about the `Vote`.

**Comment by frank-zsy** [comment]
/vote Auriga

There is an operation system called `Andromeda` which combines Android and ChromeOS. And I think we should use names with up to 3 vowels for pronunciation convenience. And also the meaning should be considered too.

**Comment by heming6666** [comment]
> ### Vote Summary
> * **Andromeda**: tyn1998,
> * **Antlia**:
> * **Apus**:
> * **Aquarius**: mb0ma,
> * **Aquila**: LiuChangFreeman,
> * **Ara**: zhuxiangning,
> * **Aries**:
> * **Auriga**: heming6666, frank-zsy, wengzhenjie,

📢 📢 📢  

According to the voting results, we would select `Auriga` as our code name for the first version!

**Comment by heming6666** [comment]
Done.
