### ISSUE TITLE
We need add more information and some pictures in the repo homepage

### ISSUE THREAD

**Issue by will-ww** [hypertrons/hypertrons-crx#130]
Especially some attractive pictures to let the users know what is the porpose of this projet~

**Comment by will-ww** [comment]
For example, although not sure the exact meaning of this picture  :-)

![无标题](https://user-images.githubusercontent.com/15010826/119998345-30bc1700-c003-11eb-9fc7-aaec50475fe6.jpg)

**Comment by heming6666** [comment]
+1

Maybe we can add some detailed description of `Developer Collaboration Network` and `Project Correlation Network` to `README`. For example: 

- Developer Relationship Exploration
  - `Developer Collaboration Network`: `Developer Collaboration Network` shows the collaboration between the given developer and his associated developers. From this graph you can find other developers who are closet to a given developer.
  - `Most Participated Repos`: From this graph you can find out the most active repositories for a given developer.

- Project Relationship Exploration
  - `Project Correlation Network`: From this graph you can find the projects that are related to the given project.
  - `Active Developer Collabration Network`: From this graph you can find the active developers in the given project. What's more, you can find the collaborative relationships between these developers.

@xiaoya-Esther @frank-zsy Can you help to review or think about the exact meaning or description of these graph? Thanks :)

**Comment by heming6666** [comment]
Closed.
