### ISSUE TITLE
[Community][Discussion] We need a slogan for our project !

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#133]
We need a concise and memorable slogan to show the features and intentions of out peoject.

 Any suggestions ?

**Comment by xiaoya-Esther** [comment]
I propose `"tracking, tracing and digging GitHub projects and developers"` or `"tracking, tracing and digging the things you need to know on GitHub"`. 

It depends on how specific we want the slogan to be.

**Comment by heming6666** [comment]
@xiaoya-Esther Great!  I love this slogan.

And we can even expand our point from `GitHub` to `open source projects`
