### ISSUE TITLE
[Doc] Update Installation guide

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#136]
As we have published our extention to [`Chrome App Store`](https://chrome.google.com/webstore/detail/hypertrons/jkgfcnkgfapbckbpgobmgiphpknkiljm?hl=zh-CN), We need to update Installation guide. 

Currently the installation guide describes how to download the package from the `release` page and then install it in developer mode. We need to show users how to install our extension in Chrome App Store.

**Comment by heming6666** [comment]
Here's the example: https://yiban.io/download

**Comment by LiuChangFreeman** [comment]
Shall we also publish it to Edge store?

**Comment by heming6666** [comment]
> Shall we also publish it to Edge store?

Sure!

**Comment by heming6666** [comment]
We need a chinese version

**Comment by heming6666** [comment]
> > Shall we also publish it to Edge store?
> 
> Sure!

According to the conclusion of tonight's weekly meeting, we decided to  publish only to `Chrome Web Store` in current stage ( V1.0.0). 

`Edge Store` can be considerable in the future.

**Comment by heming6666** [comment]
This PR #148 has been merged. Thanks @zhuxiangning for your great work!

In addition,  we need to update the English version of the installation guide. The website also needs to be updated if possible.

**Comment by DantrazTrev** [comment]
Hei @zhuxiangning are you working on the English Installation guide?

**Comment by zhuxiangning** [comment]
> Hei @zhuxiangning are you working on the English Installation guide?

Yes, I'm preparing it.

**Comment by heming6666** [comment]
@zhuxiangning @DantrazTrev I have update a new version of installation guide #171 . You guys can check and improve it if you find any problems or have better idea for the documentation.

**Comment by DantrazTrev** [comment]
Hei @zhuxiangning , there has been a few changes in EN Installation guide regarding the github tokens . Could you update the Zh-CN guide to reflect the changes?

**Comment by zhuxiangning** [comment]
> Hei @zhuxiangning , there has been a few changes in EN Installation guide regarding the github tokens . Could you update the Zh-CN guide to reflect the changes?

Thank you for reminding me, I will update it in the next few days~

**Comment by LiuChangFreeman** [comment]
@zhuxiangning Now the [Edge ](https://microsoftedge.microsoft.com/addons/detail/hypertronscrx/lfdjlbagcbpjpdhlllcgglplcccnigip?hl=zh-CN) version has been released, could you update the guide for it?

**Comment by zhuxiangning** [comment]
> @zhuxiangning Now the [Edge ](https://microsoftedge.microsoft.com/addons/detail/hypertronscrx/lfdjlbagcbpjpdhlllcgglplcccnigip?hl=zh-CN) version has been released, could you update the guide for it?

OK, I'll update it later.
