### ISSUE TITLE
[Bug] Error with developer network when choose Antv as the rendering type

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#141]
### Version
1.0.0

### Steps to reproduce

1. Install from `Google Web Store`
2. Open `开发者协作网络`

### Environment
- Mac
- Chrome

**Comment by frank-zsy** [comment]
Also run into this bug. The console error log is:

![image](https://user-images.githubusercontent.com/8512426/120656044-d7962c80-c4b5-11eb-86d2-c7532934b781.png)

**Comment by tyn1998** [comment]
Infact, All networks fail when chosing AntV as rendering type.

**Comment by tyn1998** [comment]
### Enviroment
- MacOS 11.1
- Chrome 90
- Hypertrons-crx v1.0.1 (using AntV as chart renderer)
### Test result
All is good!

**Comment by LiuChangFreeman** [comment]
Antv works well on mac, at version 1.0.1.  
![screenshot-20210610-105232](https://user-images.githubusercontent.com/20047907/121457323-16f2da80-c9da-11eb-9dec-8b57c4ea9663.png)

**Comment by heming6666** [comment]
Great! Thanks @tyn1998 @LiuChangFreeman .

Closed.
