### ISSUE TITLE
[Refactor] More friendly notification if data not found

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#144]
If there is no data file for a repo or user, we should display readable information about data missing but right now the crx will throw a 500 error.

![image](https://user-images.githubusercontent.com/8512426/120656974-a66a2c00-c4b6-11eb-9867-e9192d3b6f62.png)

This also involve with a data bug. From clickhouse we select the data with `any` repo_name but if a repo changed its name and the query did not get the recent name then data will be missing on OSS. This may what happened for open-digger.

**Comment by heming6666** [comment]
> If there is no data file for a repo or user, we should display readable information about data missing but right now the crx will throw a 500 error.

+1
