### ISSUE TITLE
[Bug] Two "Perceptor"s occur after returning to issues list page from issue page

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#145]
Bug reproduction:
1. Enter the "Issues" column of the repository
2. Click an issue to navigate to issue page
3. Return to previous page then two `Perceptor` & two `Insights` occur
![image](https://user-images.githubusercontent.com/32434520/120732483-f9c09680-c517-11eb-84a4-7f4aaa482d37.png)

**Comment by tyn1998** [comment]
It can be over 2.
![image](https://user-images.githubusercontent.com/32434520/120732850-95ea9d80-c518-11eb-879a-e46c605913f1.png)

**Comment by LiuChangFreeman** [comment]
Thank you for reporting this bug. We have solved it in this pr: https://github.com/hypertrons/hypertrons-crx/pull/146
