### ISSUE TITLE
[community] We need issue template for reporting bug

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#147]
It will be convenient for user to report bugs.  More importantly, it will make it easier for us to identify the cause of the problem.

**Comment by heming6666** [comment]
For example:

### Version
1.0.0

### Steps to reproduce
- Install from Google Web Store
...

### Environment
- Your system (Win / Mac / ...)
- Your browser (Chrome / Edge / ...)

**Comment by liambrewster** [comment]
/self-assign

as this is missing and also referenced within the contributing documentation I would like to add something back in as a First issue

**Comment by liambrewster** [comment]
a pull request has been make for this hopefully it will pass as a suitable fix
 
 within PR #151

**Comment by heming6666** [comment]
Hi @liambrewster, I have reviewed your PR and please check the [review comment](https://github.com/hypertrons/hypertrons-crx/pull/151#discussion_r645995211). 

Thanks for your work and we really appreciate your contribution.

**Comment by heming6666** [comment]
Fixed by #151 .
