### ISSUE TITLE
Summer OSPP Idea: Customized React chart library

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#155]
`Hypertrons-crx` is a chrome extension project which aims at tracing, digging and gaining insight into the projects and developers you're interested in.  It provides an effective way for digital operations and analysis of open source community.

The main function of `Hypertrons-crx` is inserting useful dashboards into `GitHub` pages. For example, you can find out the most relevant projects/developers to the given project/developer in `Project Correlation Network` and `Developer Collabration Network`.  The project currently uses `Echarts` and `Antv` as visualization tools. In order to provide a good interactive experience and simplify the configuration process, it is necessary to encapsulate and customize the charts used in the project (e.g. graph, line, radar and table).  We can implement the React component based on Echarts, Antv or other visualization engines.

The output requirements are:
- Refactor the `graph` component to provide a better interactive experience.
- Add `line` chart component
- Add `Bar` chart component
- Add `Rader` chart component
- Add `Table` component

We can implement these React component based on `Echarts`, `Antv`, `Fluent-ui` or other libraries.

- Difficulty: High
- Requirements: Interest in open souce data analytics. 
- Recommended: Experience with `TypeScript`, `React`, `Echarts`, `Antv` and `Fluent-ui` would be convenient.
- Mentors: @heming6666 @LiuChangFreeman  @frank-zsy 

### Microtask 1

Download `hypertrons-crx` from [`Chrome Web Store`](https://chrome.google.com/webstore/detail/hypertrons-crx/jkgfcnkgfapbckbpgobmgiphpknkiljm). You can use this [guide](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.zh-CN.md) for reference. Then find [those dashboards](https://github.com/hypertrons/hypertrons-crx#dashboards-) and write down: 
- 5 relevant projects to `microsoft/vscode` 
- the most active developer in `microsoft/vscode` 
- 5 relevant developers to `vscode-triage-bot`
- the most active repositorie for `vscode-triage-bot`

### Microtask 2

Remove your `hypertrons-crx` extension that downloaded from [`Chrome Web Store`] from `Chrome` (or `Edge`). And then re-install it from our `release`. You can use this [guide](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.md) for reference.

### Microtask 3

Set up `hypertrons-crx`in your machine. You can use this [guide](https://github.com/hypertrons/hypertrons-crx#quickstart) for reference.

### Microtask 4

Learn about the data structure that used in `Developer Collabration Network` 

### Microtask 5

Learn about how to use `graph` component to render `Developer Collabration Network` 

### Microtask 6

Anything you want to show us. Even if you find bugs in our documentation and want to issue a PR for those!

**Comment by heming6666** [comment]
For all students interested in this idea, please comment on this issue to get in touch with the mentors. 

**You can check out these microtasks to help you get familiar with this idea. It's recommented that you write down the  results of your execution in somewhere (e.g. your github repository or your final proposal ) and let us know if you have any problems.**

**Comment by DantrazTrev** [comment]
Hei @heming6666 I'm interested in this and I've gone through the micro tasks.  Although I'm facing a problem in external installation of hypertron crx , which is resolved by simply changing the `global_message_404`'s message  `message.json` in `build/locales`.
Although I'm unsure if it's just browser related I'm on Chromium 89.
Can you help me with it

**Comment by heming6666** [comment]
> Hei @heming6666 I'm interested in this and I've gone through the micro tasks. 

Thank you @DantrazTrev for your interest!

> Although I'm facing a problem in external installation of hypertron crx , which is resolved by simply changing the global_message_404's message message.json in build/locales.

Yes, you're right. Actually it's a bug caused by `global_message_404`. This PR #160 tends to fix it.

Hope it's helpful for you and let us know if you face problems.

**Comment by DantrazTrev** [comment]
> > Hei @heming6666 I'm interested in this and I've gone through the micro tasks.
> 
> Thank you @DantrazTrev for your interest!
> 
> > Although I'm facing a problem in external installation of hypertron crx , which is resolved by simply changing the global_message_404's message message.json in build/locales.
> 
> Yes, you're right. Actually it's a bug caused by `global_message_404`. This PR #160 tends to fix it.
> 
> Hope it's helpful for you and let us know if you face problems.

Hei @heming6666 thanks for the response. I'm on my way to writing my draft proposal where I encountered a couple of queries . It would be really helpful if you could answer about these. Primarily how is the table data going to be used on the basis of the data we're currently fetching ?

**Comment by heming6666** [comment]
Hi @DantrazTrev .

> Primarily how is the table component going to be used on the basis of the data we're currently fetching ?

Firstly, `table` component can be used as a widget to display detailed data of dashboards. For example, we can add a small button to [`Developer's Most Participated Repos`](https://github.com/hypertrons/hypertrons-crx#developer-releated-) panel, and when users click on this button, a `table` component will popup and display detailed data. Something like: 

![image](https://user-images.githubusercontent.com/26642280/121322263-689b5680-c941-11eb-85ad-65ac416c226a.png)

Secondly, `table` component can be used as a standalone component to display other metrics data. For example, we can use it to  show the [`new contributors`](https://github.com/X-lab2017/open-digger/issues/577) list.

![image](https://user-images.githubusercontent.com/26642280/121324465-56bab300-c943-11eb-8546-27239e1c5687.png)

**Comment by DantrazTrev** [comment]
Hei @heming6666 I've written my draft proposal , it would be helpful if I can get some feedback on it https://docs.google.com/document/d/10F5hymV5nBprfn9UERCw-BGLtfp4BvitoGQevNqhvWA/edit?usp=sharing

**Comment by heming6666** [comment]
Hi @DantrazTrev, I have just reviewed your proposal and overall it looks really good and the sections are easy to follow. 

I have just a minor comment about the detailed implementation. For example, for `table` component: 

- Do you have any specific points in mind that which library will be used to implement it ? (e.g. fluent-ui or [datatables](https://datatables.net/)). 
- What factors do you think might be important in order to determine which tool might better suit the task?

Also it woule be nice if more technical and detailed information can be added into the proposal. For example, the draft interface design of `table` component: 
```ts
interface TableProps {
  data: TableData;
  columns: ColumnsType;
  pagination: PaginationType;
  ...
}
```

**Comment by tyn1998** [comment]
## My application
Hi @heming6666 , here is [my application of Summer 2021 of OSPP](https://shimo.im/docs/kQhQK9h8jkTwpy8K). Please review, thanks!
### Application outline
- What I have learned?
  - About hypertrons-crx
  - About Echarts & AntV
  - About community
- My plan
  - Big picture
  - Encapsulation details
  - Other ideas
  - Timeline

**Comment by heming6666** [comment]
> ## My application
> Hi @heming6666 , here is [my application of Summer 2021 of OSPP](https://shimo.im/docs/kQhQK9h8jkTwpy8K). Please review, thanks!
> 
> ### Application outline
> * What I have learned?
>   
>   * About hypertrons-crx
>   * About Echarts & AntV
>   * About community
> * My plan
>   
>   * Big picture
>   * Encapsulation details
>   * Other ideas
>   * Timeline

Hi @tyn1998 , sorry for the late reply. I have reviewed your proposal. Your proposal reflected your good understanding of the project's objectives.

You can consider to add your results of microtask or contribution you have made to the proposal.

**Comment by tyn1998** [comment]
@heming6666 Thank you for reviewing. I have updated [my application of Summer 2021 of OSPP](https://shimo.im/docs/kQhQK9h8jkTwpy8K).
