### ISSUE TITLE
Summer OSPP Idea: Build website for hypertrons-crx and improve the documentation

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#156]
`Hypertrons-crx` is a chrome extension project which aims at tracing, digging and gaining insight into the projects and developers you're interested in.  It provides an effective way for digital operations and analysis of open source community.

- To help users understand `hypertrons-crx` project and know how to install our product, we need to build the website for `hypertrons-crx`, including project introduction, installation guide and other information.
- To help developers understand how `hypertrons-crx` works and help them participate in the project, we need to improve the documentation and add more details about the architecure, components and apis of this project.

The output requirements are:
- Build the official website for `hypertrons-crx`, including project introduction, installation guide and other necessary information.
- Improve the documentation and add more details about the architecure, components and apis of this project.

- Difficulty: Medium
- Requirements: Interest in open souce data analytics. Writing technical documentation.
- Recommended: Experience with `TypeScript`, `React` and `Markdown` would be convenient.
- Mentors: @heming6666 @LiuChangFreeman  @frank-zsy 

### Microtask 1

Download `hypertrons-crx` from [`Chrome Web Store`](https://chrome.google.com/webstore/detail/hypertrons-crx/jkgfcnkgfapbckbpgobmgiphpknkiljm). You can use this [guide](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.zh-CN.md) for reference. Then find [those dashboards](https://github.com/hypertrons/hypertrons-crx#dashboards-) and write down: 
- 5 relevant projects to `microsoft/vscode` 
- the most active developer in `microsoft/vscode` 
- 5 relevant developers to `vscode-triage-bot`
- the most active repositorie for `vscode-triage-bot`

### Microtask 2

Remove your `hypertrons-crx` extension that downloaded from [`Chrome Web Store`] from `Chrome` (or `Edge`). And then re-install it from our `release`. You can use this [guide](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.md) for reference.

### Microtask 3

Set up `hypertrons-crx`in your machine. You can use this [guide](https://github.com/hypertrons/hypertrons-crx#quickstart) for reference.

### Microtask 4

Read through `README`, `Installation Guide` and `Contributing Guide`. Visit the website: https://hypertrons.github.io/hypertrons-crx-website/

### Microtask 5

Anything you want to show us. Submit at least a PR to [`hypertrons/hypertrons-crx`](https://github.com/hypertrons/hypertrons-crx)  or [`hypertrons/hypertrons-crx-website`](https://github.com/hypertrons/hypertrons-crx-website).

### Microtask 6

Anything you want to show us.

**Comment by heming6666** [comment]
For all students interested in this idea, please comment on this issue to get in touch with the mentors. 

**You can check out these microtasks to help you get familiar with this idea. It's recommented that you write down the  results of your execution in somewhere (e.g. your github repository or your final proposal ) and let us know if you have any problems.**

**Comment by Aju100** [comment]
Hi @heming6666 ,

I understand about the microtasks and also I am preparing the draft proposal. For the microtask, should I create a repo in my Github profile to list down the tasks or should I update it here in the comment section?

**Comment by heming6666** [comment]
@Aju100 Great! It's recommended to create a new repo and you can ask any question about this idea (if you have) in the comment section.

**Comment by Aju100** [comment]
Thank you @heming6666

**Comment by Aju100** [comment]
Hi @heming6666 ,

Can you please review my proposal for the Summer OSSP mentorship. I would love to get feedback from you. Thanks
https://docs.google.com/document/d/1ldnCmUxAI6TX8DOrgbHoYIiu_q4f4PNnqdPhzEb7pRA/edit?usp=sharing

**Comment by heming6666** [comment]
Hi @Aju100 

I have just reviewed your proposal. Overall the proposal is in really great shape and the sections easy to follow.

I have just a minor comment about the website. Beyond the prototype, you could add more infomation about what technology stack or front-end framework is intended to be used to implement the website.

All the best!

**Comment by Aju100** [comment]
Thank you @heming6666 . I have updated the proposal and I will submit it OSPP website. I have a question. We need two files (proposal and resume) in the zip file right ?

**Comment by heming6666** [comment]
> We need two files (proposal and resume) in the zip file right ?

Right.

**Comment by Aju100** [comment]
Thank you @heming6666 . I have updated everything and submitted too.

**Comment by Aju100** [comment]
Hey @heming6666 , i have got rejection for summer OSPP program. Can I get involve and do the things which I have shared it on the proposal.

**Comment by xiaoya-Esther** [comment]
Thank you @Aju100. I'm sorry you didn’t get selected. It's nothing about your proposal but we have a limit for the idea. You are more than welcome to get involved in the project, anytime.

I'm closing this issue because it's the OSPP development period.
