### ISSUE TITLE
Perceptor Tab repeats itself in release 

### ISSUE THREAD

**Issue by DantrazTrev** [hypertrons/hypertrons-crx#163]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [x] Raise a Question

## Introduction ot the issue

Perceptor Tab repeats itself repeatedly while switching tabs (for release)

![image](https://user-images.githubusercontent.com/43457420/121482549-e10a2200-c9ea-11eb-8920-192ead8092f6.png)

Probably has something to do with the Github token but this is not seen in the build version
## Process
1. Go to any repo
2. Go in deep file structure or sometimes not even that
3. Perceptor tab repeats itself and the tab eventually crashes

## Expected result

This thing does not happen at all in the dev build,

## Current result

Perceptor tab repeats itself and the tab eventually crashes

## Possible Fix

This probably got fixed in the later updates but I couldn't track where it was

**Comment by tyn1998** [comment]
Hi @DantrazTrev , this problem was mentioned in #145, and in next release(v1.0.1) it will be solved.

**Comment by DantrazTrev** [comment]
Thanks for the info @tyn1998
