### ISSUE TITLE
Perceptor Not Accessible when the window size is small

### ISSUE THREAD

**Issue by DantrazTrev** [hypertrons/hypertrons-crx#165]
## Type of Issue

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction of the issue
When the window size is minimized the preceptor tab should go into the three dots menu.
However, what we see there is one more Insight tab if the Insight tab is visible or no tab at all

## Process

1. Go to any repository
2. Decrease the window size till you get the three-dot menu
3. Check for the preceptor in the three dot menu

## Expected result

The preceptor should be there in the three-dot menu

## screenshot

![image](https://user-images.githubusercontent.com/43457420/121489935-3269df80-c9f2-11eb-9a02-d5d6c13061e2.png)

**Comment by LiuChangFreeman** [comment]
Thank you for reporting this bug.  
Fixed by https://github.com/hypertrons/hypertrons-crx/pull/168
