### ISSUE TITLE
[Feature] publish extension to Firefox adds-on too

### ISSUE THREAD

**Issue by Aju100** [hypertrons/hypertrons-crx#169]
Hi there,

A maximum number of users use chrome browser but firefox is also used by a huge number of people. I think extension should also be available in firefox adds.

This can help to have perceptor options in GitHub through the firefox browser too.

**Comment by LiuChangFreeman** [comment]
The release of Firefox version is not in current plan.   
If anyone can make a survey, we may consider it.

**Comment by Aju100** [comment]
Hi @LiuChangFreeman I understand about it. Should I disclose this issue as currently none of the maintainers might take it for the current plan?

**Comment by LiuChangFreeman** [comment]
> Hi @LiuChangFreeman I understand about it. Should I disclose this issue as currently none of the maintainers might take it for the current plan?
At your will.
