### ISSUE TITLE
[Doc] CONTRIBUTING.md: "npm run test" is currently not supported

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#170]
## Type of Issue
- [ ] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [x] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
["Make your changes"](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md#5-make-your-changes) in CONTRIBUTING.md asks contributors to `run npm test` before `git add & commit`, however `run npm test` is not supported in the current version of hypertrons-crx:
https://github.com/hypertrons/hypertrons-crx/blob/f445fbd1fbf40e1e6a15e45cf382fb92a3ad881b/package.json#L7-L14

PS: `npm run test` was supported in an [early version](https://github.com/heming6666/hypertrons-crx/blob/66d435e5537a16dafc13a473f3070310188cbc6a/package.json#L66-L73) of hypertrons-crx.

**Comment by heming6666** [comment]
Yes. It would be great if anyone can add unit test for the project :-)

**Comment by LiuChangFreeman** [comment]
Since `hypertrons-crx` is an almost pure front-end project, tests are not easy to write.

**Comment by DantrazTrev** [comment]
> Since `hypertrons-crx` is an almost pure front-end project, tests are not easy to write.

What would be in the tests? I'm still a bit curious. Considering the extension primarily interacts with github.com, most of the front-end tests go a bit fuzzy for me. However, the mock data could be an excellent one for testing the graphs and other components

**Comment by LiuChangFreeman** [comment]
> > Since `hypertrons-crx` is an almost pure front-end project, tests are not easy to write.
> 
> What would be in the tests? I'm still a bit curious. Considering the extension primarily interacts with github and gitlab most of the front-end tests go a bit fuzzy for me. However, the mock data could be an excellent one for testing the graphs and other components

Tests for the graph component may be a good idea.

**Comment by tyn1998** [comment]
`npm run test` was removed and now we put `yarn run prettier` to its place.
