### ISSUE TITLE
[feature] I need a button for closing the hypertrons-crx quickly

### ISSUE THREAD

**Issue by stevending1st** [hypertrons/hypertrons-crx#178]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
If I want to close the hypertrons-crx, I should go to the Expand Page and close the hypertrons-crx. It’s not a good experience, I think. I need a submenu in the toolbar to do this.

## screenshot
![image](https://user-images.githubusercontent.com/23376142/122366231-f1dc0a00-cf8d-11eb-931b-4a37d6fa2df2.png)

|  incon  |
|----------------|
|    ON / OFF    |
|      Setting      |

**Comment by LiuChangFreeman** [comment]
You can just right click the icon and manage the extension through the entry on the menu fly out.  
This is the method provided by browser default.

**Comment by stevending1st** [comment]
> You can just right click the icon and manage the extension through the entry on the menu fly out.

What I thalk is **EXPERIENCE** but not how I can do it.

**Comment by LiuChangFreeman** [comment]
> > You can just right click the icon and manage the extension through the entry on the menu fly out.
> 
> What I thalk is **EXPERIENCE** but not how I can do it.
> 
> The **Tampermonkey**, the world famous browser plugin, provides this feature instead of letting the user adopt the browser default to make the plugin stop working. Similarly, there is the AdBlock.

We'll consider it. Thank you for your suggestion.
