### ISSUE TITLE
[feature] Add Description about Token

### ISSUE THREAD

**Issue by stevending1st** [hypertrons/hypertrons-crx#179]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
I think Token is a sensitive data because it involves information security. The hypertrons-crx should specify the minimum permissions of the token.

**Comment by LiuChangFreeman** [comment]
Currently hypertrons-crx only needs the basic permission of the token. 
We only use it to get files from repositories and we don't recommand user to give permissions beyond this.  
All these will be improved as a more serious tutorial is released.

**Comment by stevending1st** [comment]
> All these will be improved as a more serious tutorial is released.

I look forward to a more detailed explanation, otherwise the function will not be used at this time.

**Comment by LiuChangFreeman** [comment]
Solved by https://github.com/hypertrons/hypertrons-crx/pull/187/commits/c9be945eca2a46dbb490ef5d99c916cceae3b471

**Comment by DantrazTrev** [comment]
@LiuChangFreeman , we might want to update the docs as well for the token info, if you won't mind we could do it as a part of  #136

**Comment by LiuChangFreeman** [comment]
> @LiuChangFreeman , we might want to update the docs as well for the token info, if you won't mind we could do it as a part of #136

Just do it

**Comment by DantrazTrev** [comment]
@LiuChangFreeman While working on this I had a query is there a way to remove the said token? Seems kinda important.

**Comment by LiuChangFreeman** [comment]
> @LiuChangFreeman While working on this I had a query is there a way to remove the said token? Seems kinda important.

Next commit will offer this
