### ISSUE TITLE
[refactor] Refactor project using React.

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#18]
## Why we need it ?
The project currectly is based on `js` + `jquery`， which is quite simple and easy to get started. However, with more and more features are added to `hypertrons-crx`, it would be convenient for us to build the project based on some existing framework. And `React` is one of the excellent framework for building user interfacesfor. It can help us:
- Create interactive UIs.
- Build encapsulated components that manage their own state, then compose them to make complex UIs.
- Use beautiful UI library(e.g. `antd`)
- and so on....

## How to do ?
1. Use `create-react-app` to set up the project.
2. Modify `manifest.json` to clarify the dist file structure.
3. Modify `webpack` configuration to generate the specified files.

I am open to hear all of the opinions. Thanks~

**Comment by frank-zsy** [comment]
I believe `React` is a good solution for this project, I am wondering how can we test the crx? If the compiled files are also in the project?

**Comment by heming6666** [comment]
It's a good question but actually I am not sure which one is the best solution right now 😑. One possible solution is using [`jest`](https://jestjs.io/) to do the unit test. I believe that test is quite important and I will include unit tests in this PR.

**Comment by heming6666** [comment]
I choose `jest` to do the logic test and snapshot test. 

### Function & Logic Test
It's quite similar with what we did in `hypertrons`. Refer to : https://jestjs.io/docs/en/getting-started

### Snapshot Test
Snapshot tests are a useful tool to make sure the UI does not change unexpectedly. Refer to: https://jestjs.io/docs/en/snapshot-testing

About how to use jest in create-react-app: https://create-react-app.dev/docs/running-tests/#writing-tests
