### ISSUE TITLE
Some issues with .gitignore

### ISSUE THREAD

**Issue by DantrazTrev** [hypertrons/hypertrons-crx#184]
## Type of Issue

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [x] Raise a Question

## Introduction to the issue

The .gitignore should be excluding a lot of log files in web-ext( From what I could infer)

However, this isn't happening as expected and I see a lot of tracked logs 
![Screenshot from 2021-06-18 02-12-29](https://user-images.githubusercontent.com/43457420/122470051-4194f280-cfdb-11eb-955a-851054e6a77a.png)

## Expected result

There shouldn't be this many tracked log files

## Possible Fix

Update .gitignore for all the files in `utils/web-ext`?

**Comment by LiuChangFreeman** [comment]
That should be improved. @heming6666

**Comment by LiuChangFreeman** [comment]
fixed by https://github.com/hypertrons/hypertrons-crx/blob/fd0383bf573c4dc7e195ac36aabea7f419df1a14/.gitignore
