### ISSUE TITLE
[discussion] New name for this project

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#189]
<!-- hypertronsMetaData: {"choices":["Hyperx","Hyperext","Hypercrx","Hypexin","Visoron"],"participants":["anyone"],"duration":259200000,"launchTime":1625058136151,"comment_id":871384474} --!>
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [x] Raise a Question

## Introduction to the issue

The name `hypertrons-crx` isn't good enough for a product.  

## Process

We can give a new name to it.  Just as the procedure  
1. `Cybertrons`, name from a movie. 
2. `Hybertrons`, change C to H.  
3. `Hyberextension`, associate chrome extension with Hybertrons

## Expected result

New names

**Comment by DantrazTrev** [comment]
If this an open discussion then how about `Hypexin` or  `Visoron` ?

**Comment by will-ww** [comment]
I propose some kinds of  Hyper + extension. As this is a Hypertrons ecosystem project, and extension can also describe the scenario that Hypertrons extent to other platform, suche as explorer. 

So the name can be: _Hyperx_, _Hyperext_, _Hypercrx_, ect.

**Comment by frank-zsy** [comment]
/start-vote Hyperx Hyperext,Hypercrx,Hypexin,Visoron anyone 3d

**Comment by frank-zsy** [comment]
/start-vote Hyperx,Hyperext,Hypercrx,Hypexin,Visoron anyone 3d
