### ISSUE TITLE
[enhancement] Add ESLint and Prettier to project.

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#19]
In order to keep the code style in a good shape and format the code automatically, it's recommend to use `ESLint` and `Prettier` in our project.

**Comment by frank-zsy** [comment]
If we develop the project with TypeScript, should we use `ESLint` or `TSLint`? Although I realize that lots of Typescript project are using `ESLint`.

**Comment by heming6666** [comment]
I think both are good for our projerct. But `ESLint` is recommended because the team behind `TSLint` have decided that they would no longer support it. Refer to https://palantir.github.io/tslint/

**Comment by heming6666** [comment]
## ESLint & Prettier

We use `umi-fabric` which provides some presets for `eslint` , `stylelint` and `prettier`. All open rules are meaningful for improving code quality.

Here's the `ESLint` configuration:
```
# .eslintrc.js
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
};
```

```
# .prettierrc.js
const fabric = require('@umijs/fabric');
module.exports = {
  ...fabric.prettier,
};
```

**Comment by heming6666** [comment]
Close by pr #21 .
