### ISSUE TITLE
Possibly not getting the teach bubble if we're away from the perceptor tab

### ISSUE THREAD

**Issue by DantrazTrev** [hypertrons/hypertrons-crx#190]
## Type of Issue
- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
In certain cases, the teaching bubble comes up even if you're down at the page and away from the preceptor tab.
![image](https://user-images.githubusercontent.com/43457420/123440046-ffc60680-d5ef-11eb-9d80-b1f20d6afebb.png)

## Process
Go to a suitable page where you can see a teaching bubble from the preceptor
Scroll down 
Got forward to any link or page
Come back

## Expected result

Should be only shown at the correct position

## Current result

We see a teaching bubble at the wrong position

**Comment by LiuChangFreeman** [comment]
I think this isn't a bad case, just like the as the official example here:  
https://developer.microsoft.com/zh-CN/fluentui#/controls/web/teachingbubble  
teachingbubble  indicates that there is something you should notice even if it's beyond what you can see on the page

**Comment by DantrazTrev** [comment]
Hmm that's reasonable 🤔 . I wonder if there's a way to let it stick around in such situations
