### ISSUE TITLE
[feature] Add basic Radar chart component

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#194]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## The 1st step to Summer 2021
Thank you for selecting me to challenge [the task](https://summer.iscas.ac.cn/#/org/prodetail/210230454). As I gave in [my plan](https://shimo.im/docs/kQhQK9h8jkTwpy8K#anchor-josS), I will focus on Echarts and AntV in week 1-3 and output a basic Radar chart component (BRadarCC). That is my first step.

I have created a public yuque repository (in Blob style) called ["我的Summer2021"](https://www.yuque.com/tyn1998/summer-2021), and I will update personal progress there. Welcome to your visits.

## About basic Radar chart component
The illustration below shows the big picture of my plan. BRadarCC is one of a series of Basic Charts Componets. "Basic" means these components are the encapsulations of Echarts and AntV charts and provided for higher level components for more detailed use.
![image](https://user-images.githubusercontent.com/32434520/124228958-82dee380-db3f-11eb-9642-dc44692c57ad.png)

**Comment by LiuChangFreeman** [comment]
Nice job!

**Comment by tyn1998** [comment]
It's been so long since I posted this issue 3 weeks ago. Stop for a while and come back to this page with a **half-finished** `basic Radar chart component` which is really easy to configure.

![image](https://user-images.githubusercontent.com/32434520/126925375-fccb1828-e53f-432a-a4c8-9f8eab512dc4.png)

After diving into Radar charts of [Echarts](https://echarts.apache.org/zh/option.html#tooltip.formatter) and [Ant Design Chart](https://charts.ant.design/zh-CN/demos/radar/?type=api) for a lot of days, I found out common features that both library provide and work out a TS interface. And then I finished AntV part of my plan:

![image](https://user-images.githubusercontent.com/32434520/126926303-4c47fc1d-3008-4860-b199-8e1dc4efd08a.png)

In next few days, I will finish Echarts part to fully work out `basic Radar chart component` .

**Comment by tyn1998** [comment]
Since we decided not to continue to encapsulate charts of Echarts and AntV (instead focus on Echarts only) in last Tencent online meeting, I will close this issue. In next phase, we will explore into Echarts [dynamic charts](https://echarts.apache.org/examples/zh/editor.html?c=bar-race).
