### ISSUE TITLE
[feature] Dynamic Bar component

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#216]
## Type of Issue
- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Description
A brand new `DynamicBar` component to display the ranking of a specific indicator (e.g. users' activity) over time. Like [this](https://jannchie.github.io/anichart.io/en/demo/bar).

![Peek 2021-09-01 22-45](https://user-images.githubusercontent.com/32434520/131692594-6ab5a006-eb92-4258-b722-8fe1a4293bc2.gif)

**Comment by will-ww** [comment]
So cool~

**Comment by heming6666** [comment]
Closed by #221 .
