### ISSUE TITLE
[feature] Update the CLA

### ISSUE THREAD

**Issue by stevending1st** [hypertrons/hypertrons-crx#217]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue

We discussed the contents related to CLA in [this discussion](https://github.com/hypertrons/hypertrons-crx/discussions/182).
So far, there is no update CLA.
If you want to modify the CLA, you need to add a file with the CLA content in [gist](https://gist.github.com/), then modify the CLA template at [cl-assistant.io](https://cl-assistant.io/).

**Comment by heming6666** [comment]
Sorry for the late reply.  .

Thank you @stevending1st for raising the discussion about the mistake of `CLA`. We have updated the right version of `CLA`. You can check it [here](https://cla-assistant.io/hypertrons/hypertrons-crx).

Thank you for your effort!

**Comment by stevending1st** [comment]
> Sorry for the late reply. .

No problem, Thx you for your work. This is an interesting project.

**Comment by heming6666** [comment]
> No problem, Thx you for your work. This is an interesting project.

Thank you @stevending1st for your interest and contribution.
