### ISSUE TITLE
[feature] Add basic configuration management

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#22]
We need add basic configuration for users including:
- Turn on/off cross-platform message notification
- Turn on/off cross-platform interactive cmd-line

@frank-zsy Please help look into this if I missed something that should be included in project. Thank you~

**Comment by frank-zsy** [comment]
I think we don't really need to notification or interactive command line right now, we can only develop the dashboard part, but the dashboard maybe need to render from a configuration file which stored in the repo. Like `.github/hypertrons-dashboard.json`, something like that.

**Comment by heming6666** [comment]
Got it. I agree that the dashboard should be rendered from a configuration. But I have a question:

If we store the configuration file in the repo, something like:
```json
"hypertrons-dashboard": {
    "user": {
        "dashboard1":{ ... },
        "dashboard2":{ ... }
    },
    "contributor": {
        "my-contribution-list":{ ... }
    },
    "committer": {
        "issue-effiency":{ ... },
        "issue-backlog":{ ... },
    } 
    ...
}
```
It means that the configuration is based on role system. And all of the users will see the same dashboards (so do contributors and committers). 

My question is: should we allow users to modify the configuration by themselves and store the configuration for each user? In that case, we provide default configuration according the role of user, and they they can modify the configuration in the extention's menu.

**Comment by heming6666** [comment]
Please move to #70 for more discussion.

Close.
