### ISSUE TITLE
[Feature] Show the top devleoper and scores.

### ISSUE THREAD

**Issue by winlinvip** [hypertrons/hypertrons-crx#234]
这个活跃度指标确实很客观，我们打算作为衡量社区贡献的指标。

比如我们有技术委员会，那么谁是核心开发者，谁贡献大，谁可以发文化衫，凭感觉很容易得罪人，用这个指标作为重要参考，就会很好。

但是目前看不到项目的top开发者的分数，有个关系图还需要一个个去看，而且还不知道哪些是项目的开发者，哪些不是，非常麻烦。

![image](https://user-images.githubusercontent.com/2777660/141609372-47e160f9-a6e8-4303-91b7-de3c2d5a1049.png)

比如左侧的图，要拿到top10就很困难，要人眼判断下哪个球大，有些还不是开发者是机器人账号(codecov-commenter)。

是否可以在右侧列出top user和分数呢？

**Comment by tyn1998** [comment]
即将上线另一个组件#233，该组件非常直观地展示了仓库内贡献者的活跃度排名情况，敬请关注～

**Comment by wxharry** [comment]
@tyn1998 This issue is related to the new feature racing bar, but I am not sure it is fully resolved, do we have plans on showing users' rank?

**Comment by tyn1998** [comment]
@wxharry My idea is to let the racing bar display the latest activity details before it plays, so the static racing bar can satisfy the need mentioned in this issue.

Also related to #729.
