### ISSUE TITLE
[Feature] A place to show the repo's history most active contributors

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#263]
## Description
The contributors' activity scores are reflection of their involvement in **recent 180 days**, which makes it easy for visitors to know who are **currently** the most active ones in the repo. However, we cannot forget those who were active in the past.

So maybe we can design a chart or whatever to list the top3(or N) contributors by month?

## Type of Issue
- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

**Comment by wxharry** [comment]
I am closing this as racing bar chart is implemented #696
