### ISSUE TITLE
[BUG] Incorrect background display on Edge browser

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#264]
## Type of Issue
_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
I installed the edge extension following this [document](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.md) and the background color of the dialog seems to have lost its value.  It seems that the Edge extension is not up-to-date, it is still `version 1.0.2` and the latest released version should be `version 1.3.0`. 

![image](https://user-images.githubusercontent.com/39271899/150452597-3c8e8575-3b2f-41d3-845a-acd01c16069f.png)

**Comment by tyn1998** [comment]
Thanks for your feedback! You're right, we will spare no effort to recall our edge store account password to update the extension.

**Comment by wxharry** [comment]
Thanks for your efforts! I received a notification today said that a new version 1.3.0 is available on Edge and I tried it out. The extension is now updated to the latest release.

**Comment by wxharry** [comment]
> Thanks for your efforts! I received a notification today said that a new version 1.3.0 is available on Edge and I tried it out. The extension is now updated to the latest release.

My fault! The extension was not updated from the Edge extensions store, but from the Chrome extensions store. Anyway, it works.

**Comment by tyn1998** [comment]
> Thanks for your efforts! I received a notification today said that a new version 1.3.0 is available on Edge and I tried it out. The extension is now updated to the latest release.

What a cute mistake! But as you find out later, we have not updated the extension in Edge Extension Store because, emm, we lost our account for Edge.

We will create a new account on Edge this vacation. Before that, your solution of adding an extension to E from C goes to our aid.

**Comment by tyn1998** [comment]
We have created a new Edge account, I believe it won't take long to see a brand new hypercrx add-on on Edge extension store.

**Comment by tyn1998** [comment]
Hi, the edge version extension was submitted and waits for audit

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/32434520/156697991-76f6f246-5d25-403c-84bc-dfbb0c1159f8.png">

**Comment by tyn1998** [comment]
Edge extension available now! 

check it out: https://microsoftedge.microsoft.com/addons/detail/hypercrx/lbbajaehiibofpconjgdjonmkidpcome
