### ISSUE TITLE
[BUG] Failed to be compatable with dark modes

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#266]
## Type of Issue
- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue

I am using `Dark Dimmed` theme on my Github and the color of the font doesn't change to be compatable with the dark theme modes and users may barely read what are showed on that dialog. 

![image](https://user-images.githubusercontent.com/39271899/150455336-4657f759-9c60-4b12-a3ff-740d4472387a.png)

**Comment by tyn1998** [comment]
Thank you for your feedback! We will work on this ASAP.

**Comment by tyn1998** [comment]
Start working on this.
