### ISSUE TITLE
[BUG] Incorrect highlight on tab bar

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#267]
## Type of Issue

- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue

`hypercrx` could create a new tab `Perceptor` in one repo. When I am using `hypercrx`, the new tab does appear, but when I click it on the tab bar, both `Insights` and `Perceptor` become highlighted. I guess `Insights` should not be highlighted when clicking `Perceptor` because it seems to be a different tab, so it could be a bug.

![image](https://user-images.githubusercontent.com/39271899/150456404-d2022b70-a281-4390-bf49-93d647b8404e.png)

**Comment by tyn1998** [comment]
Wow, you are a Bug catcher! Thank you for reporting, we will fix this ASAP.
