### ISSUE TITLE
[doc] we need to explain those unlinked nodes in networks

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#268]
## Description
![image](https://user-images.githubusercontent.com/32434520/150718695-eae9e51f-02c1-471e-bf53-dd28062d04ec.png)

I remember there is something like "threshold" or so in the code that related to networks, so the unlinked nodes are designed to be unlinked, but our users do not know.

We should figure it out and explain it to our users.

## Type of Issue
- [ ] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [x] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

**Comment by smitsekhadiaa** [comment]
hey @tyn1998  can I take up this issue.
I think will be able to fix it.

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 can I take up this issue.
I think I will be able to fix it.

**Comment by tyn1998** [comment]
Hi smit, the unlinked nodes may not be a bug but designed in this way on purpose. This issue requires further document which I think is not for newcomers.

Instead, you can try #328.

**Comment by smitsekhadiaa** [comment]
oh okay @tyn1998  yes ill try solving issue #328 
Also I was wondering that in the readme there is an incomplete image of developer collaboration network
I would be glad to fix that if possible.
Should I update it and send Pull request?
Thankyou.

**Comment by tyn1998** [comment]
What do you mean "incomplete", can you put on a screenshot?

**Comment by smitsekhadiaa** [comment]
![image](https://user-images.githubusercontent.com/90528630/167239960-447d0a68-0152-4cd7-b7b9-5ddfa12c2946.png)



here the devleoper collabration network image

**Comment by tyn1998** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/32434520/167240930-d89b3e0c-7a5e-45f9-9b65-16ceadc1dd8c.png">
Maybe you should forced-refresh your page. It seems like a network issue.

**Comment by smitsekhadiaa** [comment]
oh okay @tyn1998

**Comment by tyn1998** [comment]
The reason of edge disappearance is: they are removed on purpose to make a dense graph sparse so they become more readable.
