### ISSUE TITLE
[CI/CD] automatically push latest extensions to Chrome/Edge store 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#290]
Currently we have to **manually** submit our released extensions to both Chrome and Edge extension store. Maybe there is a better way to automate this flow.

**Comment by tyn1998** [comment]
Reading this: https://gokatz.me/blog/automate-your-chrome-extension-deployment-in-minutes/

**Comment by wxharry** [comment]
Will you consider using [chrome-webstore-upload-cli](https://github.com/DrewML/chrome-webstore-upload-cli)?

**Comment by tyn1998** [comment]
The blog I mentioned actually uses chrome-webstore-upload~ If we do not want a separate file like deploy.js to do the uploading job we can put all logic into workflow yaml file by using chrome-webstore-upload-cli.

**Comment by tyn1998** [comment]
For edge store, refer to https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api

**Comment by tyn1998** [comment]
For edge add-on store, I plan to leverage [@plasmo-corp/ewu](https://www.npmjs.com/package/@plasmo-corp/ewu) to automatically upload the extension, following this [blog](https://blog.plasmo.com/p/edge-extension).

If we can support more browsers in the future, [web-ext-deploy](https://www.npmjs.com/package/web-ext-deploy) is also in consideration. It supports: chrome, firefox, edge and opera.
