### ISSUE TITLE
[Data & UI] I would like to expose all activity and influence index for all users and repos 

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#297]
## Type of Issue

- [x] Feature Request

## Introduction to the issue

 I would like to expose all activity and influence index for all users and repos, we may need new diagrams to show the data in hypercrx like trending line charts.

**Comment by tyn1998** [comment]
Maybe in Code Tab, we can present the latest data such like current activity & incluence. And if users seek for more detailed info such as trend or history of the indices, they can find in Perceptor Tab.

Just a little idea.

**Comment by frank-zsy** [comment]
I could be done like this but I think maybe users want to see the trending right on the repo's home page, I am not sure which one is better. Maybe we can implement an edition and find some users to choose.

**Comment by frank-zsy** [comment]
I have put the data online for anyone to use. As there are too many repos and users in the history, almost 40 million, I just put the users and repos with recent activity. So the amount is about 1 million users and 1 million repos. The data will update monthly to update the users and repos which have active events in last month.

The users info URL is like:
https://hypertrons-oss.x-lab.info/activity_influence/actors/f/frank-zsy.json , to avoid too many files in one directory, I add the subdirectory before the final file which uses the lower case of the first character of the login which is `f` for `frank-zsy`, and `l` for `LinuxSuRen`.

The repos info URL is like:
https://hypertrons-oss.x-lab.info/activity_influence/repos/hypertrons/hypertrons-crx.json , this one is as simple as it looks like, the path will be `repos/${owner}/${repo}.json`.

Right now only activity and influence data are provided for all users and repos.

**Comment by tyn1998** [comment]
Got it! Thank you.

**Comment by tyn1998** [comment]
@frank-zsy, why 404 NOT FOUND "https://hypertrons-oss.x-lab.info/activity_influence/actors/x/xiaoya-Esther.json"? Is this data not computed?

**Comment by frank-zsy** [comment]
> @frank-zsy, why 404 NOT FOUND "https://hypertrons-oss.x-lab.info/activity_influence/actors/x/xiaoya-Esther.json"? Is this data not computed?

That maybe because she did not have any activity duration 2021.12, so her data is not included. Since I recalculate the influence data, I will export a new version with all active users and repos in last 6 months. And I am consider to remove the redundant prefix dir `x` and flatten all the files.

**Comment by tyn1998** [comment]
Got it~

**Comment by frank-zsy** [comment]
For performance consideration, I may reduce the data set to all users and repos which have at least 10 activity score in last 6 month which will remove lots of inactive users and repos. Is that make sense for you?

**Comment by tyn1998** [comment]
It is not a problem because currently the Trend charts component just won't show if corresponding data is not found.

and something to confirm: the time span of the data is still 2015~2021, right?

**Comment by frank-zsy** [comment]
The time span will be 2015 to last month now. For now it is 2022.2 and 2022.3 for next month.

**Comment by tyn1998** [comment]
That would be nice!

**Comment by frank-zsy** [comment]
The new data has been uploaded under a new domain: https://oss.x-lab.info/hypercrx_actor/tyn1998.json, the repo data is like: https://oss.x-lab.info/hypercrx_repo/hypertrons/hypertrons-crx.json .

As the data will be exposed to public, we will use `oss.x-lab.info` in the future, is that OK with you? @tyn1998
