### ISSUE TITLE
[Feature] Need to add `SimpleTable` class

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#3]
The `SimpleTable` class need to be implemented, used to add table to dashboard.

The table should be configurable, like
- title
- columns
- theme color

And default table style should be added into `common/css/style.css` to provide basic style.

**Comment by heming6666** [comment]
Now we use `fluent-ui` for `table` components.

Please refer to https://developer.microsoft.com/zh-CN/fluentui#/controls/web/detailslist for the usage.

Close.
