### ISSUE TITLE
[request] An "admin" or "maintain" role  is required to better organize things happen in the repo

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#303]
Guys, I would like to have an "admin" or "maintain" access to our project to better manage all things happen here. @frank-zsy @LiuChangFreeman @heming6666

**Comment by frank-zsy** [comment]
Of course, and what privilege you want exactly, like merge PR or change repo setting?

**Comment by tyn1998** [comment]
Like managing Projects（项目看板）. The access to merging PR is also great!

**Comment by frank-zsy** [comment]
https://github.com/hypertrons/hypertrons-crx/invitations invitation has been sent to this link.

**Comment by tyn1998** [comment]
That's great, thank you!
