### ISSUE TITLE
[BiweeklyReport] BiweeklyReport for Hypercrx 2022-03-08 to 2022-03-21

### ISSUE THREAD

**Issue by zhuxiangning** [hypertrons/hypertrons-crx#311]
Hypercrx biweekly report is here！

From March 8 to March 21, there are 5 PRs merged in our project~

**Main progress:**

- Chrome/Microsoft Edge Sync Update v1.4.5
- Updated some configuration files of the project and fixed some known issues

**Details:**

- [PR 309](https://github.com/hypertrons/hypertrons-crx/pull/309)/[Issue 305](https://github.com/hypertrons/hypertrons-crx/issues/305)：[fix] relocate Perceptor Tab for new GitHub page layout
- [PR 308](https://github.com/hypertrons/hypertrons-crx/pull/308)/[Issue 304](https://github.com/hypertrons/hypertrons-crx/issues/304)：[DEP] bump versions of deps suggested by synk-bot
- [PR 307](https://github.com/hypertrons/hypertrons-crx/pull/307)/[Issue 306](https://github.com/hypertrons/hypertrons-crx/issues/306)/[Issue 244](https://github.com/hypertrons/hypertrons-crx/issues/244)：[DEP] remove anichart.js and related components
- [PR 296](https://github.com/hypertrons/hypertrons-crx/pull/296)/[Issue 295](https://github.com/hypertrons/hypertrons-crx/issues/295)：[manifest] remove management permission from manifest.json
- [PR 293](https://github.com/hypertrons/hypertrons-crx/pull/293)：[version] bump hypercrx from 1.4.0 to 1.4.4

**Comment by will-ww** [comment]
Many thanks, it's great~

**Comment by tyn1998** [comment]
When pages or wiki is set up(#316 #315), the reports can be put there in a better organized structure~
