### ISSUE TITLE
Show the right version link for users.

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#312]
## Type of Issue

- [x] Documentation incomplete

## Introduction to the issue

I think the link in [README.md](https://github.com/hypertrons/hypertrons-crx/blob/master/README.md#install) still points to old version of the extension, the update last time is 2021.6.11 and the version is 1.0.1. We should update the doc so users can use the right version.

And also the link in update notification is also the old version URL, should update it too.

**Comment by tyn1998** [comment]
@wxharry Thanks! You are so welcomed to improve the documents of hypercrx, and maybe you would like to begin this work after this new feature(#301) is merged.

**Comment by wxharry** [comment]
My pleasure. Maybe I can start with replacing the old links.
