### ISSUE TITLE
[doc] We should launch Wiki pages for developers

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#315]

**Comment by wxharry** [comment]
We have a [website](https://github.com/hypertrons/hypertrons-crx-website). What's the difference?

**Comment by tyn1998** [comment]
The website is for normal users I think. Wiki, however, is for the purpose of writing down all technical details so interested developers can know how to develop the extension.

**Comment by wxharry** [comment]
Hey Lam @tyn1998! Do we have an outline on what we are going to add to the wiki?

**Comment by wxharry** [comment]
* #369 
* #393 
* #370 
* [Keep "service worker" DevTools page open](https://github.com/hypertrons/hypertrons-crx/pull/274#discussion_r811878203)

**Comment by tyn1998** [comment]
Thank you for listing the existing subtasks here!



> Do we have an outline on what we are going to add to the wiki?

Well, the anwser is... not yet.

**Comment by wxharry** [comment]
> Thank you for listing the existing subtasks here!
> 
> > Do we have an outline on what we are going to add to the wiki?
> 
> Well, the anwser is... not yet.
 
I will help with the wiki, just append anything that came to your mind to that list so that we can work on it 😸

**Comment by tyn1998** [comment]
Actually we already have wiki pages, but need to add more stuff.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/32434520/196327149-a071b05e-0bbd-4a90-b1af-e2de3c6dc6d4.png">
