### ISSUE TITLE
[feature] add self-assign button on issue pages.

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#32]
Currently, we need to type `/self-assign`  command to assign the issue to ourselves. It would be nice if we have a `self-assign` button  to click.  See the example below:

![image](https://user-images.githubusercontent.com/26642280/94657269-c946ae00-0333-11eb-9fbd-e63f4a3b3b33.png)

There are several things need to be considered:

- Where this button located.

- When to show this button.

- What will happen after click.

...

**Comment by frank-zsy** [comment]
It looks great and the flow is OK too. But `inject button->click button->GitHub API` kind component should be in identical implementation.

**Comment by heming6666** [comment]
I get it.

**Comment by heming6666** [comment]
This issue has been out-of-date. Reopen it when necessary.

Closed.
