### ISSUE TITLE
[Summer2022] Let's brainstorm tasks(projects) to be submitted!

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#322]
### Discussed in https://github.com/hypertrons/hypertrons-crx/discussions/321

<div type='discussions-op-text'>

<sup>Originally posted by **tyn1998** April  2, 2022</sup>
So we have two levels of tasks this year (3 levels last year):
>According to the difficulty of the project, the amount of project funding can be divided into 12000 RMB, and 8000 RMB

link: https://summer-ospp.ac.cn/help/en/

Guys let's put some ideas here!</div>

This issue is just for project tracing, please **do not comment** below.

**Comment by will-ww** [comment]
Great，GOGOGO~

**Comment by will-ww** [comment]
Maybe we can also involve our undergraduate and graduate students to join in from our oss courses~ @zhuxiangning

**Comment by tyn1998** [comment]
At last, we have #347 and #348.
