### ISSUE TITLE
[UI] Show profile pictures in contributor network and update README

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#328]
We have implemented this feature in [OpenGalaxy](https://github.com/X-lab2017/open-galaxy):
<img width="347" alt="image" src="https://user-images.githubusercontent.com/32434520/161474748-7cc19dd6-d573-4c12-a34b-d52dc0c39849.png">
Why not to clone it into this repo?

**Comment by zhuxiangning** [comment]
Good idea & looking forward to going online soon~

**Comment by smitsekhadiaa** [comment]
hey @tyn1998  @zhuxiangning  I had the look at the codebase and tried to understand the developers network , for solving this issue 
can i replace the node colors with `https://avatars.githubusercontent.com/<username>`  then i guess the issue will be solved?



Thankyou, Regards.

**Comment by tyn1998** [comment]
Hi smit! Why not have a try and a run?
Looking forward to your good news.

You can refer to [quick start](https://github.com/hypertrons/hypertrons-crx#quickstart) for running this project.

**Comment by tyn1998** [comment]
hello, @smitsekhadiaa~ Do you have any progress on this feature request?

**Comment by smitsekhadiaa** [comment]
Yes @tyn1998   I was able to  successfully get the profile image link of the contributor on the console of the page, now the nodes colours has to be replaced by the data we get on the console.
Currently I am working on my proposal thats why I couldn't give much time to this issue
Once I am done drafting my proposal I will work on the issue👍

**Comment by tyn1998** [comment]
Sure~

By the way, what do you mean by "on the console of the page"?

**Comment by smitsekhadiaa** [comment]
![image](https://user-images.githubusercontent.com/90528630/170818544-2812bfad-5f12-4fc6-a377-0d708d86922b.png)

i would like to know your thoughts weather I am on the right track or you could guide me to a different approach.

Thankyou, Regards

**Comment by tyn1998** [comment]
Hi @smitsekhadiaa, so you just console.log(endpoint + userID), right? It is totally right and a good first step.

Actually, I hope you can look into details of options that Echarts provide, which has a strong relationship with this project, so you can get more familiar with Echarts.

Some hint: https://echarts.apache.org/en/option.html#series-graph.data.symbol

**Comment by smitsekhadiaa** [comment]
yes @tyn1998 
i have already started looking into echarts for implementng dynamic racing bar, i will dive into it further👍

thankyou for the hint, things are much more clear to me now

Thankyou, Regards

**Comment by smitsekhadiaa** [comment]
hey @tyn1998  , @zhuxiangning 
I think I have solved this issue,
these are the results:


Active Developer collaboration network:
![active developer](https://user-images.githubusercontent.com/90528630/171362112-73bbc4b1-5cce-4f74-9639-569630b1e3cb.png)

Project correlation network:

![project coorelation](https://user-images.githubusercontent.com/90528630/171362043-15355e76-62fd-45a3-acb7-68aae248cc05.png)



Developer Collaboration network:
![developercollaboration](https://user-images.githubusercontent.com/90528630/171361992-4e36644b-3929-48a3-aea3-703f385cd89b.png)


Most Participated Repos:
![mostparticipated repos](https://user-images.githubusercontent.com/90528630/171362185-2248f401-d7e8-40b6-874d-451c101da994.png)


I hope this was the required output.
Please let me know your thoughts.

Thankyou, Regards

**Comment by smitsekhadiaa** [comment]
yes @tyn1998 
I'll do that right now.
Should I also create another PR to update the readme doc with the new video demo of the pages?

**Comment by smitsekhadiaa** [comment]
> That would be wonderful~ Thank you!

Yes ill do that 👍

Actually I meant a short video like this one which is already present in the current readme, I could replace it with the current changes done on the pages 

![image](https://user-images.githubusercontent.com/90528630/171395605-abfdce30-3bba-4a94-9ca7-76b2723d588e.png)

**Comment by tyn1998** [comment]
Ok, you mean gif. That is great~

**Comment by smitsekhadiaa** [comment]
Hey @tyn1998 
harry pointed out that prettier was not run on all the files,
I was thinking to issue a PR for the updation of readme doc and I will create that PR after running prettier and updating the Readme
is that okay?

Thankyou,Regards.

**Comment by tyn1998** [comment]
Hi @smitsekhadiaa, it is ok.

I will change the title of this issue and reopen it, your new PR can resolve it.

**Comment by smitsekhadiaa** [comment]
Hey @tyn1998 
I have created new PR with updated readme and issued the PR after proper formatting of code by `yarn run prettier`.
Thankyou

**Comment by tyn1998** [comment]
closed via #358.
