### ISSUE TITLE
perceptor not display on edge

### ISSUE THREAD

**Issue by zsz00** [hypertrons/hypertrons-crx#341]
perceptor not display on edge
edge version 100.0.1185.44 (正式版本) (64 位)
![image](https://user-images.githubusercontent.com/12711073/164611563-e98206d7-c9e1-4fb2-9db3-08d9dd3c46b7.png)

![image](https://user-images.githubusercontent.com/12711073/164611654-69bc74e7-f387-4ad1-965e-9534a17786be.png)

**Comment by tyn1998** [comment]
Thank you for your report! Perceptor on chrome fails to show, too. I suppose DOM or css of  GitHub have changed again.

**Comment by tyn1998** [comment]
It might be a problem relating to security cert:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/32434520/164876930-9c4f2767-76a7-4104-96a9-5e766a25e2ab.png">
I will contact the admin of the website.

**Comment by tyn1998** [comment]
Solved! Thanks @JingbenShi668!
