### ISSUE TITLE
[Question] How to do documentation between GitHub and Yuque

### ISSUE THREAD

**Issue by will-ww** [hypertrons/hypertrons-crx#346]
I have see some of the docs of Hypercrx on Yuque: https://xlab2017.yuque.com/me1x4f/fg8ngy

![image](https://user-images.githubusercontent.com/15010826/166625341-d6ab416a-3d7d-43ec-ac9d-e8a3069809de.png)

So I am wondering how to coordinate between these two tools.

For example, as Hypercrx become more and more mature, how about all the documentation hosted in the GitHub ? @zhuxiangning @tyn1998

**Comment by will-ww** [comment]
One of the concern maybe the user design experience and Chinese language convionce while using Yuque, 

In that way, we can use links to link the documentation together.

**Comment by tyn1998** [comment]
In my view, Hypercrx is an open source project hosted on GitHub so we should make the best of features provided by GitHub. For normal users, they get information through README, GitHub Pages(#316 ), Issues and Discussions. For developers, they can get extra info from Wiki(#315 ).

Let's leave yuque alone as an inner communication media by which we can casually and quickly document anything using our mother tongue. If we want to let the community know something, we will extract and arrange info from yuque and then translate them into English to put on GitHub.

**Comment by will-ww** [comment]
Thanks for your explain. I think this strategy is reasonable and useful. From inner source to open source, the best practice carried out is very promissing~
