### ISSUE TITLE
[Summer2022/OSPP-Project02]  Implementation and Injection of Two React Components

### ISSUE THREAD

**Issue by zhuxiangning** [hypertrons/hypertrons-crx#348]
Hey, guys！Welcome to Hypercrx! 👏👏👏
Just throw any thought you have here! 👇

**Project Mentor:** @zhuxiangning 

**Project Description:**
There are two main functions that Hypercrx offers. One is as a front-end of Hypertrons and the other is to visualize data generated from analyzed GitHub logs provided by X-lab. This project has something to do with both functions.

_**Task 1.**_ When running on GitHub repo pages, Hypercrx will try to fetch the file .github/hypertrons.json of that repo and then put part of the info of the file as one of the configuration sources. Now we want a feature: if maintainers of one repo put a pair of key-value named "repo_banner_text" into hypertrons.json, then users of Hypercrx can see a horizontal banner with text smoothly and infinitely scrolling on that repo page.

**_Task 2._** Based on Anichart.js, we ever implemented DynamicBar(see https://github.com/hypertrons/hypertrons-crx/pull/221) to present changes in contributors' activity value of a given repo. However, in practice, we found that Anichart.js just had too many shortcomings and failed to earn our confidence. At the same time, the data source of contributors' activity value also had some problems so we finally removed the DynamicBar from our charts list, badly. Recently, through examination of Echarts, we think it is equipped with the power to implement the DynamicBar that we want! So, we hope you can help us bring the DynamicBar back, will you?

_**Task 3.**_ This task has a connection with Project 2. In short, we ask you, after the AVC strategy is worked out by the chosen guy for Project 2, to inject the two components into the pages of GitHub, using the AVC way. Before that guy's success, you may try the old way to inject components as we did to check and adjust your developing components.

Details of the 3 tasks will be put on corresponding issues later. There is another thing, which is, that we courage you to document any of your progress every two weeks in specified issues, once the development phase of Summer 2022 starts.
At last, if you are interested, just go straight to the Discussions Tab of our repo and keep in touch with us!

**Difficulty:** Advanced

**Labels of Technical Fields:** React, Chrome Extension

**Labels of Programming Language:** HTML,CSS,JavaScript,TypeScript

**Project Output Requirements:**

- Design and implement the ScrollingBannerText React component
- Design and implement the DynamicBar React component
- Inject the two components into GitHub in the AVC way

**Project Technical Requirements:**

- Know how the Chrome extension works
- Know how Hypercrx works
- Familiar with HTML, CSS, JavaScript and TypeScript
- Familiar with Echarts
- Familiar with Git and GitHub

**Comment by TieWay59** [comment]
Hi hypertrons-crx folks, I'm very interested in this task, and I'll start to fork on it.

In task 1, can you tell more details about where this banner will display? maybe a screenshot can help a lot.

**Comment by sainthyz** [comment]
i have a try in my local environment. the task1 , maybe i can add a new Perceptor.In the Perceptor,I can get the  data of hypertrons.json through getConfigFromGithub. And create a component to present the value.the detail we can have a deep discussion.task 2 :there is a demo in echarts Official website and ihava used this style chart in my other projects.

**Comment by TieWay59** [comment]
Hi @zhuxiangning & @tyn1998,

> Recently, through examination of Echarts, we think it is equipped with the power to implement the DynamicBar that we want!

In task 2, are you referring to [this echarts example](https://echarts.apache.org/examples/zh/editor.html?c=bar-race) I have used it in my side project and I'll investigate how to integrate it into hypertrons-crx. But first, could you please explain why Anichart.js fails in the previous version, and could you provide any links or hints? (I looked through https://github.com/hypertrons/hypertrons-crx/pull/221 but couldn't find the reason.)

Please correct me if I make any errors, and I greatly value your time; please respond whenever you are comfortable.

**Comment by tyn1998** [comment]
I can give you a more detailed example: https://echarts.apache.org/examples/zh/editor.html?c=bar-race-country
and an option may help: https://echarts.apache.org/zh/option.html#series-bar.markPoint

Why we drop Anichart.js? See #307.

**Comment by TieWay59** [comment]
Thank you @tyn1998 ❤,  I'm going to look into that.

**Comment by tyn1998** [comment]
> where this banner will display?

This place looks great to me.
![image](https://user-images.githubusercontent.com/32434520/167785969-ff1e5c9a-abb3-433c-afb8-f5ec8510655e.png)

**Comment by smitsekhadiaa** [comment]
hey @tyn1998  I have had a detailed look at the codebase , forked and setup  hypertrons-crx ; I think now I understand how hypertrons-crx work.
I have also looked at the issue #328 and I have made good progress.
I have done research on this project #348 and I am very much intrested in it.

for Task1:
we can first create banner and then use react-infinite-scroll-hook:  
[https://reactjsexample.com/a-simple-hook-to-create-infinite-scroll-list-components-with-react/](url)

for Task 2:

I looked the resource you provided for the dynamic bar implementation.
or else  can we use the inbuilt react library to create the dynamic chart we want?-
 react-dynamic-charts :
 [https://www.npmjs.com/package/react-dynamic-charts](url)
this library also has many good inbuilt props.
I have used this library in my personal project too and it works perfectly fine.

ill continue the research on this project and keep you updated.

Please let me know your thoughts.
Thankyou, Regards

**Comment by tyn1998** [comment]
Hi @smitsekhadiaa , you did a great research!

For task1, I think react-infinite-scroll-hook does not seem like exactly what we want. What we want is a horizontal scrolling banner like the [home page](https://summer-ospp.ac.cn/) of Summer 2022:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/32434520/168114093-b7e643bc-b13a-4c2d-af17-56810068e8ff.png">

For task2, react-dynamic-charts looks great but echarts is the only option for us since it is maintained by a great community with a lot of people and we do not want to involve extra modules to increase the size of our extension.

Thank you!

**Comment by smitsekhadiaa** [comment]
Oh got it @tyn1998 👍,
for task1: I have coded the infinite horizontal scrolling text and was successful in developing it without using any external react library so that we don't involve any more extra modules. Now we just need to integrate it with hypertrons-crx at the place that you suggested.

https://user-images.githubusercontent.com/90528630/168321417-23be2532-5d88-405a-9116-e79ef24e7eea.mp4

I hope this is what was required.


for task2, yes got it. I'll look into echarts and understand the workflow.👍


Please let me know your thoughts when ever you are free.

Thankyou, Regards

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 while I was understanding at the codebase, I came across the bar statistics and found out the color used for the text is not clearly visible for the dark Github theme(which is used by many users).



![image](https://user-images.githubusercontent.com/90528630/169646459-9db1d51d-c8b9-4385-88ff-d1c5283306af.png)



 may be I could create a pull request to change that color to a compact color which will be visible in all the themes.

For task 2:  
I have looked into the racing bars on echarts for task 2 and I think I will be able to successfully implement it.
I have started to work on it.

Please let me know your thoughts whenever you get time.

Thankyou, Regards

**Comment by tyn1998** [comment]
Great job, @sainthyz !

> all the themes

Well, all themes include these:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/32434520/169647744-15c62d10-104d-40e9-b6cf-8a6e725b3d0c.png">

But currently Hypercrx only support "Light Default" and "Dark Default". May I know which theme you are using? If you can figure out a way to address this limit, just go!

Here is what the chart looks like in "Dark Default":

<img width="344" alt="image" src="https://user-images.githubusercontent.com/32434520/169648070-d58f72d7-8dee-4501-a986-552d375b309f.png">


> I have looked into the racing bars on echarts for task 2 and I think I will be able to successfully implement it.
> I have started to work on it.

That is so great! But I suppose you'd better not start the job at this moment because the committee of OSPP gives suggestion that tasks should not be actually started until the chosen guys are decided. But you are welcomed to illustrate your plan on this task!

Thanks!

**Comment by smitsekhadiaa** [comment]
Thankyou for your reply @tyn1998 
> But currently Hypercrx only supports "Light Default" and "Dark Default". May I know which theme you are using? If you can figure out a way to address this limit, just go!
>
Got it, Currently I am using day theme with dark default mode and that's why in my system it was difficult to read,

we can use a color in day theme which will be visible for all the different modes, and same for the night theme?



> That is so great! But I suppose you'd better not start the job at this moment because the committee of OSPP gives suggestion that tasks should not be actually started until the chosen guys are decided. But you are welcomed to illustrate your plan on this task!
> 

yes sure at the moment I will just try to figure out the best possible solution and I will illustrate my plan for all the task on my proposal submission for OSPP.

> Great job, @sainthyz !
> 
sorry, its @smitsekhadiaa 😅


Thankyou, Regards.

**Comment by tyn1998** [comment]
> sorry, its @smitsekhadiaa 😅

Sorry for the silly mistake!



> we can use a color in day theme which will be visible for all the different modes, and same for the night theme?

That is what we desire, but first we should find a way to get modes related info from DOMs. Currently, Hypercrx handles things in the following way:

https://github.com/hypertrons/hypertrons-crx/blob/c35a385763e9ffcfbd30a398e27da66c81b675be/src/utils/utils.ts#L127-L129

https://github.com/hypertrons/hypertrons-crx/blob/c35a385763e9ffcfbd30a398e27da66c81b675be/src/pages/ContentScripts/RepoActiInflTrend.tsx#L17-L26

I think "auto" getting in the way if users let theme mode sync with system.

**Comment by smitsekhadiaa** [comment]
Thankyou @tyn1998  for making my concepts clear, got it 👍
I will look into this for sure if we could get information on all the themes from DOMs


Thankyou, Regards.

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 
I have looked into echarts and was wondering if you could correct me if I am wrong
To make use of the dynamic racing bar using echarts,
1) we first define a `interface` for the chart we want,
2) we fetch the data for the chart we want.
3) we use the` options ={}`  where we define the attributes we want in out bar chart (type of chart we want, x-axis details, y-axis details , assigning and displaying the fetched data, etc)
 
These are the major steps to use a chart from echarts into hypertrons-crs right?

**Comment by tyn1998** [comment]
Hi @smitsekhadiaa, you can checkout [this commit](https://github.com/tyn1998/hypertrons-crx/tree/5a523e8f349e1cdc8bb1704c09c2ce6e7d3182b2) and look into the worktree.

You can write DynamicBar (or called RacingBar) component like [this](https://github.com/tyn1998/hypertrons-crx/tree/5a523e8f349e1cdc8bb1704c09c2ce6e7d3182b2/src/components/DynamicBar).

And use the component like [this](https://github.com/tyn1998/hypertrons-crx/blob/5a523e8f349e1cdc8bb1704c09c2ce6e7d3182b2/src/pages/Content/ContributorsActivityEvolution.tsx).

Then inject it into pages like [this](https://github.com/tyn1998/hypertrons-crx/blob/5a523e8f349e1cdc8bb1704c09c2ce6e7d3182b2/src/pages/Content/index.ts#L5).

**Comment by smitsekhadiaa** [comment]
Hello @tyn1998 
Thankyou for the resources i have started to look at them 👍

Thankyou, Regards

**Comment by smitsekhadiaa** [comment]
> Then inject it into pages like [this](https://github.com/tyn1998/hypertrons-crx/blob/5a523e8f349e1cdc8bb1704c09c2ce6e7d3182b2/src/pages/Content/index.ts#L5).

so initially i would have to inject the components by the old way like this 

and once the guy in project 1 has completed refoctoring the code in the AVC format then inject them in the AVC way 
>

**Comment by tyn1998** [comment]
Yes.

**Comment by smitsekhadiaa** [comment]
Hey @tyn1998 
Here is my proposal for [[Summer2022/OSPP-Project02] Implementation and Injection of Two React Components](https://github.com/hypertrons/hypertrons-crx/issues/348)

Proposal:- [Proposal Link](https://docs.google.com/document/d/1eCHaB-j1DMVG__mfoh4jWLHy0REM3ON7_BUO1rbmTGo/edit?usp=sharing)

My Resume:- [Resume Link](https://drive.google.com/file/d/1FfGAU27Ved0NyI3DDzhq-LSSGWtC8KdE/view?usp=sharing)

Can you Please review it when ever you get time and let me know your thoughts?

Thankyou, Regards

**Comment by tyn1998** [comment]
Wow, so beautiful! I will read them~

**Comment by smitsekhadiaa** [comment]
Yes, Thankyou👍

Yes here is the link for the template : [Abey Template](https://www.overleaf.com/latex/templates/abey-resume-template/jxstkffrxxmh)😊

**Comment by tyn1998** [comment]
Hey @smitsekhadiaa, HorizontalBanner will only be presented in repo page rather both in profile and repo page.

The rest of your proposal looks great to me, Congratulations!

Does Google Docs support comment? If so, please enable commenting so I can give you advice directly there.

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 
yes got it I will change the proposal according to your suggestions 👍

The updated link For commenter is : [Proposal Link](https://docs.google.com/document/d/1eCHaB-j1DMVG__mfoh4jWLHy0REM3ON7_BUO1rbmTGo/edit?usp=sharing)

Thankyou👍

**Comment by tyn1998** [comment]
Hi, @smitsekhadiaa. I think your proposal is ready for submitting. You can submit both your proposal and CV to the OSPP Student Portal now. 👍

**Comment by smitsekhadiaa** [comment]
Hey @tyn1998 
Thankyou so much for taking time and giving suggestions on the proposal.🙏
yes I will submit both of them now on the portal.👍

**Comment by tyn1998** [comment]
Hi, @smitsekhadiaa, congratulations🥇 ! Happy hacking this summer~

<img width="830" alt="image" src="https://user-images.githubusercontent.com/32434520/172031992-38e14f5a-4f45-4189-a14e-227e264d0a63.png">

**Comment by smitsekhadiaa** [comment]
Glad to hear that @tyn1998 and glad to be part of the community!
Thankyou so much,
I'll start working on the project soon👍

**Comment by tyn1998** [comment]
Hi, @smitsekhadiaa, the new AVC strategy has come out #397. Basicly, those big files with many lines are split into several small files and the code tree was also restructured accordingly.

If you have not started, it is great to kick off the two features based on the new AVC strategy.

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 , yes i'll study the new strategy and continue my work.
incase of any complexity ill reach out to you👍.
Thanks.

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 , i'll raise a draft PR today itself. 
Thankyou.

**Comment by tyn1998** [comment]
Add a `data-id` attribute can avoid element to be flushed after tab switching and it also keeps the scrolling animation from being interrupted.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/32434520/196352336-1cc08b7f-a274-4cdd-885e-ecff6cce4d88.png">

**Comment by smitsekhadiaa** [comment]
yes, i've have inserted the banner at the required position 👍

**Comment by tyn1998** [comment]
Hello @smitsekhadiaa, are you still interested in implementing the `activity-racing-bars` feature?

If the anwser is yes, a new issue will be created and you are welcomed to implement the feature after v1.9.0 is merged into master (in two weeks).

I also wrote a demo(https://github.com/X-lab2017/open-digger/pull/1292) you may refer to :)

**Comment by andyhuang18** [comment]
Hi @tyn1998 It seems that this task has not been claimed yet. I can try to finish, please give me some time! Thanks! I also paid attention to the new changes in Opendigger before. 💪 💪 💪

**Comment by tyn1998** [comment]
@andyhuang18 wow that's great. I'm looking forward to your PR!

I'll create a new issue and you can `/self-assign` there 🚀
