### ISSUE TITLE
[Feature] exclude outlier from developer collaboration network

### ISSUE THREAD

**Issue by johnnychen94** [hypertrons/hypertrons-crx#350]
## Type of Issue

_What types of issue have you found with hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bug
- [x] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

## Introduction to the issue

Example user link: https://github.com/timholy

The bot users are obvious outliers and I believe it gives better result by excluding them when building the graph

![image](https://user-images.githubusercontent.com/8684355/168027629-d7d9c563-0abe-4446-85b5-b175204fbcf7.png)

**Comment by tyn1998** [comment]
Dr. Bi @bifenglin has been conducting  a research on GitHub bot detecting (detecting bots that are not marked as `bot` but behave like a bot).

After he finishes his research and OpenDigger implements the method proposed in his paper, we can continue to work on this feature :)

**Comment by wangyantong2000** [comment]
At present, the graph data in HyperCRX is no longer provided by OpenDigger and has been replaced entirely with OSGraph. This issue can be considered for closure.
