### ISSUE TITLE
[refactor] remove antv related packages

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#355]
Since we have already only focused on Echarts, we'd better remove antv packages and related code from Hypercrx, which can also decrease the size of build folder.

**Comment by wxharry** [comment]
@tyn1998 Hi, Lam! do you have time for this? otherwise, looks like we need to move it to the next milestone.

**Comment by wxharry** [comment]
@tyn1998 Hey, Lam. I would like to work on this issue. Any advice?

**Comment by tyn1998** [comment]
Hi, @wxharry, I'm afraid that I cannot provide much information on this issue since I'm not so familiar with the related code. But one thing should not be forgotten, which is to remove all configuration code related to Antv:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/32434520/192762195-08d8df81-291b-4978-b412-9ac8ce20c2af.png">

You can start handling this as you wish, I'll be always here to help!

**Comment by wxharry** [comment]
I guess I can start with removing the antv dependencies and remove all that miss dependencies hahaha

**Comment by tyn1998** [comment]
closed via #462

**Comment by tyn1998** [comment]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/32434520/193493093-f1461936-6187-4f05-a6d2-a626d12e000f.png">

The size of the packed extension without antv packages has been reduced by 2/3 👍
