### ISSUE TITLE
[release] upload Hypercrx v1.5.5 to stores

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#357]
## Changelog

- #309 
- #320 (more accurate! Thanks, @wxharry )
- #332 
- #336 
- #356 (new feature! Thanks, @smitsekhadiaa)
- #360 
- #362

**Comment by tyn1998** [comment]
Pending in Edge Store:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/32434520/171645031-4f556eac-270e-40e7-990e-9e1530646925.png">

**Comment by tyn1998** [comment]
Published in Chrome Web Store (never so fast like this time):

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/32434520/171655539-21c7508e-e459-4c12-a1e2-341c72a35e5f.png">

**Comment by will-ww** [comment]
Great~

**Comment by tyn1998** [comment]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/32434520/172301155-690eb3a6-d45e-4918-8987-82fa1aedcc45.png">

Published in Edge store.

Done!
