### ISSUE TITLE
[doc] two gifs do not loop

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#359]
Gifs should repeat themselves again and again, but these two do not. And actually the two gifs' urls are same, which is not right, we need gifs showing trends chart from a repo and a profile respectively.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/32434520/171565132-c4fffed1-842c-48eb-b5a7-193b9c131c8d.png">

Would you like to help? @smitsekhadiaa :smile:

**Comment by tyn1998** [comment]
If you are willing to help, just comment "/self-assign"~

**Comment by smitsekhadiaa** [comment]
yes surely, @tyn1998 
I'll be happy to help.😊
/self-assign

**Comment by smitsekhadiaa** [comment]
Hey @tyn1998 
ill solve this issue by tonight if possible 
and issue a PR is it fine?

**Comment by tyn1998** [comment]
yeah, that's good～

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Smit Sekhadia ***@***.***>
发送时间: Friday, June 3, 2022 4:59:37 PM
收件人: hypertrons/hypertrons-crx ***@***.***>
抄送: Lam Tang ***@***.***>; Mention ***@***.***>
主题: Re: [hypertrons/hypertrons-crx] [doc] two gifs do not loop (Issue #359)


Hey @tyn1998<https://github.com/tyn1998>
ill solve this issue by tonight if possible
and issue a PR is it fine?

―

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 
this is the trend chart for the repo
![image](https://user-images.githubusercontent.com/90528630/171825830-50320899-1178-49bd-9942-b4da39e0d57d.png)



and this is the trend chart for the user:
![image](https://user-images.githubusercontent.com/90528630/171826025-23a9480f-b912-4f23-97ac-33ea1183c16b.png)


when ill record the gif then how will one come to know which one is for the repo and which one is for user as I just need to create a gif of just trend chart right so both of them would look same?

**Comment by tyn1998** [comment]
Well, it is fine that the two gifs look similar. Since "similar" is not "totally same" as they are now :smile:

**Comment by smitsekhadiaa** [comment]
oh okay @tyn1998 
and I wanted to ask one more thing
should in update my proposal with the pull request I have merged and issues I have solved and update it to OSPP portal as tommorrow is the last day for submission?

Thankyou

**Comment by tyn1998** [comment]
Hey @smitsekhadiaa, if you the OSPP system supports updating proposals just do it as you wish~

**Comment by smitsekhadiaa** [comment]
Yes thankyou @tyn1998 
I have created pull request #366 for this issue please check it if its proper whenever you get time

Thankyou
