### ISSUE TITLE
[CI/CD] automatically trigger `yarn run prettier` by using git hooks 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#364]
### Description

Maybe [husky](https://github.com/typicode/husky) can help.

If this issue is resolved, we should also modify PR template to remove "I have run `yarn run prettier` " from checklist.

**Comment by frank-zsy** [comment]
Can refer to https://github.com/hypertrons/hypertrons/blob/master/.huskyrc Hypertrons pre commit config

**Comment by tyn1998** [comment]
Thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Frank Zhao ***@***.***>
发送时间: Thursday, June 23, 2022 6:00:22 PM
收件人: hypertrons/hypertrons-crx ***@***.***>
抄送: Lam Tang ***@***.***>; Author ***@***.***>
主题: Re: [hypertrons/hypertrons-crx] [CI/CD] automatically trigger `yarn run prettier` by using git hooks (Issue #364)


Can refer to https://github.com/hypertrons/hypertrons/blob/master/.huskyrc Hypertrons pre commit config

―

**Comment by tyn1998** [comment]
closed via #386.
