### ISSUE TITLE
[Doc] Introduce how to and who can use commands supported by Hypertrons in wiki

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#369]
### Description

like:
- /self-assign
- /approve
- ...

**Comment by wxharry** [comment]
Is this still necessary after we merged v1.9.0? @tyn1998

**Comment by tyn1998** [comment]
I think the docs is still needed. We are still using `/approve`, don't we :D

**Comment by wxharry** [comment]
> I thought that feature is supported by the hypertrons bot, not our CRX project.

Oh, I know what you mean. We need add the [link](https://github.com/hypertrons/hypertrons-crx/blob/master/.github/hypertrons.json) and explain it, right.

**Comment by wxharry** [comment]
Is this still needed? lol

**Comment by tyn1998** [comment]
@tyn1998 I think the anwser is no :D
