### ISSUE TITLE
[doc] Add the invite link to Hypertrons Slack workspace to README 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#372]
### Description

This is the permanent invite link: https://join.slack.com/t/hypertrons/shared_invite/zt-1a7tfc1tx-5YP8m59Yg~vSqiMBMeUJnQ

**Comment by smitsekhadiaa** [comment]
hey @tyn1998 
should I add it to the readme?

**Comment by tyn1998** [comment]
Hey @smitsekhadiaa, in fact I have no idea about where to put the invite link for now. This invite link is for Hypertrons organization while we are in Hypercrx community. I think we may leave the issue open for a while.

Thank you!

**Comment by tyn1998** [comment]
Maybe we can put the link here:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/32434520/175542144-f018c2dd-9d00-4516-a149-414ea3739125.png">

Hey, @xgdyp, would you like to help?

**Comment by xgdyp** [comment]
> Maybe we can put the link here:
> 
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/32434520/175542144-f018c2dd-9d00-4516-a149-414ea3739125.png">
> 
> Hey, @xgdyp, would you like to help?

Sure, I assigned this issue to me and add a badge of slack. Please review it.

**Comment by tyn1998** [comment]
closed via #385. Thanks!
