### ISSUE TITLE
[chore] feedback link points to normal new issue rather issue chooser

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#374]
### Description

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/32434520/173007468-66a00c17-92e8-47ce-bd9e-18de12d330b6.png">

Just appending '/choose' to the url would resolve this.

**Comment by zhicheng-ning** [comment]
Hi, @tyn1998 , I can help!

/self-assign
