### ISSUE TITLE
[Bug] Missing data in my Acti & Infl trend chart (I once changed my login name)

### ISSUE THREAD

**Issue by xgdyp** [hypertrons/hypertrons-crx#375]
### Current Behavior

I found data in hypercrx is associated with the username instead of user_id
for example, I changed my username last year and the data displayed is only after I changed the name
![image](https://user-images.githubusercontent.com/37795442/173218773-69140c7a-ccee-4bb3-a930-2546bf872d48.png)

### Environment

```markdown
- OS: 
- Browser:
```

**Comment by tyn1998** [comment]
Hi, @xgdyp, thanks for your feedback! 
We will consider this. Hey, @frank-zsy, currently the files on oss are all named after their login_name or repo_name, right?

**Comment by frank-zsy** [comment]
Yes, but in the database, I also use id to identify an entity. So the username change will not affect at all. I think you only have activity after 2021.7.

**Comment by xgdyp** [comment]
Thanks! I understand
