### ISSUE TITLE
[Question]  Some confusion about activity calculation

### ISSUE THREAD

**Issue by zhicheng-ning** [hypertrons/hypertrons-crx#376]
### Description

I have a doubt, as shown in the picture below, my activity is 79.16 in January 2022 and 61.5 in March 2022, but the activity is 1.0 in February, so I want to know what is the basis for calculating the activity. This is my homepage：https://github.com/zhicheng-ning
![image](https://user-images.githubusercontent.com/39022409/173221878-7d3fbf10-156f-4cc0-8afe-f8c0c863d770.png)

**Comment by tyn1998** [comment]
Hello @zhicheng-ning, we caculate the activity metrics based on your issues, PRs and others but not on commits directly pushed into repos.

Yes, your activity dropped so dramatically in February so I think it might need to be further confirmed. @frank-zsy

**Comment by frank-zsy** [comment]
The data is correct on my side.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/8512426/173231601-ec8bef95-4a4c-44bf-abde-f7684120d87c.png">

<img width="935" alt="image" src="https://user-images.githubusercontent.com/8512426/173231646-bd2e1cdb-4aa3-428d-9a4f-6d75dd5d639f.png">

Maybe you participant in some discussion which is not included in GitHub event log right now. @zhicheng-ning

**Comment by frank-zsy** [comment]
@zhicheng-ning From the data, you participant in ByteLegend a lot in Jan. and Mar. , can you confirm on yourself that you also active a lot in Feb. ? Issues or PRs with URL are enough.

**Comment by frank-zsy** [comment]
And here is the data status of the data import service, from the missing files, we can see all data has been imported for 2022.2, not a single hour is missing.

http://106.15.39.211:9238/status

**Comment by zhicheng-ning** [comment]
> @zhicheng-ning From the data, you participant in ByteLegend a lot in Jan. and Mar. , can you confirm on yourself that you also active a lot in Feb. ? Issues or PRs with URL are enough.

Yes, I just checked the activity records in Feb. The main reason is that there are activities in my repository. My activities on bytelegend are not frequent. Thank you!

**Comment by frank-zsy** [comment]
> Yes, I just checked the activity records in Feb. The main reason is that there are activities in my repository. My activities on bytelegend are not frequent. Thank you!

No problem, the thing is if you only commit to repos, the events are not counted as activity index since it is not a collaborate action.
