### ISSUE TITLE
[Discussion] Is there any secure way to request data for Chrome extension?

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#380]
### Description

Right now, the extension will request a public data resource to display the diagrams.

Is there any secure way to request private data? Like if we want to add personal recommendations in the future, we may not want the data to be in the public domain.

**Comment by tyn1998** [comment]
Hi, @frank-zsy, does it mean that we need a backend server?

**Comment by frank-zsy** [comment]
No matter what the mechanism is, assume that we have a backend server, how can we control the data if we don't have an account system and need login in frontend?

**Comment by tyn1998** [comment]
Maybe we can use jQuery to get loginId:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/32434520/175228088-d015d571-d178-4e73-b3b4-66bf6ac467be.png">

An existing example:

https://github.com/hypertrons/hypertrons-crx/blob/43e1ed45aaf051a65a7708e3a60bbaf0926c012f/src/pages/ContentScripts/DeveloperNetwork.tsx#L374-L384

**Comment by tyn1998** [comment]
> Is there any secure way to request private data?

Oh I didn't consider this requirement.

**Comment by wxharry** [comment]
How about authorizing with Github like this?
![image](https://user-images.githubusercontent.com/39271899/175439711-b6708bc7-e6c7-4a86-94b6-7aceb14878da.png)

It is easier for user to login, though we need to design an account system

**Comment by frank-zsy** [comment]
As there are more implementations of CHAOSS metrics in OpenDigger, I am considering add more data to Hypercrx. If we have no way to handle private data, I will design to use public data first.
