### ISSUE TITLE
[Bug] [Fatal] Hypercrx content cannot show up after switching between Tabs!

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#382]
### Version

1.5.5

### Current Behavior

In profile page:

<img width="1861" alt="image" src="https://user-images.githubusercontent.com/32434520/175486474-002da1e5-157a-4018-864c-a99cd8683589.png">

In repo page:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/32434520/175486661-27aa201b-7ec9-4d3c-b8c9-4faa8f7307b4.png">

### Expected Behavior

Switching between tabs won't break Hypercrx's function.

### Environment

```markdown
- OS: macOS Monterey ARM
- Browser:Chrome 101,103; Edge 102,103
```

### Any additional comments?

Thanks for tests provided by @zhicheng-ning @zhuxiangning @xgdyp @yangli-os.

According to tests, as for repo pages, I find things go wrong only in M1 Macs. As for profile pages, switching between tabs always makes Hypercrs UI disappear no matter what the platform it is in.

**Comment by tyn1998** [comment]
We need more tests, please leave your feedback in comments if you can reproduce this fatal problem. Thanks a lot!

@frank-zsy @LiuChangFreeman @heming6666 @wxharry @smitsekhadiaa @will-ww @xiaoya-yaya

**Comment by tyn1998** [comment]
For now, I think there is a great chance that the problem is introduced by a GitHub update.

**Comment by tyn1998** [comment]
Amazing, it seems that GitHub fix their problem so everything goes back to the way it is before.

So glad to close this issue not by a PR.

**Comment by tyn1998** [comment]
Again :(

**Comment by zhicheng-ning** [comment]
sad story

> Again :(

**Comment by tyn1998** [comment]
> Amazing, it seems that GitHub fix their problem so everything goes back to the way it is before.
> 
> So glad to close this issue not by a PR.

This time we are not so lucky. I'm going to handle the problem.

**Comment by tyn1998** [comment]
emmm...working on this bug whole day but not fix it yet. This fatal problem might linger for another few days...

**Comment by frank-zsy** [comment]
Is this something to do with the GitHub page layout. In order to adapt GitHub page layout change, can we extract the insert element point out from Hypercrx source code and instead, it can load from a static file like a JSON file on OSS service to figure out where to put the components. In this way, we can adapt GitHub update by updating the static file rather than publish a new version without new features. Is this feasible?

**Comment by tyn1998** [comment]
Hi, @frank-zsy. This time the trouble is not related to GitHub page layout, but the strategy by which GitHub handles page navigation inside GitHub website.

We put our `mainInject()` into chrome extension content script and it is only run one time when the page loads or reloads. Since GitHub pages will not go through a page reload after page navigation in the new strategy now, the `mainInject()` cannot run again after navigating between pages (e.g. swiching tabs, go to profile page from repo page), not as it did before, which leads to the fatal problem.

In #396, I find a way to make `mainInject()` run each time the url is changed and it works. But another problem occurs: all fluent UI classes disappear after another `mainInject()` runs, which leads to styles crash. I believe if we change to another UI library such as antd, the problem can be solved automatically but that is time consuming.

I desperately want to know why styles disappear and I am still looking for the reason.

> can we extract the insert element point out from Hypercrx source code and instead, it can load from a static file like a JSON file on OSS service to figure out where to put the components.

Not understanding this strategy well. But we have @wxharry working on the [AVC strategy](https://github.com/hypertrons/hypertrons-crx/issues/347) and that strategy is expected to make insert point more clear and robust!

**Comment by tyn1998** [comment]
Hope! See:

- https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md#working-with-content-security-policy-csp
- https://stackoverflow.com/questions/42922784/what-s-the-purpose-of-the-html-nonce-attribute-for-script-and-style-elements
- https://stackoverflow.com/questions/49125561/how-can-i-set-a-nonce-in-material-ui-for-the-content-security-policy

**Comment by tyn1998** [comment]
HOPE!!!

https://github.com/hotwired/turbo/blob/98cdc4037788f078a741c7fb50412db0101bcb97/src/core/drive/head_snapshot.ts#L58-L69

![image](https://user-images.githubusercontent.com/32434520/178302912-38951fa7-0a19-4b8f-b9aa-6d8e7d757d78.png)

**Comment by tyn1998** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/32434520/178400080-44b1c256-b7a1-4247-a527-9833e63a6c8a.png">

**Comment by tyn1998** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/32434520/178401140-fcaa3b13-1be6-450a-a397-3d5ccc15e1e6.png">

**Comment by tyn1998** [comment]
7 days later, Hypercrx v1.6.2 is still pending in Edge store...

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/32434520/179644567-550b1b70-d109-403d-aac6-57d1de7e54bb.png">

Let's wait.

**Comment by tyn1998** [comment]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/32434520/180339675-81d4355d-5d59-4560-846f-c3eb66c0834a.png">

Now can close this issue.

**Comment by tyn1998** [comment]
refined-github community also [talked about](https://github.com/refined-github/refined-github/pull/5720#issuecomment-1166277787) this issue.
