### ISSUE TITLE
[docs] add more PR types to PR template & uncomment related issues

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#393]
### Description

Add PR types:

- refactoring
- docs
- ci
- ...

**Comment by wxharry** [comment]
would be perfect if PR types match conventional commits. refer to:
* #370

**Comment by tyn1998** [comment]
Good idea 👍 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/32434520/180816951-68cc5824-449b-4960-b602-aa647a9ce69f.png">
