### ISSUE TITLE
[Feature] Baseline is more attractive

### ISSUE THREAD

**Issue by will-ww** [hypertrons/hypertrons-crx#404]
### Description

If we can add some baseline in the **Activity & Influence Trends** chat, the developer can recognize the position of this project in the whole GitHub. Also, how to set the baseline is a challange~ 

![image](https://user-images.githubusercontent.com/15010826/178866580-ecda77fd-ff7c-464c-93e8-adc246139d09.png)

**Comment by tyn1998** [comment]
Hi, Mr.Wang @will-ww, [markLine](https://echarts.apache.org/zh/option.html#series-line.markLine) can be applied to set baselines in our trend chart, as long as we have baseline data.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/32434520/179129625-b1ac6341-e709-408b-a87b-42247af4f7b6.png">

https://echarts.apache.org/examples/zh/editor.html?c=line-marker

**Comment by tyn1998** [comment]
This issue can be reopened when baselines are available :)
