### ISSUE TITLE
[Feature][Dashborad]Developer Collaboration Network and Project Correlation Network for both projects and developers

### ISSUE THREAD

**Issue by xiaoya-Esther** [hypertrons/hypertrons-crx#41]
Initially, we have 4 kinds of graphs that need to be developed:

For a project:
- Developer Collaboration Network within the **project** for the past week.
- Network that shows the 10 most correlated **projects** for the past week.

For a developer:
- Developer Collaboration Network for a developer for the past week.
- The 10 most participated projects and their connection network.

For each graph, the developer nodes can be clicked and redirected to a developer's GitHub profile which displays the developer's graphs, and project nodes can be clicked and redirected to a project's GitHub dashboard which displays the project's graphs.

**Comment by frank-zsy** [comment]
If we use network graph to implement the most related repos and developers, I think we could extend the time range and participant numbers, like top 1000 repos/developers for last half year so we can update the data once a week or even two weeks.

Possible echarts components:
- [Simple graph with force layout](https://echarts.apache.org/examples/zh/editor.html?c=graph-force&theme=dark).
- [Graph network based on WebGL which can support much more nodes and edges](https://echarts.apache.org/examples/zh/editor.html?c=graphgl-large-internet&gl=1&theme=dark).

**Comment by heming6666** [comment]
Hey you guys, I think it's time to discuss the data structure for these two graph ( `Developer Collaboration Network` & `Project Correlation Network`).

From the `front-end` view, `Echarts` likes the following data format: 

```
{
  nodes: [
    {
      name: 'Jack',      // node name, unique
      symbolSize: 20, // node size
      value: 50           // node value
    }, 
    {
      name: 'Tom',
      symbolSize: 20,
      value: 50
    }, 
    ...
  ],
links: [
    {
      source: 'Jack', 
      target: 'Tom',
      symbolSize: 10 // size of edge
    }, 
    ...
  ],
}
```

So it woule be nice if `back-end` can return the data like: 
```
{
  nodes: [
    {
      name: 'Jack',      // user or repo name, unique
      value: 50           // activeness
    }, 
    {
      name: 'Tom',
      symbolSize: 20,
      value: 50
    }, 
    ...
  ],
edges: [
    {
      source: 'Jack', 
      target: 'Tom',
      weight: 10      // collaborative relationship
    }, 
    ...
  ],
}
``` 

WDYT @wengzhenjie @LiuChangFreeman ?

**Comment by xiaoya-Esther** [comment]
Thanks @heming6666  for the data structure, quick question here, what does `symbolSize` mean? Can we specify the node size directly according to the value((activeness of projects or developers)) of nodes? 

Let me ping @wengzhenjie @frank-zsy  @LiuChangFreeman  here for discussion.

**Comment by heming6666** [comment]
> Thanks @heming6666 for the data structure, quick question here, what does `symbolSize` mean? Can we specify the node size directly according to the value((activeness of projects or developers)) of nodes?
> 
> Let me ping @wengzhenjie @frank-zsy @LiuChangFreeman here for discussion.

Thank you @xiaoya-Esther for the question. You're right. And `symbolSize` is the parameter defined by `Echarts` that represents the node size. In our case, `symbolSize` equals `value`.  So there's no `symbolSize` in the data structure returned from `back-end`: 
```
{
  nodes: [
    {
      name: 'Jack',      // user or repo name, unique
      value: 50           // activeness
    }, 
    {
      name: 'Tom',
      // no symbolSize here
      value: 50
    }, 
    ...
  ],
edges: [
    {
      source: 'Jack', 
      target: 'Tom',
      weight: 10      // collaborative relationship
    }, 
    ...
  ],
}
``` 

I have edited this [comment](https://github.com/hypertrons/hypertrons-crx/issues/41#issuecomment-797377174) for my mistake. Thanks @xiaoya-Esther for your question again ~

**Comment by LiuChangFreeman** [comment]
The necessary information is just what you mentioned above. Let the `back-end` team provide `swagger` API docs, the discussion may be much more easier. Just like what we have done before.  
https://app.swaggerhub.com/apis/tongji3/wuhan2020/1.0.0#free

**Comment by wengzhenjie** [comment]
Great! This data structure has basic properties. I think more attributes can be added to nodes such as the number of issue comments, the number of open issue, etc.

**Comment by heming6666** [comment]
> Great! This data structure has basic properties. I think more attributes can be added to nodes such as the number of issue comment, the number of open issue, etc.

Sure! I am totally agree with you.

**Comment by frank-zsy** [comment]
> The necessary information is just what you mentioned above. Let the `back-end` team provide `swagger` API docs, the discussion may be much more easier. Just like what we have done before.
> https://app.swaggerhub.com/apis/tongji3/wuhan2020/1.0.0#free

If we use static resource like CDN URL to get the data, we may not need `swagger` docs.

**Comment by xiaoya-Esther** [comment]
I saw how the networks are implemented now and they are super great. Here are some personal comments:

- Does it make sense to remove the table at the left of the components? Users may have less interest in the specific value, and the table makes the components a little bit too big. I suppose we could consider a simple and light approach to give the network some more clarification, i.e. time period displayed, nodes and links represent for, calculation methods(this could use a hyperlink which redirects to some other places like documentation, user guides, etc.)

**Comment by xiaoya-Esther** [comment]
Also, when playing with the nodes, I found a really strange `participated repo network` for a developer who is rather active in the Apache ecosystem. I suppose it is close to a complete graph for those repos are so connected with each other, do we have a better way to display the graph clearer?
![image](https://user-images.githubusercontent.com/56542972/115184641-d8931a80-a110-11eb-8bca-33d0f47eb2cb.png)

**Comment by LiuChangFreeman** [comment]
> I saw how the networks are implemented now and they are super great. Here are some personal comments:
> 
> * Does it make sense to remove the table at the left of the components? Users may have less interest in the specific value, and the table makes the components a little bit too big. I suppose we could consider a simple and light approach to give the network some more clarification, i.e. time period displayed, nodes and links represent for, calculation methods(this could use a hyperlink which redirects to some other places like documentation, user guides, etc.)

I think the UI and UX can be implemented more elegantly.  
For example, give a button and `TeachingBubble` or `CallOut` rather than show the content directly. It really tasks too much space to be displayed.   
![image](https://user-images.githubusercontent.com/20047907/115184874-4d665480-a111-11eb-9c07-26ae8d6fb27c.png)  
![image](https://user-images.githubusercontent.com/20047907/115185066-b0f08200-a111-11eb-8148-41ffa8bff64e.png)  
![image](https://user-images.githubusercontent.com/20047907/115185079-b948bd00-a111-11eb-9bfd-7ca64c71ac53.png)

**Comment by xiaoya-Esther** [comment]
> I think the UI and UX can be implemented more elegantly.
> For example, give a button and `TeachingBubble` or `CallOut` rather than show the content directly. It really tasks too much space to be displayed.

Agree, those two UI components look really great!

**Comment by heming6666** [comment]
> * Does it make sense to remove the table at the left of the components? Users may have less interest in the specific value, and the table makes the components a little bit too big. I suppose we could consider a simple and light approach to give the network some more clarification, i.e. time period displayed, nodes and links represent for, calculation methods(this could use a hyperlink which redirects to some other places like documentation, user guides, etc.)

@xiaoya-Esther I agree.

> I think the UI and UX can be implemented more elegantly. For example, give a button and TeachingBubble or CallOut rather than show the content directly. It really takes too much space to be displayed.

You're right. I am trying to: 
- use `tooltip` to support some useful interactive operations with the graph.
- use the giving `fluentUI` components to show the clarification of the graph.

**Comment by heming6666** [comment]
Done.
