### ISSUE TITLE
[chore] substitute all image urls with ones that hosted on githubusercontent.com in case of broken images

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#411]
### Description

I've been thinking it as an internet issue for so long but now I treat it as a broken image. Maybe we should recapture a screenshot and update it in README.

In README:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/32434520/180365793-0a1db7c7-93b8-42e6-a0dd-139c527030c9.png">

Open it in seperate tab:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/32434520/180366036-217dc4d5-af7a-44af-be38-c1f4aac04c04.png">

Hey @zhicheng-ning, could you please check this issue on your machine? If you can reproduce the problem, we should replace the broken image.

**Comment by zhicheng-ning** [comment]
In my machine, as show below. It's amazing.

![image](https://user-images.githubusercontent.com/39022409/180369126-20e9ed59-631a-4b08-832f-11d864d0ae53.png)

**Comment by tyn1998** [comment]
😭 😆 

Thank you, I will further check it.

**Comment by tyn1998** [comment]
![image](https://user-images.githubusercontent.com/32434520/180371327-001b5e80-36f4-4656-9123-53fa09494928.png)

Maybe the problem is caused by aliyun oss urls. I think we can recapture those images which hosted on aliyun oss.

**Comment by zhicheng-ning** [comment]
When I click [it](https://camo.githubusercontent.com/7eadc5c7e130fdccf516b19a654ca7a1f62ff15bc1d20e3d48939423022757b9/68747470733a2f2f687970657274726f6e732e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f696d616765732f726561646d652d706572636570746f722d656e7472616e63652d322e706e67) or download this picture, the image display is fine.

![image](https://user-images.githubusercontent.com/39022409/180375188-b487dcc4-6e21-4844-bb7b-759a32b2792c.png)

**Comment by tyn1998** [comment]
Yes, I also tried to download them directly. Since there is nothing else to blame, the aliyun oss urls are highly suepected, I suppose.

**Comment by tyn1998** [comment]
![image](https://user-images.githubusercontent.com/32434520/180377908-364aa8c5-9e0b-4d8e-86b0-f9189f9cd090.png)

If you click the image to open it in new tab, it seems that the url is redirected to camo.githubusercontent.com, which may causes the trouble.

**Comment by zhicheng-ning** [comment]
> If you click the image to open it in new tab, it seems that the url is redirected to camo.githubusercontent.com, which may causes the trouble.

In README, all pictures which don't located in *.githubusercontent.com domian are redirected to camo.githubusercontent.com. This behavior may be related to GitHub's official Settings.

![image](https://user-images.githubusercontent.com/39022409/180442788-c303f40e-c8b0-45eb-a3d2-e148fb96d709.png)

**Comment by tyn1998** [comment]
emm, INSTALLATION.md and INSTALLATION.zh-CN.md also have these broken images.

**Comment by xgdyp** [comment]
I'll pick it

**Comment by xgdyp** [comment]
I found typo in INSTALLATION and fix it.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/37795442/180710129-5059c6d3-36c7-43f4-b710-dc11d78668bf.png">
