### ISSUE TITLE
[docs] gives <table> a <thead> in several markdown files

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#413]
### Description

![image](https://user-images.githubusercontent.com/32434520/180450973-8dedb678-2120-487d-a327-1d6fcbe06950.png)

Files are:

- https://github.com/hypertrons/hypertrons-crx/blob/fea52e15c8090c0cd8ce917b77642cd6e0fbc085/README.md
- https://github.com/hypertrons/hypertrons-crx/blob/fea52e15c8090c0cd8ce917b77642cd6e0fbc085/README.zh-CN.md
- https://github.com/hypertrons/hypertrons-crx/blob/fea52e15c8090c0cd8ce917b77642cd6e0fbc085/INSTALLATION.md
- https://github.com/hypertrons/hypertrons-crx/blob/fea52e15c8090c0cd8ce917b77642cd6e0fbc085/INSTALLATION.zh-CN.md

**Comment by tyn1998** [comment]
Please refer to this code snippet to create a table with head:

https://github.com/hypertrons/hypertrons-crx/blob/fea52e15c8090c0cd8ce917b77642cd6e0fbc085/README.md?plain=1#L18-L42

**Comment by xgdyp** [comment]
I'll fix it together with #411

**Comment by debjit20504** [comment]
Ok, I'll try to fix

**Comment by tyn1998** [comment]
Hey @debjit20504, it is so nice of you that you are willing to help. But this issue was assigned to @xgdyp.

Maybe you can find other issues with "good first issue" label to contribute to Hypercrx if you like~
