### ISSUE TITLE
[UI] the width of chart container should not be fixed

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#414]
### Description

Too narrow:

![image](https://user-images.githubusercontent.com/32434520/180469760-6076ada2-3f36-4681-a5c5-65fa42d5fd4e.png)

Too wide:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/32434520/180471568-cf3cad0d-a6b4-4cb6-8af8-68867fb2cd77.png">

**Comment by wxharry** [comment]
Also, since we have replaced green dots with avatars, I think we should remove that.
![image](https://user-images.githubusercontent.com/39271899/180483344-8c6d2332-77b5-477a-8d63-507e2263d3b7.png)

**Comment by tyn1998** [comment]
Yes, thanks for reminding.

**Comment by wxharry** [comment]
Or we can use a green circle as an edge of each node to keep that feature, like this: 
![image](https://user-images.githubusercontent.com/39271899/180586180-0de7a06f-566c-41ed-b99c-c9f531b2a8fc.png)

**Comment by debjit20504** [comment]
@tyn1998  can you tell the name of the file where this chart's code is present

**Comment by tyn1998** [comment]
Hi, @debjit20504, here are two files that use [Graph](https://github.com/hypertrons/hypertrons-crx/blob/master/src/components/Graph/Graph.tsx) component. And as you can see, the width property is fixed to 480 and 780 respectively.

https://github.com/hypertrons/hypertrons-crx/blob/17934e1d07f1af8e063ed76abff066961f7ff87b/src/pages/ContentScripts/DeveloperNetwork.tsx#L139-L142

https://github.com/hypertrons/hypertrons-crx/blob/17934e1d07f1af8e063ed76abff066961f7ff87b/src/pages/ContentScripts/ProjectNetwork.tsx#L119-L122

**Comment by tyn1998** [comment]
> Or we can use a green circle as an edge of each node to keep that feature, like this: ![image](https://user-images.githubusercontent.com/39271899/180586180-0de7a06f-566c-41ed-b99c-c9f531b2a8fc.png)

Looks good to me. But we may leave it as it is now, since the perceptor layout will be refactored in coming months I suppose. We can talk the UI later.

**Comment by debjit20504** [comment]
@tyn1998 like after changing how can I preview that weather the size of the chart is fit or not I've tried using yarn run start in vs code, and tried typescript build in atom editor can you please help me with this.

**Comment by tyn1998** [comment]
Hi, @debjit20504, sorry that I didn't get your point, could you please describe your problem in detail?

**Comment by debjit20504** [comment]
> Hi, @debjit20504, sorry that I didn't get your point, could you please describe your problem in detail?
I'm saying that I have make changes in DeveloperNetwork.tsx and ProjectNetwork.tsx and after that how can I verify changes on that chart..?

**Comment by tyn1998** [comment]
oh I got you now, please see quickstart section in README. You can install the built extension to chrome.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Debjit Pramanik ***@***.***>
发送时间: Monday, July 25, 2022 12:26:32 AM
收件人: hypertrons/hypertrons-crx ***@***.***>
抄送: Lam Tang ***@***.***>; Mention ***@***.***>
主题: Re: [hypertrons/hypertrons-crx] [UI] the width of chart container should not be fixed (Issue #414)


Hi, @debjit20504<https://github.com/debjit20504>, sorry that I didn't get your point, could you please describe your problem in detail?
I'm saying that I have make changes in DeveloperNetwork.tsx and ProjectNetwork.tsx and after that how can I verify changes on that chart..?

―

**Comment by debjit20504** [comment]
**yesterday, I followed all those steps mentioned in the quickstart section and got this** 👇

![Screenshot (466)](https://user-images.githubusercontent.com/79047521/180658397-98e58f3b-3520-4d35-8532-92b4fb0653c3.png)

**but today, when I opened that, I got this** 👇

![Screenshot (465)](https://user-images.githubusercontent.com/79047521/180658504-6ba98bb1-9716-4bc0-a1e2-068aed94dfe2.png)

**Comment by wxharry** [comment]
> ![Screenshot (465)](https://user-images.githubusercontent.com/79047521/180658504-6ba98bb1-9716-4bc0-a1e2-068aed94dfe2.png)
It seems that there is an app using port 3000. Kill that process and try again.

**Comment by tyn1998** [comment]
Hi, @debjit20504!

1. Some errors raised in extension management page is ok **if every funtion of Hypercrx works**, since they are not fatal errors but sometimes more like warnings.  Actually, we are trying to reduce those errors that might scare users and develpers recently.

2. As @wxharry pointed out, you may have another app running in 3000 port. Another way to solve the problem is to simply use another port to run. Since you are using git bash, you can do like: `PORT=3001 yarn run start` to specify a port.

**Comment by debjit20504** [comment]
Ok, I've tried both ways but getting the same thing 👇
![image](https://user-images.githubusercontent.com/79047521/180794191-b38522ba-f321-457d-adb2-c1d4c5d43661.png)
is there anything wrong?

**Comment by tyn1998** [comment]
localhost:3001 is where devServer hosts, there is no need to open it in browser.

Could you please record a screenshot for repo page, like:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/32434520/180797299-3e9a88a7-6f82-492f-86ac-8ab66a75fa40.png">

And after you install the fresh built unpacked extension, you should also disable Hypercrx installed from chrome webstore.

**Comment by debjit20504** [comment]
> localhost:3001 is where devServer hosts, there is no need to open it in browser.
> 
> And after you install the fresh built unpacked extension, you should also disable Hypercrx installed from chrome webstore.
> 
> Could you please record a screenshot for repo page (like below)? And what did you mean "the same thing"?
> 
> <img alt="image" width="1263" src="https://user-images.githubusercontent.com/32434520/180797299-3e9a88a7-6f82-492f-86ac-8ab66a75fa40.png">

Ok, I'll record and update you and about that same thing I mean was I tried using kill port 3000 and other one using new port,

**Comment by debjit20504** [comment]
![image](https://user-images.githubusercontent.com/79047521/181180013-89351ed6-0f8e-4ea6-b077-2c34d6067889.png)

![image](https://user-images.githubusercontent.com/79047521/181180097-aa4d8312-41ba-4c57-a241-2e4745af1ebd.png)

Does, this do the job.

**Comment by debjit20504** [comment]
Now, should I make a PR ?

**Comment by tyn1998** [comment]
Of course, please.

**Comment by debjit20504** [comment]
Should make PR by comparing branch OR by comparing across Fork

**Comment by tyn1998** [comment]
Hi, @debjit20504, I'm not understanding you well, but you can refer to this:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/32434520/181235537-7aaafd09-4c2b-4593-8315-60afe8e53347.png">

**Comment by debjit20504** [comment]
https://user-images.githubusercontent.com/79047521/181235765-ad60f402-9cc4-4cd1-946b-f7041c0a0cdc.mp4

**Comment by tyn1998** [comment]
Haha, now I'm sure that you may be not so familiar with how to contribute on GitHub. That is ok, I was totally a noob last year but now I'm so familiar with these things.

Please refer to: https://github.com/hypertrons/hypertrons-crx/pull/417#issuecomment-1193075664 .

**Comment by tyn1998** [comment]
Hi, @debjit20504, of course you should fork the repo first, and push the "debjit_testing" branch to your folk repo. hypertrons/hypertrons-crx should be "upstream" remote, while debjit20504/hypertrons-crx is "origin" remote.

Please refer to: https://github.com/hypertrons/hypertrons-crx/pull/417#issuecomment-1193075664 .

**Comment by debjit20504** [comment]
Thanks for the help. I'll do that. I'm dying laughing at my mistake. That how stupid I was, you know. Before making that video, I deleted that debjit_testing branch and the worst part is I have committed all the changes in that branch. So all that is gone, and Now I can't even checkout that bcoz it's the main repo, not the fork one, so git log won't do any good😂😂

**Comment by debjit20504** [comment]
nvm give me 10, 20 min after making changes I'll do PR

**Comment by tyn1998** [comment]
Oh, that is a sad story...

**Comment by tyn1998** [comment]
closed via #438.
