### ISSUE TITLE
[docs] remove opera logo's link in README

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#416]
### Description

Opera can install chrome extension in specific way actually, but an opera logo with chrome webstore link is confusing:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/32434520/180592166-49d09ab6-0b6f-4493-8f02-7bf3e01c639b.png">

Better to remove the link from the logo (in two README files):

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/32434520/180592150-c21efd60-ac68-4b01-a82d-a1bfeeb98d55.png">

**Comment by debjit20504** [comment]
@tyn1998 I've removed chrome-webstore link from there but now if someone click on that icon now it open the opera icon in a new tab will it be ok?

**Comment by tyn1998** [comment]
It is ok. Just like a normal image in README that can be clicked.
