### ISSUE TITLE
[Community] we invite @wxharry to be one of the Hypercrx maintainers 🎉 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#420]
### Description

Hi, @wxharry!

We are so thankful for your continuous contributions to Hypercrx, would you like to join us to be one of the Hypercrx maintainers? You will be granted to write access to this repo as well as the approver role of hypertrons if you are willing to.

Best regards,

Hypercrx core team.

**Comment by wxharry** [comment]
Yes! Thank you so much @tyn1998 !!!
