### ISSUE TITLE
[docs] we need to specify the available node version that compatible with all modules

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#423]
### Description

![image](https://user-images.githubusercontent.com/39271899/180662089-5a4abb8c-1520-42a1-8427-87b8ddb86d8d.png)
I got this error after I updated the latest commit. The newly added package `@plasmohq/edge-addons-api` requires a node version >=16.14, but mine is 16.13.1.

This error can be easily fixed by updating node. However, this error could be a problem for some of our contributors. 

Do we need to specify the available node version we are compatible with?

**Comment by tyn1998** [comment]
Hi, @wxharry. Agree with you, we'd better add "engine" field to package.json to limit the node version and add "Requirement" to README like: 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/32434520/180674653-c33d5c32-8d84-4017-89b1-e52436d4bb17.png">

By the way, it is a convention that odd version is less stable than even version, so you are encouraged to update your node from 16.13.1 to 16.14 or other even number version.

**Comment by wxharry** [comment]
Thank you for your information. I'm using 16.16 now.

**Comment by tyn1998** [comment]
closed via #437.
