### ISSUE TITLE
[Feature] embeded view for star and fork (s,f)

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#432]
### Description

A possible design:  

<img width ="900" src="https://user-images.githubusercontent.com/32434520/181482571-bf4a8320-c78c-4ab3-b655-c5e2755ef226.png"/>

**Comment by frank-zsy** [comment]
Great idea!

**Comment by tyn1998** [comment]
Kick off today 💪

**Comment by tyn1998** [comment]
Oh a terrible mistake made by me is that I purely ignored the truth that that data in month is the event number but not the absolute increase number, which makes "increment stars/forks" impossilbe to get.

I think we should not bring users inaccurate information in such an important place. Trying to find another proper way...
