### ISSUE TITLE
[UI]  add green edges to avatars in Active Developer Collabration Network graph

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#442]
### Description

After we replace the original green circle with avatar, the bar at the bottom of the graph is useless.
![image](https://user-images.githubusercontent.com/39271899/185020437-ff2bc4af-a8de-46f6-bf6d-daad02eb4ff8.png)

Instead of removing it, I suggest keeping it, and modify the shape of avatars to a circle surrounded by different green colors according to the bar, like this:
![image](https://user-images.githubusercontent.com/39271899/180586180-0de7a06f-566c-41ed-b99c-c9f531b2a8fc.png)

**Comment by tyn1998** [comment]
Good idea!

**Comment by tyn1998** [comment]
Well, if we set [symbol](https://echarts.apache.org/zh/option.html#series-graph.data.symbol) as image, we cannot draw a border around the image by [itemStyle.borderXXX](https://echarts.apache.org/zh/option.html#series-graph.data.itemStyle.borderColor). So this cannot be accomplished at the moment.
