### ISSUE TITLE
[Feature] a data center to fetch, store and provide data for charts and components

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#448]
### Description

We need a data center for reasons:

1. Soon, there will be components that demand data from different json files at once.
2. Decrease network requests (though most of them hit the browser cache)
3. https://github.com/hypertrons/hypertrons-crx/issues/402

**Comment by tyn1998** [comment]
An illustration:

![Hypercrx数据中心示意图-1](https://user-images.githubusercontent.com/32434520/189595393-321c1c41-45a3-4196-b1c2-d10b6c15f329.jpg)

Hi @zhicheng-ning, do you have any idea to implement this feature? Such as a proper design pattern or whatever you've learned about.

**Comment by zhicheng-ning** [comment]
Hi @tyn1998 , I think this [link](https://juejin.cn/post/6947936223126093861) maybe helpful.

**Comment by tyn1998** [comment]
@zhicheng-ning, thank you for sorting the murdle in my head (face to face)!

After discussing with you guys, I realize that what I really need is not what I described above. I will change the issue title and modify the description part later.

**Comment by zhicheng-ning** [comment]
> Updated illustration:

It seems like DTO（Data Transfer Object）, it can add or decrease the data field in the response object for different request purposes.

**Comment by tyn1998** [comment]
The [cache](https://ahooks.gitee.io/zh-CN/hooks/use-request/cache) ability provided by ahooks's useRequest looks like what I was searching for.
