### ISSUE TITLE
[docs] Add troubleshooting to wiki 

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#457]
### Description

We would like to collect troubles and errors that users or developers encountered when using hypercrx. It would be great if we could have a troubleshooting section in our wiki to collect relevant issues and solutions.

**Comment by wxharry** [comment]
I added [smit's issue](https://github.com/hypertrons/hypertrons-crx/issues/458) to the troubleshooting in wiki, but seems like we need to discuss the format a little bit. Any advice @tyn1998 ?

**Comment by tyn1998** [comment]
@wxharry meaningful job, thanks!

For me, the size of the font is too big. Maybe consider this layout:

**Error: husky - Command not found when committing**(#458)

> solutionbalabala.

**trouble2xxxx**

> solutionxxx

**xxx**

> xxxx

No title level font, just make troubles bold and solutions referenced.

**Comment by tyn1998** [comment]
Now it looks like this:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/32434520/196323935-31df2017-218e-47e2-8c83-fab25a3cc6e4.png">
