### ISSUE TITLE
[Bug] Husky error: Command not found on git commit -m " "

### ISSUE THREAD

**Issue by smitsekhadiaa** [hypertrons/hypertrons-crx#458]
### Current Behavior

After adding the changes to the working tree, on `git commit -m " " ` the terminal on windows (powershell and command prompt) are showing error- husky : command not found in PATH

![image](https://user-images.githubusercontent.com/90528630/190848394-f2473008-d7e9-4f52-8201-760c4e3ff60b.png)

### Expected Behavior

After git add -A , git commit -m " " should work perfectly fine , committing the added changes on the respective branch.

### Environment

```markdown
- OS: Windows
- Browser: Google Chrome
```

**Comment by tyn1998** [comment]
![image](https://user-images.githubusercontent.com/32434520/190851192-dad38b78-f263-4ff2-a681-be539716cacf.png)

Hi @smitsekhadiaa, I have tested `git commit` operation on my windows machine which has a really clean environment and everything works well. I'm afraid that the issue is a specific one that only occurs on your machine.

The environment troubles are always disappointing and suck, be patient and good luck!

**Comment by tyn1998** [comment]
Hi, @zhicheng-ning, could you help to `git commit` a random change on your windows machine and upload a screenshot here? We are eager to know if the issue is a general problem on windows.

**Comment by zhicheng-ning** [comment]
> Hi, @zhicheng-ning, could you help to `git commit` a random change on your windows machine and upload a screenshot here? We are eager to know if the issue is a general problem on windows.

ok, this action is in on the latest branch.

![image](https://user-images.githubusercontent.com/39022409/190852339-22ee6e2f-6f62-4984-9ef6-a65b9126fe5a.png)

**Comment by wxharry** [comment]
The first line indicates that the error might because of `node`, please check this issue to see if it would help. @smitsekhadiaa https://github.com/nodejs/node/issues/29287

**Comment by smitsekhadiaa** [comment]
The error is solved.
the error was due to If you're running Git from an app and the command can be found in your terminal, this means that the PATH in your app is different from your terminal.
`git config --unset core.hooksPath`
The above command unsets the hookspathif its different 
To revert the git-flow hooks directory back to its default you need to reset the config to point to the default Git hooks directory.
`
git config gitflow.path.hooks .git/hooks`

**Comment by smitsekhadiaa** [comment]
Thankyou @tyn1998 @zhicheng-ning  @wxharry  for your time.
