### ISSUE TITLE
[Bug] `Public template` is not regarded as public repo

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#468]
### Version

1.6.4

### Current Behavior

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/32434520/193962652-a4c3fa1a-884c-42bd-b39a-7e9da96b91ac.png">

### Expected Behavior

Features should run on this kind of repo.

### Environment

```markdown
- OS: macOS Monterey M1
- Browser: 105
```

### Any additional comments?

N.A.

**Comment by tyn1998** [comment]
The solution is:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/32434520/193963774-00f0992e-80c3-49e1-a6cc-0df873005e59.png">

Hi @andyhuang18, would you like to help? :)

**Comment by andyhuang18** [comment]
Sure~ I will try to solve it today！^_^
