### ISSUE TITLE
[Feature] an extensible option management system

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#474]
### Description

Since we have implemented a lot of features, we have a bunch of components. I think we should have a management option in the settings pages so that the users can switch on and off the components. Right now we only have two of them, but I think we should cover most of the components.

![image](https://user-images.githubusercontent.com/39271899/195221853-c6416b60-513a-42e1-ab5d-737508df44cf.png)

**Comment by tyn1998** [comment]
Totally agree.

**Comment by tyn1998** [comment]
Hi @wxharry, this feature must be a complex one so I think we can learn from rgh 😃 

- https://github.com/refined-github/refined-github/blob/main/source/options.tsx

**Comment by wxharry** [comment]
@tyn1998 Hi Lam, I am working on this issue and found that as we use the new injection mechanism, we change the feature id. However, we need feature id in the locale to get the correct message. Do you think we need to replace all the feature id according to the new mechanism or we simply implement a mapping to do it?

**Comment by tyn1998** [comment]
Hi @wxharry, IMO just replace all the feature IDs 🚀

**Comment by tyn1998** [comment]
Yeah their README will be treated as some kind of source code and parsed to generate a feature list then used by other code. It's a great design with which we need only to maintain a feature list in one place and consume them anywhere.

vote +1 :)

**Comment by wxharry** [comment]
> Yeah their README will be treated as some kind of source code and parsed to generate a feature list then used by other code. It's a great design with which we need only to maintain a feature list in one place and consume them anywhere.
> 
> vote +1 :)

For now, it won't block me from implementing the option management. So, further discussion maybe needed how to better add the feature list to the readme because different from rgh, we also have locale. we need to make sure that the information from the readme and locale is consistent.

**Comment by tyn1998** [comment]
OK, let's convert it to a new feature issue!

**Comment by wxharry** [comment]
@tyn1998 Hi, Lam. I remembered you mentioned we can implement cache management in the options somewhere. What is our use case for cache? Are we supposed to put charts in the cache and add a clear cache button in the options?

**Comment by tyn1998** [comment]
@wxharry maybe for #402? 

I think we can introduce a cache feature later, ATM we keep the developing option management system simple 😆 and release it with v1.9.0 ASAP.

**Comment by tyn1998** [comment]
closed via #659
