### ISSUE TITLE
[CI] auto add issues comment reply status 

### ISSUE THREAD

**Issue by zhicheng-ning** [hypertrons/hypertrons-crx#475]
### Description

mark the status of the issue as pending handle (contributor should reply) or pending feedback (issue author should reply) like this

![image](https://user-images.githubusercontent.com/39022409/195244142-d5b5ae68-74e9-4b12-bc3d-2aa0b0896563.png)

Reference: https://github.com/dataease/dataease/issues

**Comment by wxharry** [comment]
The idea is great. However, we have already had `menbotics` to help manage the repo, including labels. Is it a good way to use two different bots to manage the labels?

**Comment by zhicheng-ning** [comment]
Since I'm not familiar with `menbotics`, if the `menbotics` can be configured to implement above function, we can just use `menbotics`.

**Comment by tyn1998** [comment]
@zhicheng-ning thanks for your idea!

Please tell me if I understand right: this CI will toggle the labels multiple times once new comments are made into a certain issue?

**Comment by zhicheng-ning** [comment]
Yes,only issue author comment and other comment are distinguished and triggered only when two adjacent comments belong to the above two types of comments

**Comment by tyn1998** [comment]
This toggle ability is great, so maintainters can get issue status in issue list page at a glance.

I have some suggestions:

- rename labels for better understranding: waiting for repliers & waiting for author, respectively
- give the two labels two colors: not decided yet (can adopt the colors used by [dataease](https://github.com/dataease/dataease/issues))

**Comment by zhicheng-ning** [comment]
> I have some suggestions:

I see. I will update my pull request later.

**Comment by tyn1998** [comment]
Done!

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/32434520/195260404-2efe2457-e2d0-4827-8242-25c87dfeea77.png">
