### ISSUE TITLE
[Bug] style of perceptor tab in profile page crashes

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#478]
### Version

1.7.0

### Current Behavior

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/32434520/195639776-52f7cf01-4de7-45c4-8477-7cb8eb3c3632.png">

### Expected Behavior

Not as above.

### Environment

```markdown
- OS: macOS Monterey M1
- Browser: 105
```

### Any additional comments?

Pending for a few days to see if it is really a GitHub style change

**Comment by wxharry** [comment]
Anyway, we would need to modify the style to be conformed with our new features.

**Comment by zhicheng-ning** [comment]
Me too.
![image](https://user-images.githubusercontent.com/39022409/195834670-d55b58ae-8c78-4c0a-b275-91c0e022349f.png)

- Environment
```
- OS：Windows 11 Insider Preview
- Browser：Chrome 106
```
