### ISSUE TITLE
[Bug] sidebar render again when backing

### ISSUE THREAD

**Issue by xgdyp** [hypertrons/hypertrons-crx#479]
### Current Behavior

I use hypercrx v1.7.0 and If I browse some one's profile , It run correctly like 
![image](https://user-images.githubusercontent.com/37795442/195787995-dbbe7093-3ce6-48a4-89e8-134b59b21697.png)
Then I jump to a link like
![image](https://user-images.githubusercontent.com/37795442/195788289-4483c4e0-815c-4c33-874a-952a2cbe1f14.png)
It run correctly, too.
But if I click back button
![image](https://user-images.githubusercontent.com/37795442/195788413-cd78099c-f7d7-4dd8-9685-8d00010f28d9.png)
The tooltip(?or other name) render again.
![image](https://user-images.githubusercontent.com/37795442/195788761-53295bb3-3b24-486a-bdf6-c00e0d9771bd.png)

### Environment

```markdown
- OS:MacOs M1
- Browser:Chrome
```

**Comment by tyn1998** [comment]
Hi, @xgdyp. Thanks for your feedback!

Unexpected behaviours that happen in history navigation is not uncommon. I wrote code to handle these problems before, but as you encounter them again, GitHub has apparently updated their UI recently.

**Comment by xgdyp** [comment]
OK

**Comment by tyn1998** [comment]
> Hi, @xgdyp. Thanks for your feedback!
> 
> Unexpected behaviours that happen in history navigation is not uncommon. I wrote code to handle these problems before, but as you encounter them again, GitHub has apparently updated their UI recently.

,so we should fix this. This issue will be closed by a PR.
