### ISSUE TITLE
[UI] the position of a chart title should be adjusted

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#480]
### Description

To make it center:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/32434520/195795746-37325be3-ff1c-4ce2-80b6-c23d2c5be734.png">

PS: the issue is introduced by recent commits so the published version is not affected.

**Comment by andyhuang18** [comment]
Maybe I can have a try~

**Comment by tyn1998** [comment]
:thumb_up: Great!

andyhuang18 ***@***.***>于2022年10月14日 周五18:52写道：
