### ISSUE TITLE
[Feature] Custom data aggregation function for users.

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#487]
### Description

Right now, we have lots of data to show in Hypercrx, but for users, they may want to know the aggregated result for multiple repositories or even compare among different sets of repos.

Can we add a new config in Hypercrx to provide aggregate function. Add a new config like this:
```json
[{
  "main":"hypertrons/hypertrons-crx",
  "repos":[
    "hypertrons/hypertrons-crx",
    "hypertrons/hypertrons-website"
  ]
}]
```
Then the data show in hypertrons-crx repo should be an aggregated result of two repos.

Further more, if we add more config of sets of repos, we may add a new comparison view to compare the data among projects(sets of repos or even orgs).

Is this feasible?

**Comment by wxharry** [comment]
That is great!
IMO, we could add a new view in `perceptor` tab to show the aggretated results and comparison features.
It sounds like a new project to me thou.

**Comment by tyn1998** [comment]
Hi @frank-zsy, personally I think it's kind of wierd to make a certain repo to be a dashbord of aggregated data for a group of projects. If we want to show aggregated data for an Org, we can put charts in GitHub org pages.

If we want to show aggregated data that contains projects in different organizations, like X-lab and Hypertrons, I am inclined to use Extension Options Page(which can do more then provide options) to display aggregated data for a group of projects and we also can turn the Popup Page to a quick entrance of your favourate groups:

Popup page as quick entrance:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/32434520/196578216-59d3788f-60cc-4019-97c0-25d8e8f8bb7e.png">

Options page shows aggregated data:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/32434520/196578473-92907a67-8dd2-493a-ad7a-17ff6f6d1eb6.png">

We can also use `chrome.storage` API to store users' favourate groups so they can be synced between devices by a google (or Edge?) account.

**Comment by tyn1998** [comment]
> IMO, we could add a new view in `perceptor` tab to show the aggretated results and comparison features.
> It sounds like a new project to me thou.

Hi @wxharry, the Perceptor might be a dashboard or a reactive report in future :)

See https://github.com/X-lab2017/open-digger/issues/986#issuecomment-1266481486

**Comment by frank-zsy** [comment]
@tyn1998 Good point. But my concern is that if a user put lots repo groups in setting, the page in favorite groups could be really long. And at most time, users may want to compare group of projects, then the most instinct place is in these repos.

**Comment by tyn1998** [comment]
Oh I got your point: how to directly go to current repo's group page without scrolling and searching?

Maybe we can also put a button in a repo page if the current repo is in one of the user's favourate groups, then a click on the button will bring the user to the group-level page the repo belongs to.

**Comment by tyn1998** [comment]
Another thing to concern: if we use `.github/hypertrons.json` to store the repo groups, only maintainers of repos can control what repos are in a group; if we use `chrome.storage` to store the repo groups, we let users control their favourate groups.

The two strategies both have their strength.

**Comment by tyn1998** [comment]
Hi guys, I produced a prototype for this feature in [MasterGo](https://mastergo.com/file/77026605554366?page_id=M&source=link_share), you can have a look :)


https://user-images.githubusercontent.com/32434520/200306078-f16e06bf-24e2-40e9-83e8-5c36ef0dda80.mov

**Comment by frank-zsy** [comment]
That is really cool!

**Comment by HalloMelon** [comment]
Close this issue since it has been mentioned in OSPP.
