### ISSUE TITLE
[Doc] Readme suggestion. 

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#489]
### Description

I think right now it is really hard to find out the extensions installation path in the README doc even for me.

I think we should move the `install` part before the `Dashboard` part, and use click hyperlinks rather than browser logos to tell the users exactly where to find the extensions.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/8512426/197311900-38c61cb3-b870-4336-bd24-d42ebab275c7.png">

This part is surrounded by lots of charts and technical details, so we should move it to the top of the doc.

**Comment by frank-zsy** [comment]
And I think Opera extension is not available right now, am I right?

**Comment by frank-zsy** [comment]
And according to the [installation guide docs](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.md#-360-safety-explorer), we may also support 360-safety and 360-speed browser as well.

Does the release process cover these two types, if not we may need to remove the counterpart from the docs too.

**Comment by tyn1998** [comment]
> ### Description
> I think right now it is really hard to find out the extensions installation path in the README doc even for me.
> 
> I think we should move the `install` part before the `Dashboard` part, and use click hyperlinks rather than browser logos to tell the users exactly where to find the extensions.
> 
> <img alt="image" width="456" src="https://user-images.githubusercontent.com/8512426/197311900-38c61cb3-b870-4336-bd24-d42ebab275c7.png">
> 
> This part is surrounded by lots of charts and technical details, so we should move it to the top of the doc.

Hi @frank-zsy, I totally agree with you. People complained about the hard-to-find download icons several times, so we should make them more outstanding.

> And I think Opera extension is not available right now, am I right?

Yes, the icon should not be there.


> And according to the [installation guide docs](https://github.com/hypertrons/hypertrons-crx/blob/master/INSTALLATION.md#-360-safety-explorer), we may also support 360-safety and 360-speed browser as well.
> 
> Does the release process cover these two types, if not we may need to remove the counterpart from the docs too.

These browsers are chromium based, so they can install chrome extension. But we don’t have a workflow to upload the extension to 360 webstore, so I think we can temporarily remove them from the install guidance.

**Comment by frank-zsy** [comment]
Alright, I will remove other browser related doc int the PR #490 as well.

/self-assign

**Comment by tyn1998** [comment]
We also have Chinese README 😆 , the always forgotten one.

Hi, @Zzzzzhuzhiwei, would you like to update the Chinese README?

**Comment by Zzzzzhuzhiwei** [comment]
Sure!

/self-assign
