### ISSUE TITLE
[Feature] Google or Baidu analytics embed

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#491]
### Description

I really want to know how many developers use Hypercrx and how often do they use it.

Is it possible to embed Google analytics or Baidu tongji into extension?

**Comment by tyn1998** [comment]
Google Analytics from Chrome Webstore:

"安装量和卸载量"：

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/32434520/197322917-e4e32b46-3fc5-452f-b694-545517e56b6d.png">

“展示次数”：

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/32434520/197322999-15bf8784-53f1-487e-ba3e-f700b449b8e5.png">

“周用户人数”：

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/32434520/197322979-026bd2fd-1c1c-4376-ac0d-eec6a27161f1.png">

**Comment by tyn1998** [comment]
# Edge Add-on Store Analysis

### 每周用户数

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/32434520/197323134-2d5f2746-66f2-4eef-9355-01650f37070c.png">

### 安装

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/32434520/197323150-c52c8424-2c51-4840-bf61-78d82325b43b.png">

### 展示数

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/32434520/197323163-f856ffd2-a25f-4a02-bd08-36cbffa54491.png">

**Comment by frank-zsy** [comment]
Alright, so the data can be accessed in the Chrome store, and Chrome already did this for all the extensions right? Great, thanks.

**Comment by tyn1998** [comment]
Yes, anyone with admin access to the extensiion can visit the analysis page.

**Comment by frank-zsy** [comment]
Got that, thanks.

**Comment by will-ww** [comment]
Really great~
