### ISSUE TITLE
how to calculate influence

### ISSUE THREAD

**Issue by Lucyaaaaaaaa** [hypertrons/hypertrons-crx#493]
How exactly is influence calculated？

**Comment by tyn1998** [comment]
Hi @Lucyaaaaaaaa, metrics such as `activity` and `influence` are defined and implemented in [X-lab2017/open-digger](https://github.com/X-lab2017/open-digger). For `influence`, actually it is implemented as `openrank`, you can get more information by referring to [activity_or_openrank.ts](https://github.com/X-lab2017/open-digger/blob/master/src/metrics/activity_openrank.ts) or [activity_or_openrank.py](https://github.com/X-lab2017/open-digger/blob/master/src/metrics/activity_openrank.ts) if you are more familiar with Python.

I'm not good at the details of how these metrics are caculated, while I can provide you several important blogs that explain how OpenRank works:

- https://blog.frankzhao.cn/github_activity_with_wpr/
- https://blog.frankzhao.cn/open_rank_and_open_galaxy/
- https://blog.frankzhao.cn/how_to_measure_open_source_2/

**Comment by Lucyaaaaaaaa** [comment]
>
