### ISSUE TITLE
[enhanecment] node links are hard to select

### ISSUE THREAD

**Issue by xxchan** [hypertrons/hypertrons-crx#496]
### Description

There are too many links in the graph and it's hard to find a link between two nodes.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/37948597/198847171-e2587b33-a946-4f2e-a974-c6bb310a1183.png">

**Comment by tyn1998** [comment]
Hi @xxchan, thanks for your valuable suggestion!

The links in repos that have many collaborators are actually hard to view and interact with. We will improve this :)

**Comment by tyn1998** [comment]
In https://github.com/hypertrons/hypertrons-crx/pull/553#issuecomment-1367356478, we made the network charts less dense:)
