### ISSUE TITLE
[Bug] wrong popup position for repo

### ISSUE THREAD

**Issue by xxchan** [hypertrons/hypertrons-crx#497]
### Current Behavior

<img width="714" alt="image" src="https://user-images.githubusercontent.com/37948597/198847271-2f344b1d-f735-4eac-98ae-62953cd8a813.png">

### Environment

```markdown
- OS: MacOS Monterey M1
- Browser: Chrome 106.0.5249.119
```

**Comment by tyn1998** [comment]
Hi @xxchan, thanks for your feedback. The issue might be due to a recent GitHub UI update, we will fix it ASAP.

**Comment by tyn1998** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/32434520/198860026-2ce0640c-b82d-4873-b259-cfd0e6811935.png">

Well, I cannot reproduce the issue on my machine. It seems the teaching bubble is still in its right position. Can you guys help to check if the bug occurs on your machine? @xgdyp @zhicheng-ning @wxharry @wj23027 @andyhuang18 @lhbvvvvv @Zzzzzhuzhiwei 

Note: the teaching bubble won't show again if you once confirmed "不再提示" or "Don't show this again". You must reinstall the extension to make the teaching bubble show.

**Comment by wxharry** [comment]
Hi xxchen, I cannot reproduce the bug either. Could you check which version of hypercrx are you currently using? The current version should be version 1.7.1.

**Comment by xxchan** [comment]
I found this happens when used together with another extension: https://github.com/refined-github/refined-github

**Comment by tyn1998** [comment]
Refined GitHub, that's it! I remember.

https://github.com/X-lab2017/open-wonderland/discussions/142#discussion-4255880

xxchan ***@***.***> 于 2022年10月30日周日 23:41写道：

**Comment by wxharry** [comment]
Unfortunately, hypercrx currently is not compatable to refine-github. Users may need to swtich off some of the features of refined-github to use hypercrx properly.

**Comment by zhicheng-ning** [comment]
> Can you guys help to check if the bug occurs on your machines?

It seems no problem in my environment.
```
- OS：Windows11 22H2
- Browser: Chrome 106.0.5249.120
```
![image](https://user-images.githubusercontent.com/39022409/198915595-64ef1a2d-6376-4572-9a30-a46796edf532.png)

**Comment by tyn1998** [comment]
Thank you for your feedback, I think we have found the cause so the issue will be closed :)
