### ISSUE TITLE
[docs] add a section to introduce OpenDigger so people can know more about our data

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#498]
### Description

Data is the core of Hypercrx. If people know more about OpenDigger, they will know more about our data.

**Comment by wxharry** [comment]
#509

**Comment by tyn1998** [comment]
For README, How about naming the section as "Data Source" | "数据来源" and insert it to between "Install" and "Dashboard"?

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/32434520/201452009-92ffbd44-7158-46aa-b5db-2925490fe43c.png">

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/32434520/201452025-0727b961-f109-4e49-b631-46958977d733.png">
