### ISSUE TITLE
[CI/CD] a more flexible release workflow is needed 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#506]
### Description

At the moment we have a [release-deploy](https://github.com/hypertrons/hypertrons-crx/blob/a056deb25138704eeeb4be31517e788a62b29a16/.github/workflows/release-deploy.yml) workflow that releases a new version and uploads the built extension to webstores.

However, the workflow lacks flexiblity:

- version bumping is only controlled by semantic version, cannot be specified a new version number by hand
- there is no time left between release and upload for maintainers to decide if the released version should be uploaded to the webstores. since version number can only be monotonically increasing in stores, we should be carefull about the released version number.

I think we should improve the workflow to make the release process more flexible.

**Comment by tyn1998** [comment]
Hi @wxharry, could you help with this improvement? It is not an emergent issue so you can take your time.

**Comment by wxharry** [comment]
sure. I will work on this.
/self-assign

**Comment by tyn1998** [comment]
I'm also thinking it may be not necessary for Hypercrx to adopt `convontional commits` + `semantic versioning` to manage its versions, as @frank-zsy once pointed out the combination is not suitable for OpenDigger since we are not building a library-like or framework-like project that will be a dependency of other projects. And at the moment, we never have the chance to bump the major number since we will introduce no breaking change. 

Other version bumping strategies should be learned and investigated.

(Just a little thought put here)

**Comment by wxharry** [comment]
> I'm also thinking it may be not necessary for Hypercrx to adopt `convontional commits` + `semantic versioning` to manage its versions, as @frank-zsy once pointed out the combination is not suitable for OpenDigger since we are not building a library-like or framework-like project that will be a dependency of other projects. And at the moment, we never have the chance to bump the major number since we will introduce no breaking change.
> 

I totally agree. The semantic versioning could be redundant here. I am planning to use it only for automation purposes or maybe completely remove it from the workflow.

**Comment by wxharry** [comment]
Hi, I survive the final projects. Here is my idea on the new workflow:

Basically, we need to replace the [CCA part](https://github.com/hypertrons/hypertrons-crx/blob/master/.github/workflows/release-deploy.yml#L20-L27) with some other tools to have a more flexible version bumping and release workflow. Details are as followed:
1. remove CCA code as mentioned above
2. trigger release-deploy job by creating a release [here](https://github.com/hypertrons/hypertrons-crx/releases/new)
3. use scripts to bump versions and update changelogs (expecting to write some scripts to do so and run commands like node run release in the Github Actions)
4. update the release we just created to the latest commit

I am still working on this, so if you have any advice or anything you want to add to the workflow, feel free to leave a comment.

**Comment by tyn1998** [comment]
Hi, @wxharry, thanks for your idea. Here are mine:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/32434520/208027830-73fea685-2943-47a8-814c-554ea2880823.png">

I think we will have two main workflows called "release.yml" and "publish.yml" respectively, which can be regarded as a split of the "release-deploy.yml" workflow.

Both workflows are manually triggered. "release.yml" has an input that specifying a new version number and it will create a new git tag and a new GitHub release. we need that new tag because it is the input for "publish.yml". As you can see, this is a 2-step strategy: 

1. we create a release and a corresponding tag
2. then we just choose the tag to publish the extension to the stores

> 2. trigger release-deploy job by creating a release [here](https://github.com/hypertrons/hypertrons-crx/releases/new)

Does it mean manually create a release from GitHub UI? If so, I think it is not very convenient.

Here are my references:

- [release of opensumi/shortcuts-guard](https://github.com/opensumi/shortcuts-guard/blob/3db4f98f72e630ca9c466caa2e9304a602979388/.github/workflows/release.yml)
- [release of opensumi/core](https://github.com/opensumi/core/blob/f146a8adc6bdf2de08b7952a6a26b31f02ca4e80/.github/workflows/release.yml) 
- [my experiments](https://github.com/tyn1998/learn-github-actions/blob/0c9b727af26ccaa054c64db78a86e7d3bc4eba0b/.github/workflows/release.yml)

**Comment by wxharry** [comment]
Ohh, I see what you mean. Yes, this is a very good example to start with. But Looks like their version numbers are modified manually by the members. So in release workflow, it only checks if the current version numbers are correct. I prefer letting the workflow to do. What's your opinion? @tyn1998

**Comment by tyn1998** [comment]
They manually change the numbers in files? I didn't make a deep dive into the code so I didn't know.

Of course, It's best to automatically bump all version numbers in related files after triggering the release workflow.

**Comment by tyn1998** [comment]
I [fired](https://github.com/hypertrons/hypertrons-crx/actions/runs/4209584588/jobs/7306618866) the new release workflow just now and got failed:

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/32434520/219837271-03a2fe67-5e60-4dd9-84d0-54e01e988437.png">

The failure was caused by the protected branch feature enabled in this repo:

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/32434520/219837621-6c7e897c-c10e-4b81-8653-0f913b01e269.png">

Disabling the protected branch feature can make the workflow work, but I'm still searching for other ways...

**Comment by tyn1998** [comment]
Seems no perfect way to handle this kind of situation. Just unchecked all branch protection rules.

Then we have [the release of v1.8.4](https://github.com/hypertrons/hypertrons-crx/releases/tag/v1.8.4):

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/32434520/219839880-4ba7f9c5-1ceb-4257-953d-28322252e7b5.png">

🎉
