### ISSUE TITLE
[Question] API request

### ISSUE THREAD

**Issue by xueqidove** [hypertrons/hypertrons-crx#509]
### Description

Can you provide all github apis used by this plug-in

**Comment by tyn1998** [comment]
Hi @xueqidove, here is [a main API](https://github.com/hypertrons/hypertrons-crx/issues/395#issuecomment-1203311818) we are using at the moment.

There are several other APIs actually, but they might be deprecated recently, so I will not provide them here.

**Comment by tyn1998** [comment]
API has changed, please refer to https://github.com/hypertrons/hypertrons-crx/issues/515
