### ISSUE TITLE
[UI] Slight change request of new UI design

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#510]
### Description

As mentioned in #495 , we have a new design style, but there are still some slight changes need to be made.

1. Should add 4px for top padding. 
![image](https://user-images.githubusercontent.com/8512426/200292924-dab1bcd8-77a7-4319-aaa6-a6c24923ec8f.png)
2. Should minus 4px for left and right padding.
![image](https://user-images.githubusercontent.com/8512426/200292988-84c6c2a9-e12b-42a7-8449-9d38f844f0ab.png)
3. The background color for dark mode panel should be `#161B22` rather than `#0D1117` which may feel a little bit ligther.
4. In the light mode, the panel should have a drop shadow to distinguish the panel from background.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/8512426/200302531-9688e481-4451-4409-9be4-04e7e3c01c59.png">

**Comment by tyn1998** [comment]
Anyone wants to take this issue? Feel free to self-assign :)

**Comment by wj23027** [comment]
I can try to do it~
