### ISSUE TITLE
[Refactor] Data migration

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#515]
### Description

As the feature implemented in https://github.com/X-lab2017/open-digger/pull/1036 , the data for OpenDigger will be in a new place with new identical form.

The basic URL will be `https://oss.x-lab.info/open_digger/github`, and there will be 16 repo metrics and 2 user metrics right now. The repo metric will be at `{basicUrl}/{owner}/{repo}/{metric}.json` and user metric will be at `{basicUrl}/{login}/{metric}.json`.

The repo metrics are:
- activity: https://oss.x-lab.info/open_digger/github/apache/flink/activity.json
- openrank: https://oss.x-lab.info/open_digger/github/apache/flink/openrank.json
- attention: https://oss.x-lab.info/open_digger/github/apache/flink/attention.json
- technical_fork: https://oss.x-lab.info/open_digger/github/apache/flink/technical_fork.json
- stars: https://oss.x-lab.info/open_digger/github/apache/flink/stars.json
- issues_new: https://oss.x-lab.info/open_digger/github/apache/flink/issues_new.json
- issues_closed: https://oss.x-lab.info/open_digger/github/apache/flink/issues_closed.json
- code_change_lines_add: https://oss.x-lab.info/open_digger/github/apache/flink/code_change_lines_add.json
- code_change_lines_remove: https://oss.x-lab.info/open_digger/github/apache/flink/code_change_lines_remove.json
- code_change_lines_sum: https://oss.x-lab.info/open_digger/github/apache/flink/code_change_lines_sum.json
- change_requests(open pr): https://oss.x-lab.info/open_digger/github/apache/flink/change_requests.json
- change_requests_accepted(merged pr): https://oss.x-lab.info/open_digger/github/apache/flink/change_requests_accepted.json
- issue_comments: https://oss.x-lab.info/open_digger/github/apache/flink/issue_comments.json
- change_requests_reviews(review comment): https://oss.x-lab.info/open_digger/github/apache/flink/change_requests_reviews.json
- participants: https://oss.x-lab.info/open_digger/github/apache/flink/participants.json
- bus_factor: https://oss.x-lab.info/open_digger/github/apache/flink/bus_factor.json

The user metrics are:
- activity: https://oss.x-lab.info/open_digger/github/frank-zsy/activity.json
- openrank: https://oss.x-lab.info/open_digger/github/frank-zsy/openrank.json

The upload will be completed in this Sunday but repo examples are valid now. And all the data is up to date.

I think we can start the data migration now and the data will be sufficient for Hypercrx now except for network data.

**Comment by tyn1998** [comment]
Hi, @frank-zsy, a few questions here:

1. what is the definition of `attention`?
2. why `fork` is prefixed with `technical_` while `stars` is not?
3. any advice for presenting `bus_factor`?
4. should we make all above metrics appear in GitHub UI?

**Comment by frank-zsy** [comment]
- Attention is 2 * fork + star, which is also an index build by X-lab.
- We keep identical with CHAOSS if the metric exists in CHAOSS. `technical_fork` is a CHAOSS metric while `stars` is not.
- I don't think we should put all the metrics into Hypercrx, you can decide how to use them, I just list them here. You can decide put `bus_factor` into Hypercrx or not, I think this is an interesting metric and can be listed with `participants`.

**Comment by tyn1998** [comment]
Hi @frank-zsy, should I change `Influence` to `OpenRank`?

<img width="378" alt="image" src="https://user-images.githubusercontent.com/32434520/201833781-a4f0c604-cfe3-45a8-a4ef-6a66c2992d24.png">

**Comment by frank-zsy** [comment]
I think OpenRank is better since influence is quite ambiguous, but if we call this OpenRank then we must have a link about how OpenRank is calculated which maybe a document in OpenDigger.

**Comment by tyn1998** [comment]
Well, another question: Is it necessary to translate "OpenRank" to Chinese?

**Comment by frank-zsy** [comment]
I think we don't need to translate OpenRank to Chinese.
