### ISSUE TITLE
[Feature] Issue and pull request related interactions

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#519]
### Description

In issue and pull request charts, when clicking on a certain month data point we can show the data of the certain month.

Like when clicking on the `2021-11` data point in the issue chart on the opens line, we can jump into a new URL like https://github.com/hypertrons/hypertrons-crx/issues?q=is%3Aissue+created%3A2021-11-01..2021-11-30

Or when clicking on the `2020-11` data point in the pull request chart on the merges line, we can jump into a new URL like https://github.com/hypertrons/hypertrons-crx/pulls?q=is%3Apr+merged%3A2021-11-01..2021-11-30

Through this, we can introduce more interactions into Hypercrx and the data charts are not only for observing but also provide quick entrance into detailed data.

**Comment by wxharry** [comment]
Looks similar to a previous issue: 
* #430 
I made this one a good first issue, anyone wants to take it? Can refer to the issue I mentioned above.

**Comment by frank-zsy** [comment]
@wxharry Yes, quite similar, we can design a mechanism to show data for all possible chart interactions.

**Comment by frank-zsy** [comment]
@wxharry Does #430 work now? I find that in my Hypercrx, clicking on activity or influence chart does not lead to a new URL.

**Comment by wxharry** [comment]
Yes. What version are you using? There was a known bug on that feature, clicking is useless on English version. We have fixed it, but might haven't publish that version yet.

**Comment by frank-zsy** [comment]
Thanks, I am using Hypercrx with the English version, the function works fine after switching to the Chinese version.

**Comment by tyn1998** [comment]
closed via #524
