### ISSUE TITLE
[Awesome] Thank you for your great work ❤️

### ISSUE THREAD

**Issue by TommyLemon** [hypertrons/hypertrons-crx#527]
### Description

https://github.com/Tencent/APIJSON
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/202840936-dd798b11-4370-422d-8d13-904ad04f3e56.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/202840962-e0fc450e-e2ce-433c-bfb1-7f8b1b0a3a44.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/202840994-69a0f2da-e25e-428f-a079-df88637b89c4.png">

https://github.com/TommyLemon
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5738175/202841035-b05cd89b-5735-426c-bc21-9f8d9b609f87.png">

**Comment by zhicheng-ning** [comment]
You may also be instersted in [OpenDigger](https://github.com/X-lab2017/open-digger) that offer data for hypertrons-crx 😄.

**Comment by TommyLemon** [comment]
thx, btw, how can I view the statistics for a specific repo or account? 
eg:
https://github.com/Tencent/APIJSON

https://github.com/TommyLemon

**Comment by zhicheng-ning** [comment]
> how can I view the statistics for a specific repo or an account?

If you want to know :
- a specific repo, you can follow [project-related](https://github.com/hypertrons/hypertrons-crx#project-releated). 
- a specific account, you can follow [developer-related](https://github.com/hypertrons/hypertrons-crx#developer-releated).
- more detail data, you can go to  [OpenDigger](https://github.com/X-lab2017/open-digger) raise some issues.

btw, we'll be coming up with some big screens with open source insights: 
- XSOSI: http://dataease.nzcer.cn/link/E1OQKVBz
- Community Level:  http://dataease.nzcer.cn/link/1VxPsUCX
- Project Level
- Foundation Level
- ....

**Comment by tyn1998** [comment]
Hi @TommyLemon, we are so glad that you love the extension! We will make it a better one :)
