### ISSUE TITLE
[Bug] Part of the chart for stars was covered

### ISSUE THREAD

**Issue by TommyLemon** [hypertrons/hypertrons-crx#528]
### Version

1.7.3

### Current Behavior

Part of the chart for stars was covered. 
https://github.com/Tencent/APIJSON

![](https://user-images.githubusercontent.com/5738175/202840962-e0fc450e-e2ce-433c-bfb1-7f8b1b0a3a44.png)

### Expected Behavior

Move the chart lower that make it show completely.

### Environment

```markdown
- OS: MacOS Monterey 12.6
- Browser: Chrome 107.0.5304.110（正式版本） (x86_64)
```

### Any additional comments?
None.

**Comment by tyn1998** [comment]
Hi @TommyLemon, thanks for your feedback! But I cannot repeat the problem you met🤔  :

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/32434520/202851554-7dc045c7-cfb2-4979-bbe9-d5b39691b109.png">

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/32434520/202851583-35133ea9-e689-4ec5-9a82-d83847281cbd.png">

**Comment by andyhuang18** [comment]
When I open page in window mode and scroll the page sightly, this problem arises.

![微信截图_20221119220713](https://user-images.githubusercontent.com/50283262/202854762-fc377d8e-2c83-4ef2-9bc3-12c350211f97.png)

**Comment by tyn1998** [comment]
I have also tried this way but cannot reproduce the phenomenon 😆

**Comment by TommyLemon** [comment]
@tyn1998 u need to scroll up the web page, if u don't, it will just show completely.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/202857426-87d43af9-d75a-4073-ae9f-9a7b6af0fcba.png">

**Comment by tyn1998** [comment]
Close for now, anyway, thanks for your feedback!
