### ISSUE TITLE
[Discussion] should we use dynamic import for loading components ?

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#53]
Currently one component is corresponding to one feature ( e.g. DeveloperCollabrationNetwork). And we need load these components in `DashboardService` based on the configuration. For example, if the configuration is something like:

```
{
    name: 'DeveloperCollabrationNetwork',
    enable: true,
    ...
},
{
    name: 'ProjectCorrelationNetwork',
    enable: false,
    ...
  }
...
```
Then we should load `DeveloperCollabrationNetwork` component and **NOT** load `ProjectCorrelationNetwork` component in `DashboardService`. Here's the logic: 

``` js
import DeveloperCollabrationNetwork from '../components/DeveloperCollabrationNetwork';
import ProjectCorrelationNetwork from '../components/ProjectCorrelationNetwork';

for (const componentConf of componentsConf) {
  const {
    name,
    enable,
    props,
  } = componentConf;
  if (!enable) {
    console.log('Skipping ', name);
    continue;
  }
  switch (name) {
    case 'DeveloperCollabrationNetwork':
      render(
        <DeveloperCollabrationNetwork props={props} />,
        insertItem,
      );
      break;
  case 'ProjectCorrelationNetwork':
      render(
        <ProjectCorrelationNetwork props={props} />,
        insertItem,
      );
      break;
    default:
      break;
  }
}
```

But in this way, I need declare and import `DeveloperCollabrationNetwork` and `ProjectCorrelationNetwork` in advance. I don't think it's a good implemation If we have 10+ components (maybe more) someday.

I am trying to use `React.lazy()` and `dynamic import` to load the components dynamically:

```js
const Component = React.lazy(() => import(`../components/${name}`));
```

But I just got `Loading chunk 1 failed` exceptions. Here's the similar situation: https://stackoverflow.com/questions/53704950/webpack-code-splitting-loading-chunk-failed-error-wrong-file-path. 

And I tried the answer but it still didn't work. Here's the corresponding branch: https://github.com/hypertrons/hypertrons-crx/tree/dev

Here's the code: https://github.com/hypertrons/hypertrons-crx/blob/c3e0c39189ae3cb476f498217e5a63977ffe7f50/src/pages/Content/common/DashboardService.tsx#L55

![image](https://user-images.githubusercontent.com/26642280/110269559-f728d080-7ffe-11eb-947a-cc498debbd53.png)

Is there anything that I missed? Is it a good idea to use ` dynamic import`? Do you @LiuChangFreeman have any suggestions ? Thanks~~

**Comment by LiuChangFreeman** [comment]
I think the error is caused by the security check mechanism made by Chrome.  
Chrome extensions must not load local resources which are not in the whitelist defined in `manifest.json`.  
```json
{
  ...
  "web_accessible_resources": [
    "content.styles.css",
    "128.png"
  ],
  ...
}
```
The `React.lazy()` is designed for reducing http-requests when user visit a website for the first time. But in our scenario, all resources must have been installed to the local folder.  So we needn't use `React.lazy()` at all, otherwise it will cost us a lot of time to debug. 
Please consider solve the `dynamic import` problem using any other methods. In my opinion, the number of components introduced in our project will not be a matter. So we needn't consider it at the very beginning.

**Comment by heming6666** [comment]
### Update

As mentioned in this PR #93, Now we use `Inject` to implement the dependent logic of `Perceptor` class and component class.
Here's the `inject` function:
```ts
export function Inject(modules: any) {
  return function (target: any) {
    modules.forEach((module: any) => {
      const instance = new module();
      target.features.set(instance.constructor.name, instance)
    });
  };
}
```

Here's the usage: 
```ts
@Inject([
  PerceptorTab,
  PerceptorLayout,
  DeveloperNetwork,
  ProjectNetwork
])
class Perceptor extends PerceptorBase {
...
    // run every features
    Perceptor.features.forEach(async (feature, name) => {
      if (this.settings.toJson()[name] === false) {
        return;
      }
      if (feature.include.every((c: () => any) => !c())) {
        return;
      }
      try {
        this.logger.info('running ', name)
        await feature.run();
      } catch (error: unknown) {
        this.logger.error(name, error)
      }
    }, this)
...
}
```

It means that if we want to add a new feature (e.g. FeatureX) to `Perceptor`, then we only need to do the following things:
- add a `FeatureX` class that extends `PerceptorBase` class. And implement the logic.
- add  `FeatureX` to the `Inject` decorator. For example: 
```ts
@Inject([
  ...
  FeatureX
])
class Perceptor extends PerceptorBase {...}
```

**Comment by heming6666** [comment]
Closed.
