### ISSUE TITLE
[Proposal] Build a website to show our chart just like star-history.com

### ISSUE THREAD

**Issue by sunny0826** [hypertrons/hypertrons-crx#532]
### Description

This is a very interesting project. **I wish more people understood and used it.**

However, the users and distribution channels of browser plugins are still limited. I want us to build a website (like [start-history](https://star-history.com ) that outputs charts as images (CSV, Embed Chart, etc. ) and I want to embed these charts in my projects, profiles and wherever.

This gives users the freedom to choose which charts they want to embed in the `README` and `Profile`, while also attracting more users, as I did when I first learned about [star-history](https://github.com/bytebase/star-history).

**Comment by sunny0826** [comment]
refer repo: 
- https://github.com/bytebase/star-history
- https://github.com/yoshi389111/github-profile-3d-contrib
- https://github.com/tipsy/profile-summary-for-github
- https://github.com/vn7n24fzkq/github-profile-summary-cards
- https://github.com/rzashakeri/beautify-github-profile

**Comment by will-ww** [comment]
> refer repo:
> 
> * https://github.com/bytebase/star-history
> * https://github.com/yoshi389111/github-profile-3d-contrib
> * https://github.com/tipsy/profile-summary-for-github
> * https://github.com/vn7n24fzkq/github-profile-summary-cards
> * https://github.com/rzashakeri/beautify-github-profile

Many thanks, so many interesting projects~

**Comment by tyn1998** [comment]
This issue was transferred (manually) to https://github.com/orgs/X-lab2017/discussions/238. We can discuss it there :)
