### ISSUE TITLE
[Feature] a better feature manager

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#534]
### Description

Hypercrx has many features(almost them are charts at the moment) and they are all [registered](https://github.com/hypertrons/hypertrons-crx/blob/1269689bf749d5fde189dfdf47d485103f19d0af/src/pages/ContentScripts/index.ts#L23-L35) to [Perceptor class](https://github.com/hypertrons/hypertrons-crx/blob/1269689bf749d5fde189dfdf47d485103f19d0af/src/Perceptor.tsx#L69-L71). I think there is a lot of room for improvment of this strategy since I had a glance at how [refined-github](https://github.com/refined-github/refined-github) arranges [the same thing](https://github.com/refined-github/refined-github/blob/main/source/feature-manager.tsx).

I will add what we can benifit from a new feature manager into this description later :)

**Comment by frank-zsy** [comment]
I would like to know more detail about the architecture, I think I started the register strategy in the very early edition of Hypercrx.

**Comment by tyn1998** [comment]
closed via #548
