### ISSUE TITLE
[Bug] OpenDigger data api will change time format

### ISSUE THREAD

**Issue by xgdyp** [hypertrons/hypertrons-crx#541]
### Current Behavior

As discussed in https://github.com/X-lab2017/open-digger/issues/1074 and merged in https://github.com/X-lab2017/open-digger/pull/1078, we will change time format from `yyyym(m)` to `yyyy-mm`.

So I think hypercrx need to be ready for this change.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by tyn1998** [comment]
Got that, I will handle this. Thank you for your reminding!

/self-assign
