### ISSUE TITLE
[Typo] "collabration" should be "collaboration"

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#558]
### Description

I found two:

![image](https://user-images.githubusercontent.com/32434520/211233289-f8c90ec2-3183-4039-abfe-1a6914f710f7.png)

![image](https://user-images.githubusercontent.com/32434520/211233332-eb435fc2-1da7-4fe7-97be-57eb511b7c36.png)

Maybe exists in other places.

**Comment by kwnna99** [comment]
Can I work on this?

**Comment by tyn1998** [comment]
Sure, please :-)

**Comment by kwnna99** [comment]
Great! If you can, please assign it to me

**Comment by tyn1998** [comment]
You are welcomend to read the CONTRIBUTING. And in "[1. Claim an issue](https://summer-ospp.ac.cn/#/org/orgdetail/75d366c8-fcdf-4be9-a106-cade8978920d/)" you will find leaving `/self-assign` in a comment then the bot will automatically assign the issue to you :)
