### ISSUE TITLE
[other] labeling principles 

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#563]
### Description

As we are working on the new workflow, a clear labeling principle for issues and prs is needed.
I noticed `hypercrx` has [menbotics](https://github.com/apps/menbotics) to do this, but I am not sure about how it works. Can we configurate menbotics to meet our requirements or we need another labeler?

referring to [opensumi/core issue page](https://github.com/opensumi/core/issues) as a good example which has a neat and organized labeling.

**Comment by frank-zsy** [comment]
@wxharry Menbotics uses Hypertrons to manage automation work in community, the issue label work is based on the [`.github/hypertrons.json` config file](https://github.com/hypertrons/hypertrons-crx/blob/b277ea21b29929c1021edcac87a294094e171161/.github/hypertrons.json#L39) which uses keywords in issue or pull request title to add labels.

As the config merges the [default config from Hypertrons component](https://github.com/hypertrons/hypertrons/blob/master/app/component/label_setup/defaultConfig.ts#L17), you can check out all the labels and what keywords are used to identify the labels to add. And with `label_setup` component, you can also config the labels' color and description as same time with their names and keywords.

If you want to change or add more labels or config, you can just change the `.github/hypertrons.json` file in this repo and Hypertrons supports config hot reload, the config will take effect right after commit on master branch.

**Comment by tyn1998** [comment]
Hi @frank-zsy, I have a question: what if I delete all labels in [here](https://github.com/hypertrons/hypertrons-crx/labels)? Will they be created automatically(if not exist) every time menbotics is going to label an Issue or PR? In another word, if the majority of the labels in this repository are created automatically by menbotics rather by a human?

**Comment by frank-zsy** [comment]
> Hi @frank-zsy, I have a question: what if I delete all labels in [here](https://github.com/hypertrons/hypertrons-crx/labels)? Will they be created automatically(if not exist) every time menbotics is going to label an Issue or PR? In another word, if the majority of the labels in this repository are created automatically by menbotics rather by a human?

Yes, the purpose of Hypertrons `label_setup` component is to manage labels totally automatically. According to the [code](https://github.com/hypertrons/hypertrons/blob/5d916d83f6739002b7fd4a4b82cc27ea505be4de/app/basic/HostingPlatform/HostingClientService/LuaService.ts#L518), the labels will be created when `label_setup` component runs.

So if you delete the labels, you should also change the config file at least once to trigger component reload, the component will create all the labels in config file automatically with the config, including colors and descriptions. But it will not delete any labels on GitHub and it will not check if the label is deleted when you add labels to issue.

And if you want to manage your labels totally, you can remove `"__merge__": true` config in the config file or change it to `false`, then it will not load the labels from component default config.

**Comment by tyn1998** [comment]
> And if you want to manage your labels totally, you can remove "__merge__": true config in the config file or change it to false, then it will not load the labels from component default config.

That's great! And thank you for your explanation.

**Comment by wxharry** [comment]
I will close this issue for we know how labeling works in the repo. Thanks @frank-zsy
