### ISSUE TITLE
[Bug] The pull request chart not show when some files missing

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#564]
### Version

1.8.3

### Current Behavior

In https://github.com/alibaba/havenask , the pull request data chart can not show because review data file is missing.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/8512426/211961756-b60fd981-9518-42f6-8b7a-143d9878b777.png">

Since some repos may not use review function in their collaboration, for issue or pull request data charts, missing files should not block existing data to show.

### Expected Behavior

Show pull request chart without review data, but new pull request and merged pull request data.

### Environment

```markdown
- OS: MacOS Monterey
- Browser: Chrome 108.0.5359.124
```

**Comment by tyn1998** [comment]
Nice catch, thanks for reporting it! This situation was not considered before.

We will fix it ASAP.
