### ISSUE TITLE
[Refactor] rewrite all existing chart features by the new feature loading mechanisim

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#574]
### Description

In #548, we worked out a new feature loading mechanism and had `RepoActORTrend` refactored to `repo-activity-openrank-trends` by this new mechanism.

There are other existing features waiting to be refactored in that way and they are:

- [x] DeveloperActORTrend -> developer-activity-openrank-trends (@lhbvvvvv)(#596)
- [x] DeveloperNetwork(@tyn1998 )(#638)
- [x] PerceptorLayout (@wxharry)(#589)
- [x] PerceptorTab (@wxharry)(#589)
- [x] ProjectNetwork(@tyn1998 )(#637)
- [x] RepoDetailFork (@tyn1998)(#575)
- [x] RepoDetailIssue (@tyn1998)(#598)
- [x] RepoDetailPR (@tyn1998)(#600)
- [x] RepoDetailStar (@tyn1998)(#584)
- [x] RepoHeaderLabels (@tyn1998)(#602)
- [x] OSS-GPT(@tyn1998 )(#639)

Each should be resolved by a PR targeted to the branch ~`v2.0.0`~`v1.9.0`. This issue is opened for tracking the progress of refactoring and should be finally closed manually rather automatically by PR keywords.

**Comment by tyn1998** [comment]
Hi @lhbvvvvv, the refactor of `DeveloperActORTrend` should be similar with the one of `RepoActORTrend` which is already done in #548. So I think you could have a try on this subtask :)

**Comment by wxharry** [comment]
I would like to have a try. 😸

**Comment by tyn1998** [comment]
@wxharry Sure! You could try one or some of:

- DeveloperNetwork
- PerceptorLayout
- PerceptorTab
- ProjectNetwork

and I'm workding on xxxDetailxxx features. Met trouble last night, harder than I thought.

**Comment by wxharry** [comment]
> @wxharry Sure! You could try one or some of:

Then I will take the perceptorLayout and PerceptorTab for now.
 

> and I'm workding on xxxDetailxxx features. Met trouble last night, harder than I thought.

Good luck on that one.

**Comment by tyn1998** [comment]
I recommend using `Network Throttling` tool of Chrome DevTools to have the refactored features fully tested before submitting a PR:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/32434520/217477969-903c04b8-8433-4589-955e-2b3f6ba182c2.png">

Because in this way those bugs related to timings can be exposed.

**Comment by lhbvvvvv** [comment]
I'm more than willing

> Hi @lhbvvvvv, the refactor of `DeveloperActORTrend` should be similar with the one of `RepoActORTrend` which is already done in #548. So I think you could have a try on this subtask :)

I am very willing to try this subtask.

**Comment by tyn1998** [comment]
@wxharry @lhbvvvvv

Hi guys, I changed the branch name `v2.0.0` to `v1.9.0` in this repo just now. If you didn't start the tasks at all, you may follow these steps to kick off:

1. `git fetch upstream v1.9.0` or `git fetch upstream` for all branches and tags if you don't mind
2. `git checkout -b <your_branch_name> upstream/v1.9.0`, now you have a working branch
3. after finishing your work push this branch to your origin and create a PR targeted to v1.9.0

If you have already started(i.e. you already have a branch which is checked out from upstream/v2.0.0), I think there is nothing special to do.

Well, there is a chance that you may have checked out a local v2.0.0 whose remote is upstream/v2.0.0, just like you have a local master whose remote is origin/master. I think you don't need a local v2.0.0 at all, just start your work by checking out a branch from the upstream/v2.0.0 and don't forget to fetch the upstream from time to time.

I hope the steps described are right.

**Comment by wxharry** [comment]
Any plan about refactoring the rest of the features? @tyn1998

**Comment by tyn1998** [comment]
I'm gonna refactor `RepoDetailIssue`, `RepoDetailPR`, and `RepoHeaderLabels`.

Would you like to try `ProjectNetwork`? @wxharry 

and, hello @lhbvvvvv, could you refactor `DeveloperNetwork`?

**Comment by lhbvvvvv** [comment]
> I'm gonna refactor `RepoDetailIssue`, `RepoDetailPR`, and `RepoHeaderLabels`.
> 
> Would you like to try `ProjectNetwork`? @wxharry
> 
> and, hello @lhbvvvvv, could you refactor `DeveloperNetwork`?

Ok, I can try to do it.

**Comment by tyn1998** [comment]
Just pushed a [commit](https://github.com/hypertrons/hypertrons-crx/commit/bee576323ad95279703ec618f7cee51273be9b3e) to v1.9.0 where I cherry-picked some commits from the latest master and also manually copy some code from master (cannot simply cherry-pick from a renamed file), however, all OSS-GPT related commits were untouched.

Next, I will refactor ProjectNetwork, DeveloperNetwork and OSS-GPT one by one.

**Comment by tyn1998** [comment]
This is a huge project and it's done!

Thank you @wxharry @lhbvvvvv
