### ISSUE TITLE
[Bug]  newestMonth should not be the last month in data files

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#586]
### Version

1.8.3

### Current Behavior

I happened to visit https://github.com/X-lab2017/open-galaxy which is a long non-maintained repo and found that the `participant` is 6!

<img width="779" alt="image" src="https://user-images.githubusercontent.com/32434520/219571572-fba02df4-96ec-4663-ad2d-f3d7b0d35b79.png">

The cause is that we use the latest month in data files as `newestMonth` due to a wrong assumption: a repo should be active in every month.

https://github.com/hypertrons/hypertrons-crx/blob/6d06a8d54c70f38413941ac718625291478a2527/src/utils/data.ts#L23

### Expected Behavior

Maybe using the last month as `newestMonth` is the right way. For example, if the current month is Feburary, January should be the `newstMonth`.

### Environment

```markdown
- OS: whatever
- Browser: whatever
```

### Any additional comments?

This should be an easy task :)

**Comment by wj23027** [comment]
I can try to fix it~
/self-assign
