### ISSUE TITLE
[Discussion] Make a choice between Antd and Fluent-UI or any other candidates

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#59]
We need to use an elegent `React Component Library` when building our extension. 
They will be used in three places shown by Chrome:

- The `content` page. Just like what we do last week: inserting `React Component` into github's pages. Making implementation of inserting components such as buttons without introducing a library is not a good decision.
- The `popup` page. When user clicks the icon on the top menu, we can display a page to allow him to modify the configuration quickly.
![image](https://user-images.githubusercontent.com/20047907/111181058-8bd79380-85e8-11eb-9286-054a8802270b.png)
- The `options` page. Users can modify all the configuration items when right-click the icon and enter a stand-alone page. We can show a lot of information here and provide services that can't be made on github's pages.  
![image](https://user-images.githubusercontent.com/20047907/111181243-bc1f3200-85e8-11eb-8470-c71a9846b3c6.png)

Here are two perfect choices, I prefer `Fluent-UI` personally: 

### **1. Fluent-UI**
https://developer.microsoft.com/zh-CN/fluentui#/controls/web/button

![20210315232332](https://user-images.githubusercontent.com/20047907/111177860-97758b00-85e5-11eb-8593-384488542146.png)

### **2. Antd**
https://3x.ant.design/components/button-cn/

![20210315232341](https://user-images.githubusercontent.com/20047907/111177892-9e040280-85e5-11eb-88a6-0846255f3dcd.png)

**Comment by heming6666** [comment]
Great! Thank you @LiuChangFreeman for raising this discussion. 

I think both are good for me. I would pick `Fluent-UI`.

**Comment by frank-zsy** [comment]
I think `Fluent-UI` is more like a geek style and `Antd` is more like business style. I like `Fluent-UI` better than `Antd`.

**Comment by heming6666** [comment]
We have selected `Fluent-UI` as our UI library. Refer to https://github.com/hypertrons/hypertrons-crx/blob/master/src/components/OptionsPage/index.tsx for the usage.

Closed.
