### ISSUE TITLE
[Bug] Click 'Perceptor' button then flash back to 'Insights' button swiftly when accessing a repo

### ISSUE THREAD

**Issue by Wind-Gone** [hypertrons/hypertrons-crx#591]
### Current Behavior

When I click the 'Perceptor' button in the menu bar, it quickly flash back to the 'Insights' and display the insights content. After a few seconds, it may return to normal.

### Expected Behavior

It should display the contents under 'Perceptor' menu bar the first time 😊

### Environment

```markdown
- OS: Apple M1 Pro
- Browser: Google Chrome Version 110.0.5481.100（Stable） (arm64)
```

**Comment by tyn1998** [comment]
Hi @Wind-Gone, thank you for reporting the issue. The issue described does exist and I have experienced it several times.

Actually we have a PR(#589) working on this. Hopefully it will solve the issue :)

**Comment by Wind-Gone** [comment]
ok, thanks for your reply. We are looking to forward to seeing it resloved😊.

**Comment by wxharry** [comment]
Hi, @Wind-Gone thank you for the issue. Could you provide the version number of your hypercrx extension?

**Comment by Wind-Gone** [comment]
> Hi, @Wind-Gone thank you for the issue. Could you provide the version number of your hypercrx extension?

Hi, @wxharry , its 1.8.4

**Comment by tyn1998** [comment]
#589 didn't solve this problem and I found that rgh doesn't make their Bugs Tab feature perfect either:

https://user-images.githubusercontent.com/32434520/233067710-521785ee-28f0-477d-91ec-b8b636c422c9.mov

It is inevitable (sorry to admit).
