### ISSUE TITLE
[Bug] the network will crash if no edge provided

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#593]
### Version

1.8.4

### Current Behavior

If `edges` is `[]`:

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/32434520/221875506-1a947ed3-8f34-4cff-855b-eb4f8d5b811a.png">

then clicking the network chart with empty edges will cause crash:

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/32434520/221875868-68987f39-39e3-40c1-9f0c-6f407beae44a.png">

### Expected Behavior

Related code:

https://github.com/hypertrons/hypertrons-crx/blob/37ee797c269f0f5915c3a12c7996f560da698817/src/components/Graph.tsx#L44-L55

### Environment

```markdown
- OS: whatever
- Browser: whatever
```

### Any additional comments?

I found this bug when exploring OpenGalaxy. Put the following code at the beginning of `generateEdges` should works:

```javascript
    if (edges.length === 0) {
      return [];
    }
```

**Comment by wj23027** [comment]
I can fix it~
