### ISSUE TITLE
[Bug] Activity, OpenRank, Participants become all 0

### ISSUE THREAD

**Issue by TommyLemon** [hypertrons/hypertrons-crx#595]
### Version

1.8.4
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5738175/222138033-b27de930-e73e-4ec9-8be5-95234a4ea6a9.png">

### Current Behavior

[Bug] Activity, OpenRank, Participants become all 0

https://github.com/Tencent/APIJSON
<img width="671" alt="image" src="https://user-images.githubusercontent.com/5738175/222137084-4a9d6880-91b4-47dd-8e8f-64123d8c8e50.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/5738175/222137139-881b33e2-9759-4ba5-beed-e94bd7215641.png">

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/5738175/222138656-3308c392-ff74-4649-aa25-afd2cbccb017.png">
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/5738175/222138865-8ed5dc94-35ad-4585-b1af-22ac448fa0bb.png">

### Expected Behavior

Show correct numbers

### Environment

```markdown
- OS: MacOS Ventura 13.0 (22A8380)
- Browser: Chrome 109.0.5414.119 (Official Build) (arm64)
```

**Comment by frank-zsy** [comment]
Yes, I will release the data as soon as possible but still it is at least on the 2nd day of every month. There should be a mechanism to handle the data switch.

Actually there is a meta file like [this](https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json) to indicate when the data last updated, you can use this file to check if the data of current month has been updated or not.

**Comment by TommyLemon** [comment]
@tyn1998 the issue appeared again in recent 2 days
https://github.com/Tencent/APIJSON
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/5738175/228513698-90dd8e92-959c-45e3-b03e-48a1ab44772d.png">

**Comment by tyn1998** [comment]
Related: #632 

Fixing it...
