### ISSUE TITLE
[Feature] I would like a new chat bot feature for Hypercrx

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#599]
### Description

Hi, Hypercrx community. As ChatGPT is on fire right now, I think we can add a new feature in Hypercrx which is a chat bot for an open source project.

A popup chat box can be embedded into the pages which has a model for their documents.

I can provide chat service for the chatting.

Here is an example of the chat box:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/8512426/224477523-3642f002-bb95-46e1-b2fe-0d3782dbfca1.png">

**Comment by tyn1998** [comment]
Great idea!

Learning and playing with [Wolox/react-chat-widget](https://github.com/Wolox/react-chat-widget).
