### ISSUE TITLE
[feature] Add i18n support for different languages

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#60]
Till now, we start to implement components which may be viewed by people using different languages.
I think the `i18n` support should be introduced before anything else. Does someone have any ideas about this? 
https://developer.chrome.com/docs/extensions/reference/i18n/
![image](https://user-images.githubusercontent.com/20047907/111258352-c75d7680-8657-11eb-957e-d1a4e6401114.png)

**Comment by heming6666** [comment]
fixed by #63 .
