### ISSUE TITLE
[Bug] a false positive case of `isPerceptor`

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#603]
### Version

1.8.4

### Current Behavior

https://user-images.githubusercontent.com/32434520/224598207-2dee9ae1-1a5f-46db-9374-9809cc70ff5d.mov

### Expected Behavior

Not all urls containing 'perceptor' is Perceptor!

### Environment

```markdown
- OS: whatever
- Browser: whatever
```

### Any additional comments?

Related code:

https://github.com/hypertrons/hypertrons-crx/blob/37ee797c269f0f5915c3a12c7996f560da698817/src/utils/utils.ts#L63-L65

**Comment by andyhuang18** [comment]
I can try this issue~
