### ISSUE TITLE
[Style] red bubble showing every time may be annoying 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#611]
### Description

<img width="133" alt="image" src="https://user-images.githubusercontent.com/32434520/225311155-99592436-30df-47cd-9332-877ec3de7464.png">

**Comment by will-ww** [comment]
不过有个好处就是，然我一眼就可以看到它~

**Comment by STRRL** [comment]
+1 

The floating button just makes sense, please do NOT make the unread bubble on the corner.
