### ISSUE TITLE
[Feature] enable emoji picker in OSS-GPT chat widget

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#613]
### Description

Reference: https://github.com/hypertrons/hypertrons-crx/pull/606#issuecomment-1469242489

The style of the emoji picker should be fine tuned for both themes.

**Comment by andyhuang18** [comment]
[](url)The problem I found was that when I was in dark mode, the automatically loaded ```emoji-mart``` module was still in light mode, as shown in the image.

![1](https://user-images.githubusercontent.com/50283262/225556277-1331bc8d-b4f6-4379-a75a-e83588da43e7.png)

**Comment by andyhuang18** [comment]
So now the problem is that ```rcw``` recognizes the change in the github theme, but the ```emoji-mart``` in it does not recognize the change.

**Comment by tyn1998** [comment]
Hi @andyhuang18, I'm trying [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver) and I believe it can be a solution:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/32434520/225569535-a077c3c5-4442-41c2-bdc3-e7bce423065c.png">

**Comment by andyhuang18** [comment]
It is a new continent for me ！Thanks，let me have a look~

**Comment by tyn1998** [comment]
Hi, @andyhuang18, you can refer to code in [this PR](https://github.com/tyn1998/hypertrons-crx/pull/2) :)

**Comment by andyhuang18** [comment]
Sure : )

**Comment by tyn1998** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/32434520/225612397-7acc9c1f-7f32-45b3-8844-e9bb9defed47.png">

Maybe we can also make the widget higher to display more content~

**Comment by tyn1998** [comment]
closed via #622
