### ISSUE TITLE
[Style] add avatar for OSS-GPT chat bot 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#616]
### Description

We can add an avatar for OSS-GPT chat bot like this:

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/32434520/225514062-ed7b6607-51d1-43e9-b879-571400896b1c.png">

Reference: https://github.com/Wolox/react-chat-widget#api

Hi, @Zzzzzhuzhiwei, could you help on this?

**Comment by Zzzzzhuzhiwei** [comment]
I would like to try it !   

/self-assign
