### ISSUE TITLE
[discussion][cache] Do we need to develop a back-end service?

### ISSUE THREAD

**Issue by wengzhenjie** [hypertrons/hypertrons-crx#62]
According to the document of aliyun CDN(https://help.aliyun.com/document_detail/122172.html?spm=a2c4g.11186623.6.552.3d2c66f7tplHE4), it may require a back-end service? Do we have a better choice?@heming6666

**Comment by frank-zsy** [comment]
Actually we can directly use OSS + CDN to provide static resource service. While you attach the OSS directory to ECS you can use it like a local storage and just use CDN to boost the visit. The documentation can be found here: [https://help.aliyun.com/document_detail/173722.html](https://help.aliyun.com/document_detail/173722.html).

**Comment by LiuChangFreeman** [comment]
Just use OSS，CDN doesn't always need a back-end service.

**Comment by frank-zsy** [comment]
Yes, actually we did not use CDN for our insight report too and only use OSS to download the PDF file. Only if we have a lot of requests and we want the data transfer really fast, then we can enable CDN for the OSS.

**Comment by wengzhenjie** [comment]
Thanks! I see.

**Comment by wengzhenjie** [comment]
I develop the [`crx-backend`](https://code.kfcoding.com/ZhenjieWeng/crx_weekly/tree/master) component. 
This component has some configurations.

- The network data update cycle is once a week.
- The network data time range is 180 days.

This component provides four types of network data.
- `Repo-Repo network` shows the connection relationships for the 10 repos most relevant to the current repo. For example, you can see this [url](https://hypertrons.oss-cn-shanghai.aliyuncs.com/repo/X-lab2017/github-analysis-report.json) to get one repo data.
- `Repo-Actor network` shows the connection relationships of the 10 most active developers in the current repo.For example, you can see this [url](https://hypertrons.oss-cn-shanghai.aliyuncs.com/repo/X-lab2017/github-analysis-report_top.json) to get one repo data.
- `Actor-Actor network` shows the connection relationships for the 10 developers most relevant to the current developer. For example, you can see this [url](https://hypertrons.oss-cn-shanghai.aliyuncs.com/actor/heming6666.json) to get one developer data.
- `Actor-Repo network` shows the connections of the 10 most active repos in which the developer is currently involved. For example, you can see this [url](https://hypertrons.oss-cn-shanghai.aliyuncs.com/actor/heming6666_top.json) to get one developer data.

The calculation formula of network relationship can be referred to [here](http://oss.x-lab.info/github-insight-report-2020.pdf)

**Comment by heming6666** [comment]
Great job! Thanks @wengzhenjie .

**Comment by wengzhenjie** [comment]
I add dockerfile to [`crx-backend`](https://code.kfcoding.com/ZhenjieWeng/crx_weekly/tree/crx-docker) component for supporting serverless.
For network data, I set 30 as threshold for topN. You can see new data situation in urls. In addition, I make neighbors of `Repo-Repo network` and `Actor-Actor network` have edges.

**Comment by heming6666** [comment]
Done.
