### ISSUE TITLE
[Bug] awkward behavior after input text exceeds the input box

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#620]
### Version

1.8.6

### Current Behavior

https://user-images.githubusercontent.com/32434520/225541511-91a256f9-6ad5-4e6f-b1af-5d50ffaafbc9.mov

### Expected Behavior

should wrap in a new line.

### Environment

```markdown
- OS: macOS
- Browser: Chrome
```

**Comment by wxharry** [comment]
I believe there's a bug regarding the `resizable` attribute from "react-chat-widget". I think we should disable `resizable` for now.

**Comment by tyn1998** [comment]
@wxharry thank you for figuring it a little bit out but in my view, just let us leave it as it is now. It's not a prior issue so maybe we can fix it later.

**Comment by stealth-bombeer** [comment]
> @wxharry thank you for figuring it a little bit out but in my view, just let us leave it as it is now. It's not a prior issue so maybe we can fix it later.

This issue is some what linked to #624 ,i've uploaded a clip describing solution under the issue can anyone here check if i'm on the right track,I beleive once #624 is resolved we can be able to figure this one too 😄
