### ISSUE TITLE
[Bug] Abnormal width variation of OSS-GPT chat widget when selecting text in it.

### ISSUE THREAD

**Issue by wj23027** [hypertrons/hypertrons-crx#624]
### Version

1.8.6

### Current Behavior

When I want to select a piece of text, the width of OSS-GPT chat widget changes as I move the mouse.

https://user-images.githubusercontent.com/62098023/225647575-808805bc-fd6b-45b3-b8f9-10a728c7559d.mp4

### Expected Behavior

The width of OSS-GPT chat widget should  be variable only when its edge is selected.

### Environment

```markdown
- OS: Windows
- Browser: whatever
```

**Comment by tyn1998** [comment]
Hi @stealth-bombeer, thanks for your experiment on this issue. Would you mind creating a draft PR so we can learn how exactly you solve this?

**Comment by stealth-bombeer** [comment]
hey @tyn1998 ,i've fixed the ambiguity regarding the width variation 

https://user-images.githubusercontent.com/96366867/233825914-2d7132b7-1f99-4b6a-8c0f-9601e2ca9875.mp4

can you please tell me in which branch it is to be merged v1.9.0 or master so I can raise a PR accordingly

**Comment by tyn1998** [comment]
Great job! @stealth-bombeer

Please create a PR to v1.9.0 and I will have a review.
