### ISSUE TITLE
[Proposal] Switch menbotics to open-digger-bot 

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#627]
### Description

Right now, hypertrons-crx repo uses menbotics as the collaboration app, but this repo is also the only repo that uses menbotics in X-lab right now. All other repos use open-digger-bot as the collaboration app.

With open-digger-bot becomes public and serve more and more repos like KubeVela, OpenYurt, Sealer, I think we can use open-digger-bot to serve hypertrons-crx repo as well and menbotics bot could retire for now.

**Comment by tyn1998** [comment]
Agree!

**Comment by tyn1998** [comment]
Hi @frank-zsy, any progress?

Will the new bot be called "open-digger-bot"? Why not "hypercrx-bot"?

**Comment by wxharry** [comment]
> open-digger-bot

I think there is a bot called "open-digger-bot" used by opendigger. https://github.com/apps/open-digger-bot. And we might need some instructions on how to immigrate the bot to `hypercrx`

**Comment by tyn1998** [comment]
Hello @frank-zsy , do you have any migration plans?

**Comment by frank-zsy** [comment]
@tyn1998 The migration is quite simple, just uninstall menbotics and install open-digger-bot, all is set. But recently when open-digger-bot serves more than 200 repos, I found there are some unexpected behaviors on the backend, includes not merge PR automatically and maybe some error about weekly report issue. I will check on this later.

**Comment by tyn1998** [comment]
The app link: https://github.com/apps/open-digger-bot

<img width="1613" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/3a82ec69-071e-4702-86e2-181bbc1f892d">

Done!

**Comment by tyn1998** [comment]
> includes not merge PR automatically

e.g. https://github.com/hypertrons/hypertrons-crx/pull/727#pullrequestreview-1639083776

@frank-zsy I also want to know if `.github/hypertron.json` is still necessary after we switch to open-digger-bot? If not, we can remove it.

**Comment by tyn1998** [comment]
> But recently when open-digger-bot serves more than 200 repos, I found there are some unexpected behaviors on the backend, includes not merge PR automatically and maybe some error about weekly report issue.

@frank-zsy Confirmed 😆
