### ISSUE TITLE
[Bug] Components next to repo name cannot display data 

### ISSUE THREAD

**Issue by xgdyp** [hypertrons/hypertrons-crx#632]
### Current Behavior

![image](https://user-images.githubusercontent.com/37795442/228411831-d527efa3-2dd9-4126-a260-0865f48e1d18.png)
It displays 0.

### Environment

```markdown
- OS:Mac M1
- Browser:Chrome
```

### Any additional comments?

I check other repos, there's no data too.

**Comment by tyn1998** [comment]
We didn't know well about `Date.prototype.setMonth` 😢 

> Today is the 31st of January. When you d.setMonth(1); you are trying to set the date to the 31st of February. Since this date doesn't exist, it falls over to the 3rd of March.
> 
> Set the whole date when you initialise the object, don't try to change it piecemeal.

reference: https://stackoverflow.com/a/21490429/10369621

**Comment by xgdyp** [comment]
Hi yorknan, do you mean this is caused by `Date`?

**Comment by tyn1998** [comment]
> Hi yorknan, do you mean this is caused by `Date`?

Lam Tang here. 😄 The issue is caused by our misuse of `Date.prototype.setMonth`. Will fix it ASAP.

/self-assign
