### ISSUE TITLE
[Bug] Perceptor tab highlight issue in the developing v1.9.0

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#636]
### Version

v1.9.0 (developing)

### Current Behavior

https://user-images.githubusercontent.com/32434520/229271367-9f6e833a-0049-4792-8ee3-80637814b389.mov

### Expected Behavior

Each time only one tab should be highlighted.

### Environment

```markdown
- OS: macOS
- Browser: Chrome
```

**Comment by wxharry** [comment]
My bad. While changing the tabs from side bar, the perceptor tab will reload and copy a highlighted insight tab. Remove the highlight class and attributes should fix this.
