### ISSUE TITLE
[question] how to get the number of developers collaborated with a certain developer in the project?

### ISSUE THREAD

**Issue by OSZhouYe** [hypertrons/hypertrons-crx#641]
### Description

你好，请问怎么获取项目内与开发者有协作关系的开发者数量的数据呢？有没有这些数据的接口呢？

**Comment by zhicheng-ning** [comment]
可以参考 Network 这一块儿的数据

- https://github.com/X-lab2017/open-digger#for-repos

![image](https://user-images.githubusercontent.com/39022409/229435733-34f76df7-4adf-44fc-a7fa-b86be216855b.png)
