### ISSUE TITLE
[question] What's the definition of the closeness between developers?

### ISSUE THREAD

**Issue by OSZhouYe** [hypertrons/hypertrons-crx#643]
### Description

你好，请问一下开发者间联系的紧密程度是怎么定义的？或者它的计算公式是怎样的呢？
另外项目之间的紧密程度呢？

**Comment by tyn1998** [comment]
粗略地说，如果两个开发者在同一个Issue、PR下评论，就认为他们之间有联系，这种情况越多，联系越紧密；项目之间的联系是通过开发者建立的，如果一个开发者同时在项目A和项目B有活动，那么会认为项目A和B有联系，这种情况越多，两个项目间的联系越大。

具体请见 OpenDigger 的[指标清单](https://github.com/X-lab2017/open-digger#metrics-or-indices-usage)。另外还有几篇博客可以参考：

- https://blog.frankzhao.cn/how_to_measure_open_source_1/

**Comment by will-ww** [comment]
紧密度，其实可以作为新的指标来建设的，借鉴一些复杂网络或图数据的技术，然后放入 OpenDigger 中~
