### ISSUE TITLE
[Feature] label studio平台，如何设计层次分类

### ISSUE THREAD

**Issue by fuqiang-benz** [hypertrons/hypertrons-crx#645]
### Description

![image](https://user-images.githubusercontent.com/64388539/230884786-1279647d-48e6-4b3d-9c13-823a0900c966.png)

**Comment by tyn1998** [comment]
Hi @fuqiang-benz, would you mind providing more context? Based on your description I cannot give your help.

**Comment by tyn1998** [comment]
Hi @fuqiang-benz, I will close this issue. If you want to add more information, please feel free to reopen it.
