### ISSUE TITLE
[improvement] CSS styles update needed to ensure aligned

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#649]
### Description

Some styles of the charts are not correctly aligned with its title and the content. As illustrated in the screenshot of the `Developer Collaboration Network`, the styles may not be well set. We don't have a detailed UI design for that, so as long as it is compatible with Github, it will fine.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/39271899/232253530-d29ae46f-3f63-40aa-bec2-d6b586985175.png">

**Comment by stealth-bombeer** [comment]
Greetings @wxharry ,I have understood the issues with the alignment can I try resolving it

**Comment by wxharry** [comment]
> Greetings @wxharry ,I have understood the issues with the alignment can I try resolving it

feel free to assign this issue to yourself, using `/self-assign` commands

**Comment by stealth-bombeer** [comment]
@wxharry ,i have created pull request can you took a look,when you get free
