### ISSUE TITLE
[Feature] Add CI to the project 

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons-crx#65]
As mentioned in [#63](https://github.com/hypertrons/hypertrons-crx/pull/63), we can add some CI features  to make our project more feasible and improve the test experience.
- [x] Compile the Chrome extension to a crx file and attach to the PR, so we can download the file and manually install on our own browser by choosing `load extension from local folder`. The `.crx` file is only for test but not distribution.
- [ ] `.md` file linter.

**Comment by LiuChangFreeman** [comment]
The build && pre-release CI has been accomplished. https://github.com/hypertrons/hypertrons-crx/pull/66
