### ISSUE TITLE
[Feature] single source of truth for feature list

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#657]
Yeah their README will be treated as some kind of source code and parsed to generate a feature list then used by other code. It's a great design with which we need only to maintain a feature list in one place and consume them anywhere.

vote +1 :)

_Originally posted by @tyn1998 in https://github.com/hypertrons/hypertrons-crx/issues/474#issuecomment-1517906304_

**Comment by wxharry** [comment]
A difference between our desgin and theirs is that they don't have locale but we do. So they can use the readme to describe their features, but we will need to make sure the contents are consistent
