### ISSUE TITLE
[Feature] to add a 'Change View' button in the graphs in Perceptor

### ISSUE THREAD

**Issue by DEVelooper29** [hypertrons/hypertrons-crx#661]
### Description

Adding a 'Change View' button in the Perceptor graphs of Project Correlation Network and Active Developer Collaboration Network will be really helpful for users to analyze the graphs from different angles and views. Every time they click the button, the view will change and the users can have a variety of views from which they can select the most suitable one for them.

Below is the video for that.

https://user-images.githubusercontent.com/101932255/234202408-9607098f-bd42-49c9-a902-e22f59566b5d.mp4

**Comment by DEVelooper29** [comment]
![Screenshot (2896)](https://user-images.githubusercontent.com/101932255/234260139-023ebeb8-733c-4864-8da0-ca886e70081b.png)
Will this styling for the button work?

**Comment by DEVelooper29** [comment]
![Screenshot (2897)](https://user-images.githubusercontent.com/101932255/234260359-9ed3601f-e084-4b7a-88e3-c222a93b0785.png)
Will this styling for the button work?

**Comment by tyn1998** [comment]
Hi @DEVelooper29, thanks for your idea :)

I hold a similar idea as @wxharry does. Changing the graph's layout doesn't make huge difference in my view. While other [ECharts series](https://echarts.apache.org/examples/en/index.html#chart-type-line) like bar chart can be tried out. One data in different forms makes more sense to me.

**Comment by DEVelooper29** [comment]
Thank you for your responses. I'll be happy to contribute to this issue after all the necessary discussions are done.
