### ISSUE TITLE
[improvement]  Default alert of Github message obscure the `Fork` chart

### ISSUE THREAD

**Issue by andyhuang18** [hypertrons/hypertrons-crx#663]
### Description

When hovering the mouse over the `Fork` button, github's default alert message blocks the chart. The user cannot see the full chart at first glance. The specific message is shown in the following figure:

![Fork_problem](https://user-images.githubusercontent.com/50283262/234475936-925aec83-1433-4727-96fd-8662948baf9d.png)

**Comment by tyn1998** [comment]
Yeah, it is a little bit annoying.

**Comment by wxharry** [comment]
Is there a way to block that tooltip. It doesn't give any critical information.

**Comment by stealth-bombeer** [comment]
> Is there a way to block that tooltip. It doesn't give any critical information.

what if we set pointer events for fork tooltip to none,i think this would help us in some way .....

**Comment by pranavshuklaa** [comment]
Thank you for bringing this problem to my attention! I have devised a solution and tested it on my local setup. During my research, I attempted to find a way to disable the default GitHub fork popup, but unfortunately, I was unable to discover a method to stop it entirely. The available solutions only suggested hiding all popups when hovering over the button, but this approach would also cause the fork chart to disappear, which is not desirable.

However, I strongly believe that it is crucial to break down significant issues into smaller, manageable problems until we can completely resolve them! 😀

Currently, the chart appears directly below the button and is being obscured by the default GitHub message. My proposed solution is to relocate the chart to the left side of the message, similar to how the star chart is displayed!

![1122TE](https://github.com/hypertrons/hypertrons-crx/assets/112813390/4be48f0f-d071-4231-9e97-a8f2590e2514)

Here are the advantages of this approach:

1. By implementing this change, the default popup will occupy minimal space, and the chart's title will be clearly visible. Previously, it was obstructing 100 tiny blocks, whereas now it will only cover 25 tiny blocks!
2. Although this is not the final solution as it still occupies some space, I believe we should proceed with shifting the block to the left side of the fork button until we find a solution to completely eliminate this issue.

I have successfully implemented this solution on my local setup by changing the place to 'left' from 'bottom'. If you think it is correct, shall I proceed with opening a pull request?

**Comment by tyn1998** [comment]
> During my research, I attempted to find a way to disable the default GitHub fork popup, but unfortunately, there are no good methods to stop it entirely.

Ahha, I did the same thing before. Hope we can finally find a perfect way to address this problem :)

> I have successfully implemented this solution on my local setup by changing the place to 'left' from 'bottom'. If you think it is correct, shall I proceed with opening a pull request?

Your solution LGTM. What do you think @wxharry ?

**Comment by wxharry** [comment]
Hey @pranavshuklaa! Thanks for the research and contribution. Your solution looks good to me. Welcome to create a pr to show us your work.

Also, please share any links you think is useful to this issue. Let's make your work visible!

**Comment by andyhuang18** [comment]
My point is that blocking 100 blocks and blocking 25 blocks are actually the same for the user experience, both will hinder the user from browsing the chart. My suggestion is that the chart can be moved down so that the github prompt information and the chart do not overlap. As shown in the picture below. 

![image](https://github.com/hypertrons/hypertrons-crx/assets/50283262/f0bf62b7-1104-46bc-b4ce-e5a7bdd88b21)

**Comment by wxharry** [comment]
> My point is that blocking 100 blocks and blocking 25 blocks are actually the same for the user experience, both will hinder the user from browsing the chart. My suggestion is that the chart can be moved down so that the github prompt information and the chart do not overlap. As shown in the picture below.

You've got a point. However, i don't think we could simply move it down without changing the ui design which could make it complicated.

Also, just found that in the new github design, the fork and star buttons are in the code tab. Why not move the charts to down to the side bar like mentioned in #664.


<img width="1397" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/a1878630-cf35-4a7d-83c1-c69cedf3ee5b">

**Comment by pranavshuklaa** [comment]
> Hey @pranavshuklaa! Thanks for the research and contribution. Your solution looks good to me. Welcome to create a pr to show us your work.
> 
> Also, please share any link you think is useful to this issue. Let's make your work visible!

Just wanted to re-confirm,  
Shall i open a pr for the improvement or shall i wait , because of the current discussion going on.

**Comment by tyn1998** [comment]
@pranavshuklaa You are welcomed to open a PR for the proposed modification :)
