### ISSUE TITLE
[improvement] move tooltips to sidebar

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#664]
### Description

Hi, I am thinking if we could move the tooltips to the sidebar, indicated in the screenshot below:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/39271899/234602867-431a94bd-99f3-4e19-8491-febe3d80e4e5.png">

On the good side, all the charts could have a unified section for demonstration, nothing annoying would popup if users just want to click on the button. Meanwhile, I think it would be better if we could show the metrics name rather than an icon only. Plus, I just watch the new design of the aggrestion feature discussed #662. The top could be overcrowded. It could raise problems like need to implement ways to hide some of them.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/39271899/234604640-19162e89-6b3a-4237-bfdd-17fd6517fcfc.png">

However, on the bad side. As we move to the sidebar, it will definitely decrease the times users trigger the charts.

What would you say Lam? @tyn1998

**Comment by tyn1998** [comment]
Hi @wxharry, thanks for your suggestion and I totally get your idea. But I think it is not an ideal solution considering that the sidebar only appears in the Code tab while the header area is always there no matter what tab the user is visiting.

> Plus, I just watch the new design of the aggrestion feature discussed #662. The top could be overcrowded. It could raise problems like need to implement ways to hide some of them.

For this consideration, we can easily overcome it by [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries). If the width is small, we can remove button text with only an icon left.

What do you think?

**Comment by wxharry** [comment]
FYI, as I switch to the beta version view, the top section is even narrower

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/39271899/235306652-5d60df44-ff77-4e34-b220-f377a655a362.png">

**Comment by wxharry** [comment]
Shall we close this comment since we don't have plans to make changes for now?

**Comment by tyn1998** [comment]
@wxharry Of course :)
