### ISSUE TITLE
[Chore] restructure the file tree and refactor code accordingly 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#668]
### Description

- [ ] remove all unused code, such as files, functions, variables, etc.
- [ ] functions in `src/utils` -> `src/helpers`, and one function one file

<img width="1502" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/e4051292-aaf9-4d2d-b914-13eb318b9de9">

After this task is finished, we can release v1.9.0, finally.

**Comment by lhbvvvvv** [comment]
In `src/utils` there is a file `utils.ts` which contains many functions. Do I need to split it into multiple files? @tyn1998

**Comment by tyn1998** [comment]
@lhbvvvvv Yes :)

**Comment by tyn1998** [comment]
closed via #672
