### ISSUE TITLE
[Feature] i18n, but with a good library 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#669]
### Description

 The current used DIY i18n support is indeed embarrassing:

https://github.com/hypertrons/hypertrons-crx/blob/2220a5bffe0e535539ed5c90c8d77ce722935cd5/src/utils/utils.ts#L54-L57

We should take a research on related libraries then switch to a good one. Also remove keys no longer used.

**Comment by wxharry** [comment]
Agree. It is unnecessary for each feature to fetch the locale settings to get message. And things like that would make coding harder
