### ISSUE TITLE
[Bug] The time display on the ossgpt dialog box is incorrect

### ISSUE THREAD

**Issue by wj23027** [hypertrons/hypertrons-crx#678]
### Version

1.8.8

### Current Behavior

The time display on the OSS-GPT dialog box is incorrect. The time is actually 16:03, but it shows 04:03.

![image](https://github.com/hypertrons/hypertrons-crx/assets/62098023/33bf89ea-cb42-4b99-8688-9888bfff8280)

### Environment

```markdown
- OS:Windows
- Browser:edge
```

**Comment by wxharry** [comment]
Hi @wj23027, could you give us more information on this issue? It works fine on my laptop.

<img width="593" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/d54bd227-5e0c-403b-99db-f9c34b76c3b5">

**Comment by wj23027** [comment]
> Hi @wj23027, could you give us more information on this issue? It works fine on my laptop.
> 
This bug may not appear until after 13 o 'clock, and the display time was 12 hours earlier than the current time. The bug appeared on both of my machines.

![image](https://github.com/hypertrons/hypertrons-crx/assets/62098023/4105441b-6751-43d4-bea3-35192523a31d)

**Comment by wxharry** [comment]
> This bug may not appear until after 13 o 'clock, and the display time was 12 hours earlier than the current time. The bug appeared on both of my machines.

Gotcha. Looks like the current time displays in 12-hour clock without am/pm. this issue might help https://github.com/Wolox/react-chat-widget/issues/133

**Comment by stealth-bombeer** [comment]
Maybe, we can get the timestamp element and set the html as the current time, I'll give it a try

**Comment by wxharry** [comment]
Hi @stealth-bombeer, how's everything? need help?

**Comment by tyn1998** [comment]
> > This bug may not appear until after 13 o 'clock, and the display time was 12 hours earlier than the current time. The bug appeared on both of my machines.
> 
> Gotcha. Looks like the current time displays in 12-hour clock without am/pm. this issue might help [Wolox/react-chat-widget#133](https://github.com/Wolox/react-chat-widget/issues/133)

I was searching for relevant content in their issues, and I found a method that seems to be effective. Then suddenly I noticed that Harry has already mentioned that issue in this issue. Haha!

The provided solution seems simple, do you have interest in solving it? @wj23027
