### ISSUE TITLE
[feature] Maybe we can add an OSChain (open source chain) view 

### ISSUE THREAD

**Issue by will-ww** [hypertrons/hypertrons-crx#68]
As inspired by open source software chain project with iscas, I think the oss chain graph is also a straitforword way to show the relationship of repos.  Although this kind of information is  not rich enough, maybe we can do some case study to demo the usefulness of this approach. @heming6666 @sunqing

**Comment by heming6666** [comment]
This is a great idea and maybe this feature can be used as an idea of `Summer 2021 of Open Source Promotion Plan`. 

Releated issue: #103

**Comment by tyn1998** [comment]
Thanks for your discussion. Maybe we can reopen the issue in future.
