### ISSUE TITLE
[Bug] chart broken when I specify third person pronoun in my profile.

### ISSUE THREAD

**Issue by zhicheng-ning** [hypertrons/hypertrons-crx#684]
### Version

1.9.0

### Current Behavior

https://github.com/hypertrons/hypertrons-crx/assets/39022409/fb65d9dd-d00d-4ea0-9a8c-c9a63846a269

### Environment

```markdown
- OS: Win11
- Browser: Chrome
```

**Comment by andyhuang18** [comment]
Thanks for reminding! I will fix it ASAP.
