### ISSUE TITLE
[Bug] multiple header-labels are added when creating a new issue without a template

### ISSUE THREAD

**Issue by stevending1st** [hypertrons/hypertrons-crx#686]
### Version

1.9.0

### Current Behavior

When a new issue is created from the created issue page and the repository does not have a configuration template, multiple header-label are added to the form page.

### Expected Behavior

only one header-label are added to the form page.

### Environment

```markdown
- OS: Win11
- Browser: Edge
```

**Comment by tyn1998** [comment]
<img width="1583" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/ea15ae4f-7ef8-4434-b95b-04e4735c12b1">

Hi @stevending1st, sorry for the late reply. The issue you mentioned might influence other features, so #682 will be pending for a while until we find the root cause for this bug.

Much thanks for your bug report!

**Comment by tyn1998** [comment]
This issue can be reproduced by another way:

<img width="1357" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/26a41b90-16c2-4c7b-84b8-b05d624377a6">

<img width="1359" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/1026702c-2e0c-4258-9573-6cf2628e9bb1">

**Comment by Zzzzzhuzhiwei** [comment]
I just encountered the same problem several times. When I open a repository and immediately click ‘issue’ before loading it, the following situation will occur：
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/3e2ff03a-e512-4578-b4c9-0ff0e13f2fd2)
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/92d42dc8-be29-4b40-80d6-34a4e2a9e0ac)
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/55e3d559-480f-4d78-851f-5d2623220739)
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/2e705458-3ded-47f5-9dfc-eac5fb7d2d8e)
