### ISSUE TITLE
[Feature] activity-racing-bars

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#687]
_Originally posted by @tyn1998 in https://github.com/hypertrons/hypertrons-crx/issues/348#issuecomment-1549647475_

@andyhuang18
            
Since the data for `activity-racing-bars` is ready for a while, we can implement the fancy feature now. I wrote a demo(https://github.com/X-lab2017/open-digger/pull/1292) you may refer to :)

**Comment by andyhuang18** [comment]
Copy that! I will work on it.

**Comment by tyn1998** [comment]
Any progress want to share with us :D @andyhuang18 

An early draft PR is always welcomed.

**Comment by andyhuang18** [comment]
Ok, sorry, I have been busy preparing for paper sharing recently, and I will release the Draft PR tomorrow.
