### ISSUE TITLE
[Bug] OSS-GPT only shows on Code tab

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#688]
### Version

v1.9.0

### Current Behavior

I am not sure it is a bug or not. The OSS-GPT only shows when I am on the `code` tab. Did I miss the discussion about where to show the OSS-GPT?

### Expected Behavior

OSS-GPT is always there in a repository.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by tyn1998** [comment]
@wxharry It should appear in all tabs. Are you using the brand new GitHub UI design?

**Comment by wxharry** [comment]
> @wxharry It should appear in all tabs. Are you using the brand new GitHub UI design?

Yep. So you don't have this bug on the old design, right?

**Comment by tyn1998** [comment]
Yes, the new UI seems changing a lot. We shoud do something in advance 🤔

**Comment by wxharry** [comment]
> Yes, the new UI seems changing a lot. We shoud do something in advance 🤔

Agree. we should add the ui design to the Environment in the bug report template to help understand the issue.
