### ISSUE TITLE
[Bug] features that broken after GitHub’s redesigned navigation features

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#690]
### Version

1.9.0

### Current Behavior

After enabling the new navigation features:

<img width="1718" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/2edf2670-688c-4446-9d7e-ed2e44625d68">

**Some features are broken** and they are(for now I only found one broken feature):

- [x] #688

### Expected Behavior

All features should function as normal.

### Environment

```markdown
- OS: whatever
- Browser: whatever
```

### Any additional comments?

Welcome to leave a comment to report bugs related to the redesigned navigation features.

**Comment by wxharry** [comment]
> Hi @wxharry, for now only one feature(OSS-GPT) was found having failure. Did you experience other feature failure?

No other bug detected for now.

**Comment by wxharry** [comment]
I found that the perceptor tab is missing in the new ui design. Simply switch tab from code to issue and refresh the page. The perceptor tab would disappear. Could you have a try if you could reproduce it? @tyn1998 @lhbvvvvv

**Comment by pranavshuklaa** [comment]
I noticed that the issue and pull request chart is not visible when hovered over the respective buttons . This does not happen on the main repo page , it only occurs when u shift to any other page of the repo (for example : the [issue page](https://github.com/hypertrons/hypertrons-crx/issues) ) . 
Environment : 
Os: Windows
Browser: Chrome and Edge

**Comment by wxharry** [comment]
Looks like features fail when we move to the new github ui design

**Comment by lhbvvvvv** [comment]
> I found that the perceptor tab is missing in the new ui design. Simply switch tab from code to issue and refresh the page. The perceptor tab would disappear. Could you have a try if you could reproduce it? @tyn1998 @lhbvvvvv

There is the same problem in my computer. My OS is Windows.

**Comment by tyn1998** [comment]
<img width="990" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/b6f532c6-afcf-461c-9426-67616160e17f">

No longer a new feature so now all users are using the navigation features. Good for us :)
