### ISSUE TITLE
[Improvement] How to trigger Tooltips in settings

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#692]
### Description

Currently, the tooltips in the settings are triggered directly by hovering on the title container. IMO, it is no a big problem but it would be more intuitive if we could trigger the tooltips by adding a customize icon like this [demo](https://ant.design/~demos/components-form-demo-required-mark). Or, if the tooltips is unnecessary, we could consider removing it.

<img width="658" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/d77cfcfb-cd15-4355-b119-90776faf9ce9">

**Comment by stealth-bombeer** [comment]
We can create a toggle state in options.tsx, offcourse appropriate styles can be applied to toggle button 😄 

https://github.com/hypertrons/hypertrons-crx/assets/96366867/79bf9724-2dc4-40d9-a1b1-0086c02c3dfe

Does this make sense ?

**Comment by Vlad116** [comment]
Не лучше ли сделать подсказки по иконке вопроса как вы и описывали @wxharry  Что-то подобное тому, что показано на скриншоте (только с более подходящей иконкой серой/белой). Я думаю это лучшее решение в данной случае, вножество проектов используют этот ux паттерн в своих приложениях и он будет интуитивно понятен пользователю. Так же если вам это нужно, я мог бы добавить возможность выключения тултипов (переключением чекбокса на основными настройками плагина), но думаю в этом нет особой необходимости, если он будет появляться только по наведению на иконку
![PR](https://github.com/hypertrons/hypertrons-crx/assets/32329117/a69cc20d-bc85-43bc-a941-75582b1b8875)

**Comment by Vlad116** [comment]
I have posted the PR and am waiting for edits or acceptance as you will have time to look at it @wxharry
