### ISSUE TITLE
[Style] improve styles in our project

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#693]
### Description

For most of the time, our focus is on the bugs, features, and performance. However, there are some minor style problems in the style which could be fixed while working on a related feature or serve as good first issues for those who want to participate.

Please comment below about your advice on the style in the project.

**Comment by wxharry** [comment]
We should increase the bottom margin for the last box in the settings page

Before:

<img width="675" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/d8de7891-859f-4b39-95a8-9b40a56db744">

After:

<img width="675" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/98b8abae-ee28-4c53-805e-27693eeb6b54">

**Comment by stealth-bombeer** [comment]
Hello @wxharry ,May I have a look at this ?

**Comment by wxharry** [comment]
> Hello @wxharry ,May I have a look at this ?

I am glad you are interested in this. Would you please wait for others to review and add their findings so that we could fix them at once? Thanks 😄

**Comment by Vlad116** [comment]
I'm think we also need styled setting's button in popup, now it's look default and a little bit ugly
![image](https://github.com/hypertrons/hypertrons-crx/assets/32329117/9ceb11bf-45af-4322-aba5-a44911cb7b0f)

**Comment by wxharry** [comment]
Close as mostly fixed in #790
