### ISSUE TITLE
[Discussion] What should options page contains?

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#70]
Let's take one for example:  
Normally the `options page` of an extension will provide user a list of setting items. 
But this page can also be used as a hub for various services. 
So we should make a discussion about the usage of this page. 

![image](https://user-images.githubusercontent.com/20047907/112157560-3e0ded00-8bdf-11eb-8487-9f8425d3653c.png)

**Comment by xiaoya-Esther** [comment]
Several perspectives from my point of view:

- Customized configure components for Developer Profile and Project Profile.
- We may

**Comment by xiaoya-Esther** [comment]
I have several perspectives as for now:

- Customized configure components for **Developer Profile** and **Project Profile** - we would release more components besides those two networks.
- We may also turn on premium mode after the chrome is getting more mature, and that is where the "**enable premium**" option goes.

Detailed designs may be refined according to the development process, which we can discuss further!

**Comment by xiaoya-Esther** [comment]
Here I have another example of Grammarly.
![image](https://user-images.githubusercontent.com/56542972/112290083-da142300-8cc9-11eb-9e0c-168ed564dda7.png)

**Comment by LiuChangFreeman** [comment]
> Here I have another example of Grammarly.
> ![image](https://user-images.githubusercontent.com/56542972/112290083-da142300-8cc9-11eb-9e0c-168ed564dda7.png)

That's good idea.

**Comment by heming6666** [comment]
Closed. Please reopen it when necessary.
