### ISSUE TITLE
[Feature] Add project label on page

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#711]
### Description

As implemented in https://github.com/X-lab2017/open-digger/pull/1301 , the meta file for repos exported by OpenDigger contains label data too right now.

Just like in https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json , all labels for OpenDigger is listed in the file.

So I think we can add label data to project page as well due to the meta file content, like below:

![image](https://github.com/hypertrons/hypertrons-crx/assets/8512426/80c8802b-22e4-47d1-8d4f-ee1834ec028e)

Although we have more detail to discuss, I think the idea is feasible.

**Comment by will-ww** [comment]
I think @Zzzzzhuzhiwei can look at this feature as your research interest include repo labeling and recommendation~

**Comment by tyn1998** [comment]
Hi @frank-zsy, good idea!

Just drew a draft, does it look good to you?

![image](https://github.com/hypertrons/hypertrons-crx/assets/32434520/d53ee43d-7f57-471f-9fa9-a258d8fa5ece)

**Comment by frank-zsy** [comment]
@tyn1998 Aggregate all labels into a single icon is fine too, but it will make it not that easy to see all the labels attached to current repo.

Another approach is what I draw above which is adding all labels directly on the page like below the repo name, and hover to a label should show a list with other repos/orgs with same label and users can click in the list to navigate to corresponding repos/orgs. Because I think for users maybe interested in investigating and exploring with label data like for certain technology.

**Comment by tyn1998** [comment]
> and hover to a label should show a list with other repos/orgs with same label

@frank-zsy Is there a way to get all repos/orgs by label id?

**Comment by frank-zsy** [comment]
@tyn1998 Not right now, I can add it to OpenDigger export task.

**Comment by frank-zsy** [comment]
As implemented in https://github.com/X-lab2017/open-digger/pull/1358 , the label has been exported to OSS, we can acess the label data by https://oss.x-lab.info/open_digger/labels/{label_id}.json , like https://oss.x-lab.info/open_digger/label_data/:communities/xlab/data.json
