### ISSUE TITLE
[Bug] Perceptor Tab not highlighted after refreshing

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#714]
### Current Behavior

1. go to perceptor tab
2. refresh

### Expected Behavior

Perceptor tab is highlighted after refreshing

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by tyn1998** [comment]
Reproduced. Thank you for reporting the bug @wxharry !

The issue occurs in both the old and the new UI.

<img width="1920" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/046de2ce-bae8-40ec-9f34-18d016d46ba3">

<img width="1920" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/9934474c-28ac-49dc-b305-a4b9b230a673">

**Comment by tyn1998** [comment]
The thing get worse now.


https://github.com/hypertrons/hypertrons-crx/assets/32434520/c9e7875e-1908-42e9-b2c1-ebdb15655689

**Comment by wxharry** [comment]
> ~The thing get worse now. Perceptor layout doesn't show (only happens in the new UI).~
> UPDATED: it only happens with my developing branch, sorry.
No, you are right. It is a known bug. Perceptor Tab related components won't work on the new github design.

**Comment by tyn1998** [comment]
@wxharry The issue is due to how we check if the current repo is a public repo. I have pushed [a commit](https://github.com/hypertrons/hypertrons-crx/pull/717/commits/1ffe41dc986993ec4f6e5612e0ef5767e3dc6f4c) to address this issue.

**Comment by wxharry** [comment]
Fixed
