### ISSUE TITLE
[Bug] Users charts will not be shown if they set the pronouns setting.

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#722]
### Version

1.9.0

### Current Behavior

GitHub introduced a new feature which is `Pronouns` to let users provide the pronouns of themselves. The default setting is `Don't specify`, but when a user changed the setting to a certain item like `he/him`, the user name showed in the profile page will be like `login · he/him` and then Hypercrx will use this as login to get data from OpenDigger which will cause 404 error.

Like https://github.com/thaJeztah , the activity and OpenRank charts will not be shown on the profile page.

![image](https://github.com/hypertrons/hypertrons-crx/assets/8512426/bc4ec854-16b9-4d16-8050-bf3a1bf8b763)

![image](https://github.com/hypertrons/hypertrons-crx/assets/8512426/67ad3b29-fe4f-4ba4-aac8-452e8d780bd4)

### Expected Behavior

Parse the login of current user correctly and show the charts.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by tyn1998** [comment]
Hi @frank-zsy, the issue is the same as #684 which was fixed by #685.#125 

Hello @lhbvvvvv, I think we can release a new version :)

**Comment by frank-zsy** [comment]
Sorry, I should search the issues first. Glad to see a new release to fix this.
