### ISSUE TITLE
[Feature] extract info from users' avatars to color the racing bars

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#723]
### Description

We just released v1.9.0 with a new feature "Contributors Activity Racing Bars". It is a great feature but the random colors it presents are actually a little ugly.

A good idea is to extract color info from users' avatars.

Notes: Bots have no avatars.

**Comment by wxharry** [comment]
A possible lib would be [colorthief](https://github.com/lokesh/color-thief?tab=readme-ov-file). (I didn't do the research, it is recommended by gpt and also looks like a nice project)

**Comment by tyn1998** [comment]
@wxharry I'll have a try, thank you 👍
