### ISSUE TITLE
[Refactor] refactor the Options page with antd 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#725]
### Description

<img width="1549" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/df6aafc1-48a4-4533-b527-fe0e00f08e81">

Hypercrx will introduce [antd](https://github.com/ant-design/ant-design) as the UI library. Now in the codebase only the Options page depends fluentUI, which should be refactored with antd.

**Comment by andyhuang18** [comment]
Recalling that when I started OSPP, I wanted to use fluentUI because I saw that fluentUI was used. But in the end, I chose antd and supported domestic production! !

**Comment by wxharry** [comment]
> Recalling that when I started OSPP, I wanted to use fluentUI because I saw that fluentUI was used. But in the end, I chose antd and supported domestic production! !

You made a good choice. We are planning to use antdesign in our project. We will need your help later!
