### ISSUE TITLE
[Refactor] refactor tooltips with GitHub Popover 

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#726]
### Description

<img width="1605" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/9da86b58-a3d0-42bd-82af-1129985280e6">

~Currently the react-tooltip has some issues. Since we are planning to introduce antd into the project, we may consider using [Popover](https://ant-design.antgroup.com/components/popover-cn) to replace the react-tooltip.~

The original Popover from GitHub may be imployed:

<img width="485" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/ec273b63-745b-451d-ab35-41ad5c48c1ea">

**Comment by andyhuang18** [comment]
It just so happened that I learned a lot about antd in the process of OSPP, so leave this task to me!

**Comment by wxharry** [comment]
#601 is related to this issue, please pay attention to this problem when working on antd
