### ISSUE TITLE
[Feature] Media player control for racing bar

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#729]
### Description

Currently, our racing bar chart only has a replay button, we want to add more media player control on repo activity racing bar: 

- The basic control should include Pause, Play/resume, Previous, Next besides Replay.
- Click on Pause/Play control should be able to Pause/resume the racing bar.
- Click on Previous/Next controls should be able to jump to the previous/next month of current month.
- Can go to a specific position.

**Comment by tyn1998** [comment]
And: the chart should display the bars of the latest rather earliest month before it starts to play.

**Comment by 2000wyt** [comment]
I briefly installed and experienced Hypercrx. For the Contributor Activity Racing Bar, it starts playing from the earliest time. For some projects created earlier, if users want to observe the evolution of contributor activity from a specific month, they have to wait for the chart to play until it reaches this specific time point. Do you think it is feasible to allow users to choose a specific time to start playing?

**Comment by tyn1998** [comment]
Hello @2000wyt, I'm sure the idea is feasible :)

**Comment by wxharry** [comment]
> I briefly installed and experienced Hypercrx. For the Contributor Activity Racing Bar, it starts playing from the earliest time. For some projects created earlier, if users want to observe the evolution of contributor activity from a specific month, they have to wait for the chart to play until it reaches this specific time point. Do you think it is feasible to allow users to choose a specific time to start playing?

Good idea! I will add this to the description of issue.
