### ISSUE TITLE
[Feature] Dump diagrams into small imgs and dispatch it by webapp.

### ISSUE THREAD

**Issue by TieWay59** [hypertrons/hypertrons-crx#733]
### Description

Lately, I have come up with a hypothesis: on GitHub, the need to show off is much stronger than the need to observe. It is much easier to develop a web app that produces report images than a browser plugin. And it is much less challenging to spread images on social networks than plugins. Ultimately, this kind of traffic will increase HC's visibility.

_A crazy idea made of love & admiration for @tyn1998._

> ~~最近我产生了一种猜想：在 github，show-off 的需求远大于 observe 的需求。开发一个生成报告图片 webapp 工程难度远小于浏览器插件。并且社交网络上图片扩散的难度远小于传播插件。最终，这种流量会反哺 hc 的曝光度。~~

**Comment by will-ww** [comment]
It makes sense to some extent, pls see: http://47.110.125.80

This web app is supported also by OpenDigger, and can dump diagrams and sth else interesting~

**Comment by TieWay59** [comment]
That's nice but my point is, that social media is lazy, ppl turn to see much simpler imgs for sharing :

![image](https://github.com/hypertrons/hypertrons-crx/assets/40034603/971cf7b2-2e79-4a68-a478-dfc59f606c49)

And it's very possible for developers to add img-links in their README.md from https://star-history.com/#hypertrons/hypertrons-crx&Date

![image](https://github.com/hypertrons/hypertrons-crx/assets/40034603/81fa07e7-df9d-440d-bd7d-b3d3d081ea3b)

so if we can ship small components screenshots automatically in that way, it'll be very promising. @will-ww

**Comment by tyn1998** [comment]
Hi @TieWay59, thanks for your idea and advice. There is already a [discussion](https://github.com/orgs/X-lab2017/discussions/238) for this topic, we can talk about it there.

**Comment by TieWay59** [comment]
oh, sorry to mention. They already have it:  https://twitter.com/OSSInsight/status/1694039271643169147?s=19

**Comment by wxharry** [comment]
> oh, sorry to mention. They already have it: https://twitter.com/OSSInsight/status/1694039271643169147?s=19

It is fine they've already have something similar, we are supported by OpenDigger which is our stuff.

**Comment by tyn1998** [comment]
650k Community OpenRanks are [soon](https://github.com/X-lab2017/open-wonderland/issues/311) released, I think it's time to make the idea into a real project. This issue will be closed, while we can discuss in https://github.com/orgs/X-lab2017/discussions/238 and take a first step out.
