### ISSUE TITLE
[Feature] Add configuration scheme to implement global settings

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#74]
We can save configuration in Chrome's local storage using `chrome.storage.local.set/get`, but the scheme of configuration should be decided first.  

Consider the situation:  
- The **_configuration_** should act as a global object which can be accessed everywhere in all source codes. 
- There are 4 different pages(_**content,background,options,popup**_) which doesn't share memory with each other. 
- The **_configuration_** should be intialized with default values if users haven't assigned their own choices to it.  
- The **_configuration_** should be dumped into string or json object when storaged and loaded from them when intialized.  
- The scheme of  **_configuration_** shouldn't change very frequently but can be expanded with updates easily. When updateing to a new version, users can keep their choices before. 

We need a considerate design of how to make it.

**Comment by LiuChangFreeman** [comment]
I think we can do it in this way: 
```typescript
class Settings {
  checkForUpdates: boolean | undefined;

  loadFromJson(data:{ [key: string] : any; }):void{
    if("checkForUpdates" in data){
      this.checkForUpdates=data["checkForUpdates"];
    }
    else{
      this.checkForUpdates=false;
    }
  }

  toJson():{ [key: string] : any; } {
    const result: { [key: string] : any; } = {};
    result["checkForUpdates"]=this.checkForUpdates;
    return result;
  }
}

export default Settings;
```
Intialized in some page:
```typescript
import {useState,useEffect} from 'react';
import {chromeGet,chromeSet} from '../../utils/utils'
import Settings from "../../utils/settings"

...
const [settings,setSettings]= useState(new Settings());

useEffect(() => {
  const initSettings=async ()=> {
    const obj=await chromeGet("settings");
    settings.loadFromJson(obj);
    setSettings(settings);
  }
  initSettings();
},[settings]);
...
```
Modified and storaged in another place:
```typescript
settings.checkForUpdates=checked;
setSettings(settings);
const obj=settings.toJson();
await chromeSet("settings",obj);
...
```
All key-values can be handled by adding new property to class `Settings`.

**Comment by heming6666** [comment]
Done. Thanks @LiuChangFreeman for your great work!
