### ISSUE TITLE
[bug] Duplicate numbers on the racing bar

### ISSUE THREAD

**Issue by zhaosj975** [hypertrons/hypertrons-crx#750]
### Description

As shown in the first picture，the bars  in 2021 have too many annotated numbers，this makes the chart less beautiful.
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/ddac3d2f-84f6-4809-8998-3a35e7fc2b8d)

And in the second picture, the chart doesn't show all authors.
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/699c1396-d3f7-4434-b09a-3c25a3272169)

And the loading is not in order, it is from 2022 to 2023 and then to 2021.

https://github.com/hypertrons/hypertrons-crx/assets/79428895/e2213b64-87cc-4b1e-bb15-2791e0c8accc

**Comment by tyn1998** [comment]
@zhaosj975 Thank you for reporting the issue. The bug is due to https://github.com/X-lab2017/open-digger/pull/1405

BTW, a GitHub markdown tip:

<img width="922" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/1649d851-3730-4872-adab-fb862cd10f19">

**Comment by zhaosj975** [comment]
Get it~！👍 It's very useful！ @tyn1998

**Comment by wxharry** [comment]
I got the same issue.

<img width="900" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/39271899/e8c511ab-9ed1-47bf-8739-c558f1a1f2cc">

I think it is a bug.

**Comment by tyn1998** [comment]
This is a bug that should be fixed ASAP.

/self-assign
