### ISSUE TITLE
[Bug] OSS-GPT unable to give a response

### ISSUE THREAD

**Issue by Tenth-crew** [hypertrons/hypertrons-crx#753]
### Description

When asked questions of OSS-GPT, it was almost unable to give a response, I tested the hypercrx and open digger Q&A situation is the same, how to get it to return an answer in an acceptable time

![image](https://github.com/hypertrons/hypertrons-crx/assets/68376741/ef209bd3-7ddd-4f2b-a8d7-820e328eac17)

**Comment by tyn1998** [comment]
@Tenth-crew thanks for reporting. The issue is confirmed:

<img width="1415" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/8d10a75d-4f4e-49cd-b8e8-54a68f5590e4">

Hello @frank-zsy, could you help to check on this issue?

By the way, please fill out the PR title :)

**Comment by frank-zsy** [comment]
OSS-GPT is now back to work.

<img width="524" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/8512426/1d8e127e-7bb9-493a-b401-82c16e3a3ff3">

**Comment by frank-zsy** [comment]
The reason is the server instance shut down and restart then the service is down, now it started.
