### ISSUE TITLE
[Bug] Redundant Tabs 

### ISSUE THREAD

**Issue by HalloMelon** [hypertrons/hypertrons-crx#759]
### Version

1.9.3

### Current Behavior

https://github.com/hypertrons/hypertrons-crx/assets/79428895/1f5582c1-4d5c-42b1-b8d7-250e74ff9a51

this repo has more than one perceptor tab, the url as follow: https://github.com/jmorganca/ollama

### Environment

```markdown
- OS:Windows 11
- Browser:Chrome
```

**Comment by zhaosj975** [comment]
But now I see, it becomes normal. 
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/1534d5fa-302d-4375-9996-b8054c1555ea)

sometimes it is not so stable. 👀

**Comment by wxharry** [comment]
> But now I see, it becomes normal. 
> 
> sometimes it is not so stable. 👀

Yeah. That could happen. It could be something else like how you access this link.

**Comment by HalloMelon** [comment]
@wxharry  You're right, it seems like there could be multiple factors contributing to this issue. That's a valid point to consider. 🤔
