### ISSUE TITLE
[Feature] Improvement Suggestion for the xAxis of the Issues Tooltip Chart

### ISSUE THREAD

**Issue by HalloMelon** [hypertrons/hypertrons-crx#762]
### Description

I would like to propose some enhancements for the xAxis of the issues tooltip chart. Currently, it is not as clear and user-friendly as it could be. The first time I saw the chart,I cannot understand the meaning of xAxis so quickly. So the text on the xAxis could be easier to read.

For examples：
In this repo ( its url as follow: https://github.com/hypertrons/hypertrons-crx ), perhaps it would be better to only display the numerical values of the years on the xAxis within this time range,.

![a026709a10ec0ce0c26e22eb8881fd2](https://github.com/hypertrons/hypertrons-crx/assets/79428895/8b26c10b-c8d3-4b6f-8fcc-1e7828392b41)

In this repo ( its url as follow: https://github.com/X-lab2017/open-research )，within this time range, I think this presentation format is more reasonable.

![4378edf3d0d108ec1e5796cd6d78583](https://github.com/hypertrons/hypertrons-crx/assets/79428895/dff826b3-4b5b-47b3-8244-7d687161466e)

**Comment by tyn1998** [comment]
<img width="774" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/fd4a5686-70a3-4410-8cb1-dd3aafbf3528">

Hello @HalloMelon, the issue can be resolved by combining [xAxis.minInterval](https://echarts.apache.org/zh/option.html#xAxis.minInterval) and [xAxis.axisLabel.formatter](https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter).

**Comment by wangyantong2000** [comment]
@HalloMelon's question is mainly about explaining the meanings of the x-axis and y-axis. Now I have an idea to mimic this feature:  [the link in Chrome](chrome-extension://inlecjdnpbciaembmkojceckffmmlllb/options.html) or [the link in Edge](extension://lbbajaehiibofpconjgdjonmkidpcome/options.html). 
<img width="363" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/135088663/6d8c2f38-fc52-49a1-81f8-a77bdcf5c321">
Add a small component next to the chart title to trigger the display of the meanings of the x-axis and y-axis. If this is feasible, @HalloMelon do you have any specific ideas on implementation details?

**Comment by HalloMelon** [comment]
I think we need to state two things in the tips box: the first is that the vertical axis represents the increment rather than the total for each period, and the second is that the horizontal axis represents the time at which the user can resize the interval by scrolling with the mouse. 

So the following example is a possible representation：the vertical axis represents the increments for each time period; the horizontal axis represents the time; the horizontal axis intervals are resized by scrolling with the mouse.

**Comment by HalloMelon** [comment]
I think we need to state two things in the tips box: the first is that the vertical axis represents the increment rather than the total for each period, and the second is that the horizontal axis represents the time at which the user can resize the interval by scrolling with the mouse. 

So the following example is a possible representation：the vertical axis represents the increments for each time period; the horizontal axis represents the time; the horizontal axis intervals are resized by scrolling with the mouse.
