### ISSUE TITLE
[Bug] Can't update activity and influence after changing githubid

### ISSUE THREAD

**Issue by funky-eyes** [hypertrons/hypertrons-crx#763]
### Version

1.9.3

### Current Behavior

![image](https://github.com/hypertrons/hypertrons-crx/assets/19943636/0326e444-5038-42c1-90ea-76639ecabe81)
为什么我的活跃度和开源影响力仅到9月份就不再更新了？在10月份的时候，我将a364176773这个id改名为funky-eyes，不知道是不是这个原因引起的？
Why did my activity and open source influence stop updating only in September? In October, I renamed the id a364176773 to funky-eyes, and I wonder if that's what caused it?
![image](https://github.com/hypertrons/hypertrons-crx/assets/19943636/d0342d70-95c3-4883-8d1c-eaeac63140fb)
https://github.com/seata/seata/pulse?redirect=perceptor
Secondly in seata's contributor active, my activity is counted on my previous id, shouldn't this be counted as in the github commits? No matter what name I change, my email stays the same, doesn't it?
其次在seata的贡献者活跃中，我的活跃度都被算在了之前的id上，这不应该按照github commits中来统计吗？无论我改了什么名，我的邮箱不变，不是吗？

### Environment

```markdown
- OS:
- Browser:
```

**Comment by tyn1998** [comment]
> Secondly in seata's contributor active, my activity is counted on my previous id, shouldn't this be counted as in the github commits? No matter what name I change, my email stays the same, doesn't it?

Hi @funky-eyes , as far as I know a user's login id is the identifier for computing all metrics in OpenDigger. Commits don't take influence on the computing process.

> Why did my activity and open source influence stop updating only in September? In October, I renamed the id a364176773 to funky-eyes, and I wonder if that's what caused it?

Could you help on this question? @frank-zsy

**Comment by frank-zsy** [comment]
@funky-eyes I will look into this problem, actually in OpenDigger we use GitHub database ID rather than login name as the index of a user, so it should not be wrong if you change your GitHub login. This should be a bug and will be fixed soon.

**Comment by frank-zsy** [comment]
@funky-eyes Look into the detail data of yours in https://oss.x-lab.info/open_digger/github/funky-eyes/activity.json and https://oss.x-lab.info/open_digger/github/funky-eyes/openrank.json , `2023-10` is a key included in the data, so maybe this involves something about cache strategy of the file. Can you try to reload the page without cache and check if the data is right or not?

**Comment by funky-eyes** [comment]
> @funky-eyes Look into the detail data of yours in https://oss.x-lab.info/open_digger/github/funky-eyes/activity.json and https://oss.x-lab.info/open_digger/github/funky-eyes/openrank.json , `2023-10` is a key included in the data, so maybe this involves something about cache strategy of the file. Can you try to reload the page without cache and check if the data is right or not?

Thanks, I solved the problem by clearing the cache.
