### ISSUE TITLE
[Bug] racing bar graph dithers heavily at beginning of every month (2k+ data)

### ISSUE THREAD

**Issue by TieWay59** [hypertrons/hypertrons-crx#765]
### Version

1.9.3

### Current Behavior

https://github.com/godotengine/godot-docs/pulse?redirect=perceptor

Watch this repo's animation, and it seems glitching in the gap of months.

### Environment

```markdown
- OS: Ubuntu
- Browser: Edge
```

### Any additional comments?

Am I the only one having this problem? pls let me know.

**Comment by TieWay59** [comment]
Pinging @tyn1998 @wxharry

**Comment by lhbvvvvv** [comment]
I did not see the glitch, can you give the animated segment of the glitch.
