### ISSUE TITLE
[Feature] Add `contributors` metric into charts.

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#769]
### Description

As implemented in https://github.com/X-lab2017/open-digger/pull/1491 , we will have `contributors` metric data exported in OpenDigger next month.

In many cases, when I look into a repo, I would like to know both the participants count and contributors count, but right now, only participants count are shown.

Maybe we can display the contributors metric with participants metric in same charts like this:

<img width="496" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/8512426/11a0cca6-d680-446b-b7bb-0e9b403c5447">

An extra bar chart should be added in the image.

**Comment by HalloMelon** [comment]
the definition of contributor：https://chaoss.community/kb/metric-contributors/
