### ISSUE TITLE
[Discussion] How do we check for updates and notice users?

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#78]
The situation is a little complex:  

- The extension can compare its current version with the latest one in background tasks, but at least we need to setup an `http-api` to provide information about the latest version.  
- Then we should decide what is exactly the **latest version**. Is it the latest release build created by `ci` or one `.crx` that chosen by us manually? Or can it only be a candidate which is already published into stores? 
- So it all comes to the original problem: we don't know very much about how to distribute out extension to users all over the world. Maybe someone should study the rules first to help us work better in this field.

All in all, this problem is not anything about code but we should have a discussion about it at the very begining.

**Comment by heming6666** [comment]
Done by #81 .

Closed.
