### ISSUE TITLE
[chore] change the project name Hypercrx -> HyperCRX

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#800]
### Discussed in https://github.com/hypertrons/hypertrons-crx/discussions/772

<div type='discussions-op-text'>

<sup>Originally posted by **xiaoya-yaya** January 20, 2024</sup>
Hypercrx as the tool demo paper was recently accepted by ICPC 2024 conference and have received quite good review comments!

According to the reviewers' comments, and in conjunction with the community feedback, HyperCRX as the project name will be more easily pronounced for newcomers. Thus, we propose to change the project name from Hypercrx to HyperCRX.

<img width="1328" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/56542972/340524e8-a58b-4561-b26d-763a59b6dc95"></div>

We should change all occurrences of `Hypercrx` to `HyperCRX`, yet variables in code that contain "hypercrx" do not need a change.

**Comment by HalloMelon** [comment]
Yeah, I'll try this!
