### ISSUE TITLE
[Bug] Some charts may not display Chinese correctly under Chinese settings

### ISSUE THREAD

**Issue by wangyantong2000** [hypertrons/hypertrons-crx#804]
### Version

1.9.5

### Current Behavior

The chart display under normal Chinese settings is as follows.
<img width="478" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/135088663/370eb14a-dfbc-47a1-87e8-6aaebd127291">
However, in the following charts, Chinese cannot be displayed correctly and is still in English.
<img width="220" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/135088663/f19d2fed-769d-4c6f-97fd-e2eb0aaceb59">
<img width="476" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/135088663/65a7c764-1268-4298-be3a-3b553777d8d5">

https://github.com/hypertrons/hypertrons-crx/assets/135088663/8b3881fb-812c-4709-808b-23751630c818

### Expected Behavior

Make these charts display correctly.

### Environment

```markdown
- OS:MacOS Monterey M3
- Browser:123.0.6312.107 (arm64)
```

**Comment by wxharry** [comment]
Related #63

**Comment by wxharry** [comment]
Fixed in #826
