### ISSUE TITLE
[OSS101] Task 3: Display OpenDigger labels in the right of the repository header

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#807]
## Description
From #711

![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/6b161a12-b1df-4f62-a170-708e368d9fce)

**Background Information:**  The meta file exported by OpenDigger now includes label data.
**Objective:**  To add this label data to the project page for better display of label information.
**Reference:**  You can refer to the file at https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json, which lists all labels for the OpenDigger project.

## 任务描述
来自 #711

![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/b36371d7-f6e4-4298-a7e3-42182112f9c5)

**背景信息：** OpenDigger现在导出的meta文件包含了标签数据。
**目标：** 将这些标签数据添加到项目页面上，以便更好地展示标签信息。
**参考：** 可以参考 https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json 文件，其中列出了所有OpenDigger项目的标签信息。

**Comment by CarterpillarOnGh** [comment]
1.我们能修改github用户profile页面中日历的格子颜色，但是，没有办法定位到label所在的div，所以没法修改。是否有办法定位到label所在的div的parent所在的div，再定位回去？2.添加feature是否同时需要index和view?3.如果需要的话，view应该如何编写？（我们是新手小白）

**Comment by wxharry** [comment]
第一步可以先在view中参考已有的label添加新的label，然后再由下往上把这个feature调整成可以控制的独立feature
