### ISSUE TITLE
[Feature] A better way to check for updates

### ISSUE THREAD

**Issue by LiuChangFreeman** [hypertrons/hypertrons-crx#81]
We can judge the type of installation by `chrome.app.getDetails()` and see whether `key` is in the `manifest`.
Let's take one for example, the right is a store-version installation:
![20210401171435](https://user-images.githubusercontent.com/20047907/113273172-f722a480-930e-11eb-9959-586f7bb0606e.png)
Each time when we start a background task, the necessary information will be send to the back-end server such as:  

- The user-agent. We can judge whether the user can install '.crx' directly.
- The version. To decide whether there is a suitable update for it.
- The type. If it is a store-version installation, the update will be ready only when it has been published into the store. 

What the back-end server should respond: 

- If there is a suitable update.
- How to update. 
- Some necessary information. (_Date of it, the latest version number, what's new_......)

If we don't want to set up the back-end server so early, a json served by oss is also enough.   
In that situation, there must be a way to update the json.  
For example, just use another `ci` to make it. 
This decision should be done as soon as possible considering that it would take a lot of time to test.

**Comment by LiuChangFreeman** [comment]
@frank-zsy The oss deployment is needed to make further work be continued.

**Comment by heming6666** [comment]
The necessary key has been deployed and it works now.

Done.
