### ISSUE TITLE
[OSS101] Task 8: Obtain GitHub tokens to increase request limits

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#812]
## Description
Recently, there has been a [discussion](https://github.com/hypertrons/hypertrons-crx/issues/773#issuecomment-1918190670) in the community about GitHub Tokens. In fact, HyperCRX had previously introduced GitHub Tokens to increase the number of requests made to GitHub, as seen in #100. However, in #574, we removed it since there was no longer a frequent need to access the GitHub API.

Considering that HyperCRX may need to frequently access the GitHub API in the future, we need to reintroduce GitHub Tokens with the following specific requirements:

1. Provide a UI interface allowing users to input their GitHub Tokens.
2. Securely store user's Tokens.
3. Encapsulate a network request method that uses the GitHub Token, which will be called by other new features needing to access the GitHub API in the future.

## 任务描述
近期，社区内又出现了对 GitHub Token 的[讨论](https://github.com/hypertrons/hypertrons-crx/issues/773#issuecomment-1918190670)。事实上，HyperCRX曾经早已引入过 GitHub Token 来增加向 GitHub 发起请求的次数，见 #100。但在 #574，我们将其移除了，因为 HyperCRX 不再有频繁访问 GitHub API 的需求。

考虑到未来 HyperCRX 会出现需要频繁访问 GitHub API 的特性，我们需要重新引入 GitHub Token，具体要求如下：

1. 提供UI界面，使用户可以输入他们的 GitHub Token
2. 安全存储用户的 Token
3. 封装一个使用 GitHub Token 的网络请求方法，该方法未来会被其他需要访问 GitHub API 的新特性调用

**Comment by wblxxx** [comment]
1.在哪提供输入token的UI界面，插件的扩展选项中吗？
2.ui界面和和存储token，封装网络请求方法分别在代码的那个模块进行增改？ 
@tyn1998

**Comment by wxharry** [comment]
1. 输入token的界面应在选项中（options），需要提供输入框和简单的说明（包括为什么我们需要用户提供token，用户该如何生成token，以及token需要哪些权限），可以参考[Refined GitHub](https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) options页面中的要素，结合我们options页的设计实现
2. UI界面在src/pages/Options/下。封装网络请求可以放在src/api/下的一个新文件，参考文件夹中的其他文件进行设计。关于token存储，我们有存储用户其他信息的功能，不需要额外设计。可以参考Refined GitHub 是如何存储token的。
Correct me if I am wrong. @tyn1998
