### ISSUE TITLE
[CI/CD] the deploy workflow seems broken

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#819]
### Description

https://github.com/hypertrons/hypertrons-crx/actions/runs/9141558225

**Comment by wxharry** [comment]
I tried re-running the job, it didn't give enough info. @tyn1998 Could you take a look at the chrome extension store to see the progress? I don't have the access.

**Comment by tyn1998** [comment]
Hi @wxharry, the action works good again: https://github.com/hypertrons/hypertrons-crx/actions/runs/9337278705/job/25698941030

Maybe it was just becuase the Edge Store service failed that time.
