### ISSUE TITLE
[Bug] HyperCRX breaks a native feature - GitHub Action Trigger Button

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-crx#825]
### Version

1.9.6

### Current Behavior

Currently, I cannot trigger the action as the video below shows:

https://github.com/hypertrons/hypertrons-crx/assets/32434520/1df27c09-03a6-4329-b309-3356ac00bb37

But after I disable HyperCRX the issue won't happen.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by wxharry** [comment]
The issue lies in `NativePopover.tsx` line 17 and 49
```
const $popoverContainer = $('div.Popover');

...

$popoverContainer.css('display', 'none'); 
```
The popup button is captured by our NativePopover wrongly and the display is set to none forever after the hidePopover is triggered.

**Comment by wangyantong2000** [comment]
I will try to fix this bug.
