### ISSUE TITLE
[Doc] Update App Store Description

### ISSUE THREAD

**Issue by Xsy41** [hypertrons/hypertrons-crx#833]
Since the previous description in the app store was a bit brief, I explain this section in detail below.

**Short description**

Adds analytic dashboards to GitHub

**Description**

Adds analytic dashboards to GitHub, facilitating the tracing of projects and exploration of developer networks.

Features:

📊 Displays developer activity and OpenRank trends
🤝 Visualizes developer relationships and networks
🤖 Uses GPT technology to generate content and suggestions (not available)
📈 Shows repository activity and OpenRank trends
🏁 Displays repository activity in a racing bar format
🔧 Provides detailed information on repository forks
📌 Adds labels for OpenRank, activity, contributors, and participants to repository headers
📑 Shows detailed information on repository issues
🔗 Visualizes relationships between repositories
🔀 Provides detailed information on pull requests
⭐ Shows detailed information on repository stars
GitHub: https://github.com/hypertrons/hypertrons-crx

**Screenshot**（Upto 6 images showing how your extension works. Size: 1280 x 800 pixels or 640 x 400 pixels）
![unnamed](https://github.com/user-attachments/assets/6de33703-7be7-4a88-84fc-854674bf8539)
![f406fb7fb1f3c27041dfcb034452e888](https://github.com/user-attachments/assets/50cf23f7-9a6b-4278-81c4-b1528cb3856b)
![9f903bc3ca58032a12b8f4fc9e11472b](https://github.com/user-attachments/assets/8d399959-a1de-4266-bc53-50114809ed2a)

**Search terms**（Up to 7 terms. 30 character limit for each term. No more than 21 separate words across all search terms)

1. HyperCRX
2. GitHub
3. X-lab
4. OpenRank
5. OpenDigger
6. Network
7. Developer

**Comment by HalloMelon** [comment]
The summary of the features is excellent! However, since we have updated our visualizations, could you please update the screenshots? This way, we can also update the content in the README accordingly.

**Comment by HalloMelon** [comment]
A simple introduction as followed：

Discover HyperCRX, a powerful browser extension designed to enhance your GitHub experience by providing in-depth insights into projects and developers. Seamlessly integrating with GitHub, HyperCRX offers a suite of interactive features that allow you to:
·Assess Maintenance Status: Instantly view the maintenance activity of repositories and developers.
·Track Developer Activity: Monitor the contributions and interactions of developers with detailed visualizations.
·Explore Connections: Understand the relationships between projects and developers through intuitive network graphs.

Ideal for software engineers, project maintainers, open-source newcomers, and employers, HyperCRX empowers you to make informed decisions and engage more effectively with the open-source community. Join over 1,000 users on Chrome and Edge who have already enhanced their GitHub workflow with HyperCRX.
Download now and transform the way you navigate and contribute to GitHub projects!

**Comment by Xsy41** [comment]
Yes! Below are screenshots of the updated features.
![2806cd396cd9dadf8928febfd502b92](https://github.com/user-attachments/assets/2975ae49-f9c2-4fc6-8b20-3557361622c3)
![total](https://github.com/user-attachments/assets/b85d1c81-8525-4e43-bb2b-5e4312187dd7)
![未命名的设计 (3)](https://github.com/user-attachments/assets/a0c3846d-2da7-40d3-9130-7d2a76eda0e8)
![未命名的设计 (5)](https://github.com/user-attachments/assets/f2fc1ab7-f9f1-4524-919b-16644d184c85)

**Comment by HalloMelon** [comment]
Thank you for your screenshot, which contributed to updating the repository's README and the project description in the store.
