### ISSUE TITLE
[Feature] Replace HyperCRX networks component with OSGraph networks

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#834]
### Description

Currently, we have 4 networks (2 for repos and 2 for developers) in HyperCRX, but since OpenDigger no longer maintains a graph database infra, the data of the 4 networks are not updated for months.

After OSGraph 2.0 launched, we could use OSGraph networks to replace the old components.

OSGraph has 6 types of network (3 for repos and 3 for developers), so we could just put them into HyperCRX and replace the old ones. OSGraph provides sharing URL to access the networks, so I think we just need to embed them with iframe.

**Comment by frank-zsy** [comment]
In development stage, we could just use the network URL of microsoft/vscode repo and tison to test. The networks are:

- Repo contribution graph: https://osgraph.com/result?shareId=1&shareParams=41881900,1405669423,1721288623,10&isShare=true
- Repo ecosystem graph: https://osgraph.com/result?shareId=2&shareParams=41881900,10&isShare=true
- Repo community graph: https://osgraph.com/result?shareId=3&shareParams=41881900,5,5,3&isShare=true
- Developer activity graph: https://osgraph.com/result?shareId=4&shareParams=18818196,10&isShare=true
- Developer partners graph: https://osgraph.com/result?shareId=5&shareParams=18818196,10&isShare=true
- Developer interests graph: https://osgraph.com/result?shareId=6&shareParams=18818196,5,3&isShare=true

In the future, the sharing URL of OSGraph will update to something like `https://osgraph.com/github/microsoft/vscode/xxgraph` then we can replace the URL with current repo name and developer login.

**Comment by wangyantong2000** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ca72d46a-d2d3-4c82-b32e-dd0f1c783586">
Is it possible for the style to look like this in the future

**Comment by HalloMelon** [comment]
X-lab 用现有的 sharing url 测试 iframe 在插件中嵌入的匹配度和效果  这是什么意思

**Comment by frank-zsy** [comment]
@HalloMelon Could you provide the detailed title and description of the networks which will be used in this feature according to the information in https://github.com/TuGraph-family/OSGraph readme? We will need both Chinese and English version.

**Comment by HalloMelon** [comment]
Yeah, let me do it~

**Comment by wangyantong2000** [comment]
At present, there are 4 networks in HyperCRX. Afterwards, will we embed all 6 networks in OSGraph into HyperCRX or only embed 4 of them in the future.

**Comment by HalloMelon** [comment]
**English Version**
- Project Contribution Network
Description: Discover the core contributors of a project. By analyzing the development activities (Issues, PRs, Commits, Code Reviews, etc.), identify the key contributors to the project.
Example: To find out who is contributing code to the Apache Spark project, select "Project Contribution Network" - search for "spark" - select "apache/spark". You will find core contributors such as HyukjinKwon and dongjoon-hyun, as well as bot accounts like AmplabJenkins and SparkQA that only participate in Code Reviews.

- Project Ecosystem Network
Description: Gain insights into the ecosystem partners of a project. Extract the development activities and organizational relationships between projects to construct the core ecosystem relationships.
Example: To understand the ecosystem around the popular open-source model Llama3, select "Project Ecosystem Network" - search for "llama3" - select "meta-llama3/llama3". You will see connections to well-known AI projects like PyTorch, TensorFlow, and Transformers, as well as the notable Llama.cpp. Interestingly, you can also find common developers between Ray and Llama3.

- Project Community Network
Description: Analyze the distribution of a project's community. Extract information about the core developer communities based on the development activities and organizations involved.
Example: To understand the current state of the Flink project's community, select "Project Community Network" - search for "flink" - select "apache/flink". The main followers are from China, the USA, and Germany, with Alibaba being a major contributor.

- Development Activity Network
Description: Showcase individual contributions to open source. By analyzing the development activities (Issues, PRs, Commits, Code Reviews, etc.), identify the core projects a developer is involved in.
Example: To see which open-source projects Linus Torvalds is currently involved in, select "Development Activity Network" - search for "torvalds". Besides the Linux project, Torvalds is also contributing to LLVM, Mody, libgit2, and Subsurface (a diving log management tool).

- Open Source Partners Network
Description: Find open source partners. Identify other developers who closely collaborate with a developer in the open-source community.
Example: To find like-minded people in the open-source community, select "Open Source Partners Network" - search for your ID. You might discover many strangers following the same projects, and you can explore the open-source partners of your friends and colleagues to expand your network.

- Open Source Interests Network
Description: Discover individual open-source interests. Analyze the technical fields and interests of developers based on the themes and tags of the projects they participate in.
Example: To see what technologies the most active GitHub developers are interested in, select "Open Source Interests Network" - search for "sindresorhus" (GitHub's top user). You will find interests in Node.js, npm, and JavaScript, as well as the massively popular Awesome project with over 300k stars.



**Chinese Version**
- 项目贡献图谱
描述: 发现项目核心贡献。根据项目开发者的研发活动信息（Issue、PR、Commit、CR等），找到项目的核心贡献者。
示例: 想看看谁在为Apache Spark项目写代码，选择“项目贡献图谱” - 搜索“spark” - 选择“apache/spark”。可以看到HyukjinKwon、dongjoon-hyun等核心贡献者，还有AmplabJenkins、SparkQA这两个只参与Code Review的机器人账号。

- 项目生态图谱
描述: 洞察项目生态伙伴。提取项目间的开发活动、组织等关联信息，构建项目的核心生态关系。
示例: 想了解最近很火的开源大模型Llama3的周边生态，选择“项目生态图谱” - 搜索“llama3” - 选择“meta-llama3/llama3”。可以看到与pytorch、tensorflow、transformers等知名AI项目的关系，还有上科技头条的llama.cpp。意外发现ray和llama3有不少公共开发者，值得深入挖掘。

- 项目社区图谱
描述: 分析项目社区分布。根据项目的开发活动和开发者组织等信息，提取项目核心开发者社区的分布情况。
示例: 想了解大数据引擎Flink发展的社区现状，选择“项目社区图谱” - 搜索“flink” - 选择“apache/flink”。可以看到项目关注者主要来自中国、美国和德国，Alibaba是代码贡献的中坚力量。
开发活动图谱
描述: 展示个人开源贡献。根据开发者的研发活动信息（Issue、PR、Commit、CR等），找到参与的核心项目。
示例: 想知道大神Linus Torvalds最近在参与哪些开源项目，选择“开发活动图谱” - 搜索“torvalds”。可以看到他主要参与的是linux项目，但也有llvm、mody、libgit2的贡献，还在subsurface这种“潜水日志管理工具”上有大量贡献。
开源伙伴图谱

描述: 寻找个人开源伙伴。找到开发者在开源社区中，与其协作紧密的其他开发者。
示例: 想知道在开源社区有没有和自己志同道合的人，选择“开源伙伴图谱” - 搜索自己的ID。会发现有很多陌生人关注了同一批项目，也可以探索朋友们的开源伙伴，拓展自己的开源社区人脉。
开源兴趣图谱

描述: 挖掘个人开源兴趣。根据参与项目的主题和标签等信息，分析开发者的技术领域与兴趣。
示例: 想知道GitHub上最活跃的开发者对哪些技术感兴趣，选择“开源兴趣图谱” - 搜索“sindresorhus”（GitHub用户榜 No.1）。可以看到他对node、npm、js很感兴趣，他发起的awesome项目有超过30W星。当前数据主要来自项目标签信息，后续会借助AI技术有更好的展现。

**Comment by frank-zsy** [comment]
I think we will embed all 6 networks in OSGraph if it is not too much trouble.

**Comment by wangyantong2000** [comment]
Currently, all accounts and repositories can display OSGraph. However, the racing bar in our Perceptor interface is not available in all repositories. At present, without the data of racing bar, the effect will be as shown in the figure.
<img width="1494" alt=" Screenshot 2024-08-22 16 42 22" src="https://github.com/user-attachments/assets/1dba8ea2-3288-47d4-8961-700c9eb77895">
I think we can remove this prompt. If there is data for the racing bar, the racing bar will be displayed; if not, it will not be displayed.

**Comment by wangyantong2000** [comment]
The last time OSGraph personnel raised the following questions:
1. Caves height issue
2. Refreshing the page graph will result in a scaling process
3. Click on the percetor, refresh, and the tab activates insights
4. The OSGraph link in the upper right corner of the graph only leads to the homepage and cannot directly reach the corresponding canvas of the project.
5. All repositories and accounts have these 6 graphs.


https://github.com/user-attachments/assets/9c77b2c3-ffa8-4950-9f65-f64e5d4f3ccd


https://github.com/user-attachments/assets/28601c07-6004-4cff-97c9-9c149364eac5

Several issues have been resolved at present. As shown above. And for questions 1 and 2, regarding height and refresh scaling, I think it is due to issues with the OSGraph webpage itself. As shown in the video below.

https://github.com/user-attachments/assets/8680db51-2556-4eb3-918f-e445bf52f815

**Comment by frank-zsy** [comment]
It looks really good already~

**Comment by wangyantong2000** [comment]
> @wangyantong2000 Why does this issue reopened? Is there anything to improve?

Previously, it was mentioned in the group that better routing solutions may be proposed in the future. For convenience, this issue has not been closed.

**Comment by frank-zsy** [comment]
Sure, understood. Actually OSGraph has modified the routing design, I think we can start to migrate to the new version.

**Comment by wangyantong2000** [comment]
> Sure, understood. Actually OSGraph has modified the routing design, I think we can start to migrate to the new version.

OK.

**Comment by wangyantong2000** [comment]
> Sure, understood. Actually OSGraph has modified the routing design, I think we can start to migrate to the new version.

Is there a description of the new routing design?
