### ISSUE TITLE
[Bug] The latest commit information on the repo homepage user card openrank is not added

### ISSUE THREAD

**Issue by Tenth-crew** [hypertrons/hypertrons-crx#842]
### Version

latest

### Current Behavior

![image](https://github.com/user-attachments/assets/9e5eb66b-139d-431c-8b0f-85feed362664)

### Expected Behavior

I hope that the user card can add openrank information normally

### Environment

```markdown
- OS: Windows11 
- Browser: Edge 126.0.2592.113
```

**Comment by wangyantong2000** [comment]
It should be due to the dynamic loading of the page. At the beginning, when you retrieve the elements, the network did not load them, causing your` document. querySelectorAll (hovercardselector) `query to be empty.

**Comment by wangyantong2000** [comment]
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/8a96f62f-8eb5-4985-b712-ff34adc70712">

<img width="474" alt="image" src="https://github.com/user-attachments/assets/036f0d64-2006-43bf-b2d6-a420f1c6db53">
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/f6b3ca2c-ec96-4397-b744-f1d5899ad5bb">

https://github.com/opencv/opencv

At present, such a problem still exists, whether it will be solved.

**Comment by Tenth-crew** [comment]
Can you describe how you encountered this bug? I don't know the details yet, but the possible reason is a network problem. In the code, I set it to ignore the element if it is not loaded within 1500ms. If you do not load it within the first 1500ms of entering the warehouse, the element may not be monitored.

**Comment by wangyantong2000** [comment]
> <img alt="image" width="1347" src="https://private-user-images.githubusercontent.com/135088663/357279479-8a96f62f-8eb5-4985-b712-ff34adc70712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjU1MjQsIm5iZiI6MTcyMzUyNTIyNCwicGF0aCI6Ii8xMzUwODg2NjMvMzU3Mjc5NDc5LThhOTZmNjJmLThlYjUtNDk4NS1iNzEyLWZmMzRhZGM3MDcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNTAwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWIwMjRhNTNmNjU2ZTI0MWJjYjI3ZjRkNTkzOTVmM2Q1MmI1OGRiNDU5ZmIyNDk3N2U5Y2RiNTA1ZDdlZTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5zF0FUOyR00Vul3kuMQbRMRgndMjy4dG5cXqECV5aI"> <img alt="image" width="474" src="https://private-user-images.githubusercontent.com/135088663/357279042-036f0d64-2006-43bf-b2d6-a420f1c6db53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjU1MjQsIm5iZiI6MTcyMzUyNTIyNCwicGF0aCI6Ii8xMzUwODg2NjMvMzU3Mjc5MDQyLTAzNmYwZDY0LTIwMDYtNDNiZi1iMmQ2LWE0MjBmMWM2ZGI1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNTAwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmZhMjYxMGUzZmQ5ODU1ZGMzZTc1MDU2MWU4ODg5YWU1OTlmOTEzZTc5N2MxMWJjNjRkZWNkY2JiOGI2OGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vX-nj42QjU_BLVTGhIyrI4-2Fhx_MfvuP6fEnTSS0Hk"> <img alt="image" width="1510" src="https://private-user-images.githubusercontent.com/135088663/357279153-f6b3ca2c-ec96-4397-b744-f1d5899ad5bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjU1MjQsIm5iZiI6MTcyMzUyNTIyNCwicGF0aCI6Ii8xMzUwODg2NjMvMzU3Mjc5MTUzLWY2YjNjYTJjLWVjOTYtNDM5Ny1iNzQ0LWYxZDU4OTlhZDViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNTAwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njk1NzYyY2NkZDdmZjYwODIxZTAxNDdkMWM2NjA4YTk5MTVmMzcyOTIxNGU0NTVkZThhMDM2MmNjOGNkZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8DGiKsNBNto7RL5gku-ivRGE7B9krl83v7dEp-rxafo">
> https://github.com/opencv/opencv
> 
> At present, such a problem still exists, whether it will be solved.

The first two diagrams are on the same screen. The second diagram shows openrank, but the first one does not. The second diagram is in the contributors screen, for a person whose openrank is there but isn't shown. And no one else's cards in that contributors are shown.

**Comment by Tenth-crew** [comment]
The reason I can think of is network issues. Maybe we can set the waiting time to be longer.
