### ISSUE TITLE
[Feature] Circle of contributors

### ISSUE THREAD

**Issue by MrH233** [hypertrons/hypertrons-crx#850]
## Description
**This feature issue is to track task which is mentioned in https://github.com/hypertrons/hypertrons-crx/issues/808**
In order to present warehouse contributors in a more diverse manner, as well as their contribution size and collaborative relationships. We constructed an Active Developer Collaboration Network on the homepage to replace the original Circle of Contributors.
![点击前](https://github.com/user-attachments/assets/fea2b5be-3e4a-4828-a845-8ca058811394)
In addition, we have set up a toggle button where users can switch the contributor interface view to the Circle of Contributors by clicking the button.
![点击后](https://github.com/user-attachments/assets/9d1c5d78-8991-4903-ade0-34856991be60)
##### For more information, please refer to the README_808 of <a href="https://github.com/MrH233/hypertrons-crx">fork repository<a/> and feel free to share your views in this issue.

**Comment by HalloMelon** [comment]
Your suggestion is excellent, but I think from an aesthetic perspective, further adjustments could be made, such as adding a button at the circle shown in the screenshot below. It could use a network icon, making it display the network diagram when the mouse hovers over it.

![1722477528577](https://github.com/user-attachments/assets/ec95b17e-ff2f-4d78-88b4-a3d1113de01a)
