### ISSUE TITLE
[Bug] the length of contributor bar have some problem

### ISSUE THREAD

**Issue by PureNatural** [hypertrons/hypertrons-crx#853]
### Version

1.9.7

### Current Behavior

![image](https://github.com/user-attachments/assets/48eaf663-da16-4610-9437-49b448122711)
As we can see the image, two contributor's activity are 5.8, but the length of the bar may not equal.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by wangyantong2000** [comment]
<img width="304" alt="image" src="https://github.com/user-attachments/assets/edcf8d58-3672-4be3-b9c8-fe95617045b3">

The actual values are 5.81 and 5.76, respectively, because they are both 5.8 when the bits are reserved.

**Comment by wangyantong2000** [comment]
If you want to display the last two digits, you can set the `precision` in the configuration to 2. The data can be fully displayed with the following effect.
<img width="919" alt="image" src="https://github.com/user-attachments/assets/fbb8c312-d27a-4420-a475-ba4e65fbcfd1">

**Comment by wangyantong2000** [comment]
If it is confirmed that this needs to be changed, I will complete this task.

**Comment by HalloMelon** [comment]
Hi @wangyantong2000. For example, my openrank value is 3.3, can it be kept consistent and also display 3.30?

**Comment by wangyantong2000** [comment]
> Hi @wangyantong2000. For example, my openrank value is 3.3, can it be kept consistent and also display 3.30?

Then just switch to a custom format. The effect is as follows. 
<img width="893" alt="image" src="https://github.com/user-attachments/assets/c0045eca-8d61-48ac-bd9f-5403eec6f215">
Do others think we should keep the last digit '0'?
