### ISSUE TITLE
[Doc] Update the store display picture and description

### ISSUE THREAD

**Issue by Xsy41** [hypertrons/hypertrons-crx#857]
### Description

We plan to unify the name of HyperCRX, update the image display of the store, and modify the introduction name.
**1. Unified name**
![统一名称](https://github.com/user-attachments/assets/31e1ec90-bb5a-46f1-a55c-2a9f940a8846)
**2. Change the store picture**
Our current picture of the store is a little blurry, with multiple images pieced together. Try using small pictures to show the content.
![1920710d5f0856d35a6d9b3fb583bec](https://github.com/user-attachments/assets/b1ddfd47-5607-4f2f-ab91-8544007e4608)
Roughly follow this idea to change the display image.
<img width="1599" alt="清晰大图" src="https://github.com/user-attachments/assets/9241a7c0-fb6e-4da9-b03e-4a6314548fca">
**3. Introduce the name change**
![93d7a8395ac4aa8ecf0b2d5c7895095](https://github.com/user-attachments/assets/afa1137e-cee7-4405-9e71-3d3117dca8ce)

**Comment by HalloMelon** [comment]
Like the introduction of this [plug-in,](https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf?hl=zh-CN&utm_source=ext_sidebar)  and based on the previous issues (https://github.com/hypertrons/hypertrons-crx/issues/833). I think the introduction can be written like this:

Adds analytic dashboards to GitHub, facilitating the tracing of projects and exploration of developer networks.

Features:
📊 Displays developer activity and OpenRank trends
🤝 Visualizes developer relationships and networks
🤖 Uses GPT technology to generate content and suggestions (not available)
📈 Shows repository activity and OpenRank trends
🏁 Displays repository activity in a racing bar format
🔧 Provides detailed information on repository forks
📌 Adds labels for OpenRank, activity, contributors, and participants to repository headers
📑 Shows detailed information on repository issues
🔗 Visualizes relationships between repositories
🔀 Provides detailed information on pull requests
⭐ Shows detailed information on repository stars

Download now and transform the way you navigate and contribute to GitHub projects!

**Comment by HalloMelon** [comment]
Hello @Xsy41 ,I just submitted a PR and modified the text, but there are still some problems with workflow processing. When I click "Test Token", there are two failure situations, one is an invalid token, and the other is that users did not click "save" first. In the second method, when you directly click "Test Token", can the corresponding prompt pop up, such as: "Please save first and then test."？

**Comment by wangyantong2000** [comment]
> Hello @Xsy41 ,I just submitted a PR and modified the text, but there are still some problems with workflow processing. When I click "Test Token", there are two failure situations, one is an invalid token, and the other is that users did not click "save" first. In the second method, when you directly click "Test Token", can the corresponding prompt pop up, such as: "Please save first and then test."？

It should be better to modify the workflow, and it should also be possible to test without saving after input.

**Comment by HalloMelon** [comment]
> > Hello @Xsy41 ,I just submitted a PR and modified the text, but there are still some problems with workflow processing. When I click "Test Token", there are two failure situations, one is an invalid token, and the other is that users did not click "save" first. In the second method, when you directly click "Test Token", can the corresponding prompt pop up, such as: "Please save first and then test."？
> 
> It should be better to modify the workflow, and it should also be possible to test without saving after input.

Oh yeah, I read the specific requirements:

Provide a UI interface allowing users to input their GitHub Tokens.
Securely store user's Tokens.
Encapsulate a network request method that uses the GitHub Token, which will be called by other new features needing to access the GitHub API in the future.

So, it is better to test before save, and the current tip is ok.

**Comment by wangyantong2000** [comment]
> Oh yeah, I read the specific requirements:
> 
> Provide a UI interface allowing users to input their GitHub Tokens. Securely store user's Tokens. Encapsulate a network request method that uses the GitHub Token, which will be called by other new features needing to access the GitHub API in the future.
> 
> So, it is better to test before save, and the current tip is ok.

The current problem is that this function has a problem, when the first input, the correct token after the test, will also be reported error. This feature should be perfected.

**Comment by Xsy41** [comment]
I changed the image display in the app store. Below is a link to the image.
[Picture link](https://ibb.co/album/pvQXr2)
I feel like we can change our name in the App Store from "HyperCRX" to "HyperCRX for GitHub" and change the brief section to "Adds analytic dashboards to GitHub".

**Comment by HalloMelon** [comment]
Yeah, I think it's great. But maybe the screenshots can provide more relevant introduction, like this one：

![image](https://github.com/user-attachments/assets/ca2af198-5063-4c10-8cc0-927666fb715b)

**Comment by Xsy41** [comment]
Okay, I've added a few more screenshots with more specific text. Below is a link to the image.
[Picture link](https://ibb.co/album/M8h0ns)

**Comment by HalloMelon** [comment]
It is better, and I have the following picture as a supplement.
![FotoJet](https://github.com/user-attachments/assets/f1d2aeb7-6ffe-4b51-936c-759a6bc57f43)

**Comment by HalloMelon** [comment]
I updated with two new screenshots.
![FotoJet2](https://github.com/user-attachments/assets/99e837a3-3255-487e-9c6e-9e9cb7a56610)
![FotoJet1](https://github.com/user-attachments/assets/7e3df641-bead-4a0c-9190-cc81c76bab06)

**Comment by HalloMelon** [comment]
Hypercrx project adds analytic dashboards to GitHub, aiming at tracing, digging and gaining insight into the projects and developers you're interested in. We do this by inserting useful dashboards into GitHub pages. Hypercrx provides an effective way for digital operations and analysis of open source community.

Features:
📊 Displays developer activity and OpenRank trends
🤝 Visualizes developer relationships and networks
🤖 Uses GPT technology to generate content and suggestions (not available)
📈 Shows repository activity and OpenRank trends
🏁 Displays repository activity in a racing bar format
🔧 Provides detailed information on repository forks
📌 Adds labels for OpenRank, activity, contributors, and participants to repository headers
📑 Shows detailed information on repository issues
🔗 Visualizes relationships between repositories
🔀 Provides detailed information on pull requests
⭐ Shows detailed information on repository stars

Download now and transform the way you navigate and contribute to GitHub projects!
