### ISSUE TITLE
[Bug] Multiple tags can cause problems with tag arrangement

### ISSUE THREAD

**Issue by wangyantong2000** [hypertrons/hypertrons-crx#859]
### Current Behavior

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/dae7ec49-f46a-4a05-81d9-35ef80dff51f">

https://github.com/openai/whisper

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/29bcf6ec-4f98-432a-8f29-e7c77207c528">

https://github.com/opencv/opencv

Multiple tags can cause problems with tag arrangement, such as in the two repositories above.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by HalloMelon** [comment]
I think when there are a lot of tags, some tags can be folded, as shown below:

![image](https://github.com/user-attachments/assets/b87e12f9-283c-4270-94a6-31d93d8dd503)

**Comment by wangyantong2000** [comment]
> I think when there are a lot of tags, some tags can be folded, as shown below:
>
>! [image](https://private-user-images.githubusercontent.com/79428895/357378619-b87e12f9-283c-4270-94a6-31d93d8dd503.png?jw t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6I mtleTUiLCJleHAiOjE3MjM1NDYzNDYsIm5iZiI6MTcyMzU0NjA0NiwicGF0aCI6Ii83OTQyODg5NS8zNTczNzg2MTktYjg3ZTEyZjktMjgzYy00MjcwLTk0Y TYtMzFkOTNkOGRkNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJ TJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmW C1BbXotU2lnbmF0dXJlPWNmNWVlYTZjNmE4NzY1OTY2MTZlZGI4OWQ5Zjc2NDlmMDQ1ZDkyYjBkNzQ0MGMwMTgxM2ZmZWI5ZDNiODNlZDUmWC1BbXotU2lnb mVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j6nOm1oXC90kAriBEl0HfE6jviZrKcwVwG_BFvMbH-g)

This idea may be feasible, you can give it a try.

**Comment by frank-zsy** [comment]
Is this the feature of v1.9.7 or later version? I am currently using 1.9.7 but can not see the labels.

**Comment by wangyantong2000** [comment]
> Is this the feature of v1.9.7 or later version? I am currently using 1.9.7 but can not see the labels.

This hasn't been released yet. Currently there is an issue that has been merged into the master branch of the repository.

**Comment by wangyantong2000** [comment]
Because some repositories label a lot of data is very long. One idea is to mimic the repository home page by adding a label for the repository underneath. Place red box 2 below red box 1.
<img width="1497" alt="未命名" src="https://github.com/user-attachments/assets/9eb146d3-656f-4734-8de9-4fb4bdc2c363">

**Comment by frank-zsy** [comment]
> Because some repository label data is not only voluminous but also lengthy in text. One idea is to mimic the repository home page by adding a label for the repository underneath. Place red box 2 below red box 1. Might be worth considering. 

Great idea, like it.

**Comment by wxharry** [comment]
> Because some repository label data is not only voluminous but also lengthy in text. One idea is to mimic the repository home page by adding a label for the repository underneath. Place red box 2 below red box 1. Might be worth considering.

<img width="1850" alt="image" src="https://github.com/user-attachments/assets/0996dbc6-4a3c-4c4c-8432-71c486e88d17">
I am also thinking if it is possible to move the other labels to the end of the list, so users get to know what metrics they are reading.

**Comment by wangyantong2000** [comment]
> Here is a prototype of what mentioned in [the comment](https://github.com/hypertrons/hypertrons-crx/issues/859#issuecomment-2305190248). I think this looks really good and we can add hyperlink to corresponding leaderboard for these labels when we finished the labels leaderboards.

This looks great.

**Comment by TieWay59** [comment]
one more fail case: https://github.com/bytecodealliance/wasmtime

**Comment by wangyantong2000** [comment]
Next, this task will be completed by @Xsy41 .

**Comment by Xsy41** [comment]
Some labels are too long, the name is similar, how to deal with it? @frank-zsy 
failing case：https://github.com/openai/whisper
<img width="1613" alt="image" src="https://github.com/user-attachments/assets/eb241a5d-473c-428c-8eb0-beafa7bf916a">

**Comment by wangyantong2000** [comment]
The icon may be this one https://open-digger.cn/img/logo/logo-blue-round-corner.png ？

**Comment by Xsy41** [comment]
This is the initial adjustment plan at present, let's see if there are any better suggestions.
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/aa7ee208-1c48-4dd6-924a-a3bed2f4c47f">
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/a6e7f98e-2912-4d2d-90fc-ebce6ad75f36">

**Comment by TieWay59** [comment]
Good job @Xsy41! LGTM. cc @tyn1998 

Is it possible to use `AI` instead of the full spell? I guess we'll need a shortened set of tags in someplace. (and give the full form on some hover inform text.) cc @wangyantong2000

**Comment by HalloMelon** [comment]
Wonderful @Xsy41 , but I was wondering if it's possible to display a portion of the important tags and collapse the remaining tags, instead of collapsing all the tags directly. However, I'm not sure if there is a specific method to automatically select higher-priority tags or an algorithm to rank the tags by priority.

**Comment by Xsy41** [comment]
Thanks to @HalloMelon and @TieWay59 , at present we have two methods, the first method does not show the full name for long tags, and the mouse hover to show. The second shows tags with higher priority, or for some similar tags. As shown in the following figure, can you only show the following four labels framed in red?

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/71329f6f-ab0e-4f08-a77a-4cd1b1fb3771">

**Comment by wangyantong2000** [comment]
> Thanks to @HalloMelon and @TieWay59 , at present we have two methods, the first method does not show the full name for long tags, and the mouse hover to show. The second shows tags with higher priority, or for some similar tags. As shown in the following figure, can you only show the following four labels framed in red?由于和，目前我们有两个方法，第一个方法不显示长标签的全名，并将鼠标悬停显示出来。第二个显示具有更高优先级的标记，或者一些类似的标记。如下图所示，可以只显示以下四个红色边框的标签吗?
> 
> <img alt="image" width="1326" src="https://private-user-images.githubusercontent.com/75050154/371128037-71329f6f-ab0e-4f08-a77a-4cd1b1fb3771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTE5NjgsIm5iZiI6MTcyNzM1MTY2OCwicGF0aCI6Ii83NTA1MDE1NC8zNzExMjgwMzctNzEzMjlmNmYtYWIwZS00ZjA4LWE3N2EtNGNkMWIxZmIzNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDExNTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDg0ZDk4ZTI1NGRjMjUxZWYyMTY0ZTg4MTQ3NTNlNGNhZWFhYWI0OGM1MzdlYTk0YWEzZWQ1MDNmOGQ1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SMMc7ab4rg_WK8TazTN06byzCNtoL0HYj1BevjLWtw0">

At present, our label data is directly provided by OpenDigger. I think we can wait for @frank-zsy  to reconfirm the label data and see if further processing is needed. See if the changes are caused by the data source itself or during development.

**Comment by frank-zsy** [comment]
The label structure in OpenDigger involves multiple layers, so one repo may has multiple labels in a technical area in different layers just like `whisper`. And In the label structure, the parent label name will be a prefix to its children labels.

I think only presenting the top-level label is neat and clean, but in the label data exported in OpenDigger, we do not provide if a label is a top-level label but a top-level label is prefix of its all children labels.

So there are 2 ways to fix this:

- Provide level of a label in OpenDigger export data. And this will take time to develop in OpenDigger.
- In HyperCRX, filter all the labels which have prefix equals to any other label.

**Comment by frank-zsy** [comment]
Oh, actually I think the type of the label implies the level of the label. For `Domain` and `Tech` label, the type of the label will be `Domain-n` and `Tech-n`.

So just filter the labels with type `Tech-n` and `n` is not 0, and same to `Domain-n`, we can get rid of the children labels.

**Comment by Xsy41** [comment]
> Oh, actually I think the type of the label implies the level of the label. For `Domain` and `Tech` label, the type of the label will be `Domain-n` and `Tech-n`.
> 
> So just filter the labels with type `Tech-n` and `n` is not 0, and same to `Domain-n`, we can get rid of the children labels.

Thanks to @frank-zsy  we filtered all `Tech-n` and `n` is not 0, and our final interface rendered the result.

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/466dfe60-b147-4e50-a5f2-abf4e9196e86">
