### ISSUE TITLE
[Feature] Change the base URL of oss data

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#881]
### Description

The former base URL is `https://oss.x-lab.info/open_digger/`, as OpenDigger has independent infra now, we should change the base URL to `https://oss.open-digger.cn/`.

The 2 base URLs will both be valid for next 6 month and then the former one will not be updated then.

**Comment by wangyantong2000** [comment]
Ok, I will handle it as soon as possible afterwards.
