### ISSUE TITLE
[Bug] External URL injection issues, such as side label icon

### ISSUE THREAD

**Issue by wangyantong2000** [hypertrons/hypertrons-crx#887]
### Current Behavior

https://github.com/user-attachments/assets/5bb51d7b-5108-4b63-a797-5db889305531

### Environment

```markdown
- OS:
- Browser:
```

**Comment by wangyantong2000** [comment]
The statement of GPT is as follows.
<img width="975" alt="image" src="https://github.com/user-attachments/assets/5465a9c4-2cf1-4636-b484-82175213bf81">

**Comment by wangyantong2000** [comment]
Similar issues can also occur in the icons of OSGraph.
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/e63ea90b-c9df-492f-8e0f-7dc22fae73c5">

**Comment by wangyantong2000** [comment]
<img width="804" alt="image" src="https://github.com/user-attachments/assets/01290787-96de-42e2-8ba0-1cecb2f40678">
I tried to modify the CSP strategy. But none of them were successful. Due to GitHub's CSP being platform level, its limitations cannot usually be modified.
Afterwards, these images will be obtained locally instead of through URLs.

**Comment by tyn1998** [comment]
<img width="1875" alt="image" src="https://github.com/user-attachments/assets/8aef0b85-b730-4212-a7e9-850acd7d2c68">

The issue is not replicated in my browser.

**Comment by Xsy41** [comment]
I also have this problem, in the process of constantly trying to move forward and backward, the picture will not load out.
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/c68755ef-69c1-4a97-b8f1-18d2e725659a">

**Comment by Xsy41** [comment]
We can use base64 encoding, which @frank-zsy mentioned, to avoid this problem.Here is a 36px logo.
```javascript
src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAMAAADW3miqAAABtlBMVEX///8eof8boP8coP8an/8dof8aoP+Kzv8eof8eof8eof8eof8eof8eof8doP+Dy/8jo/8io/9Zuv+Mz/8eof+FzP/1+//A5f/D5v/9/v9du/8hov/8/v8ko/81q//4/P8mpP+Y1P8tp/8opf/F5/+Lz//Y7/+Nz//d8f8Yn/9pwP88rv9auv+U0v+64v8gov+R0f+w3v8yqf+j2P/c8P+a1f+Lzv/+//9Otf/7/f+34f+e1v9Ntf/0+v+x3v8+rv8fov/T7f/n9f8Zn/9jvv/u+P9/yv+S0f/z+v+t3f9Rtv8xqf+Byv9evP/W7v8sp/8rpv/I6P+44f9Gsv83rP8ppv8npf/+/v/y+f9swv9qwf/L6f+Ey/+By//6/f+24P/x+f/k9P+j2f/g8v+d1v9VuP9Fsf8zqv8wqP+GzP+Cy/9UuP8wqf+Jzv/2+//0+/9fvP+EzP+/5P+24f+r3P9Tt/86rf/o9f85rP+u3f+q2/8Ynv9Js/9/yf88rf9uwv+P0P/5/P/m9f/l9P/i8/+f1/8Xnv9Qtv9Ks/9Hsv9Br/93xv9zxP9uw/9kvv8kpP9gvf9HcEysAMmpAAAAknRSTlP//////////8b0+KIMZv///////xn/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AMUw4HUAAAHcSURBVDjLjZT1VxtBEMdn5eI57hJSYoSEBAlepHiB0uJWwaVI0Rp1AQoVisv9x+xy5CV5IWTnh307e5/bnd35zoCm2ewmM0pjZpPdpmmgZVst6A6zWLM1sFlRBrPawG7JBFnsYEIZzQTmzJAZkIAlQtiAuVFK0kJSbpnLaCwocnY9blNxGii3/B4APCks7vE8euhVyG0QdnCmoyW/v6/XD601ASJJKZDBxRhwdsp4S+1uBHCXBkd9GEvJOz3g0Ab1/fLufH7Hps+mIi+rvCMkCTJyKIuqX7e/bK5PAIxX5QDkuRvkVMiACHsEhX2Hwpk5Nj4dlmIQiUPXfzjZvHF2mo1LAVmHiPK9PQmiJR7mhFoWAF5V6seRN81ZRA88tpMjjzn3UQ00reoxydVNEMJ0IBXyhZrXbm5XWQfw7yB69DfxOD9z6pQVVdbfSa6uZQvFZ+HBIYAPNB64ZzKWaUBSmN8XfrtPBo0fd/9TTJAU5Eu1L0g8LeR5xXuO1X+L/Nw7PXccBunreea65MTckbHltz8ifzg4tD9weewLf2LTivzkBEsYt6sFHCqK0s7oRbefJ5ikSsWgS6XhRiqLAXKb6BQB0YnJV6gQ7iopoeIUKnOhhiHUeoSamEg7vAIbGEZaYScUbgAAAABJRU5ErkJggg=="

**Comment by frank-zsy** [comment]
I am wondering that when this bug will be triggered. Because in the production mode, I do not see the problem, like for the 1.9.9 release in Chrome extension store.

Does this happen when you use the pre-release or development mode? Or this also happens in production mode?

BTW, I prefer the base64 solution since it will definitely reduce the OSS cost ( I mean really money here ).

**Comment by wangyantong2000** [comment]
> I am wondering that when this bug will be triggered. Because in the production mode, I do not see the problem, like for the 1.9.9 release in Chrome extension store.
> 
> Does this happen when you use the pre-release or development mode? Or this also happens in production mode?
> 
> BTW, I prefer the base64 solution since it will definitely reduce the OSS cost ( I mean real money here ).

This situation is caused by the security policies of GitHub pages. When resources that need to be injected through external URLs appear, the GitHub page will refuse to load the external URL resources and report this error. The image of osgrpah introduced in the previous frame and the icon of osgrpah will both report errors in the console, but it does not affect normal use. The side label icon may have errors in some situations this time.

**Comment by wangyantong2000** [comment]
Currently, I have asked @Xsy41  to help replace the icon URL with another format.
