### ISSUE TITLE
[Feature] The new routing design of OSGraph

### ISSUE THREAD

**Issue by wangyantong2000** [hypertrons/hypertrons-crx#889]
A new issue has been opened from [# 834](https://github.com/hypertrons/hypertrons-crx/issues/834) to complete the replacement of the routing design.

Is there a description of the new routing design?@frank-zsy

_Originally posted by @wangyantong2000 in https://github.com/hypertrons/hypertrons-crx/issues/834#issuecomment-2423742866_

**Comment by frank-zsy** [comment]
We can directly get the share URL from OSGraph website, corresponding routing design is:

- Project contribution network
  - https://osgraph.com/graphs/repo-contrib/github/hypertrons/hypertrons-crx?contrib-limit=10
- Project ecosystem network
  - https://osgraph.com/graphs/repo-eco/github/hypertrons/hypertrons-crx?repo-limit=10
- Project community network
  - https://osgraph.com/graphs/repo-community/github/hypertrons/hypertrons-crx?country-limit=5&org-limit=5&contrib-limit=3
- Development Activity Network
  - https://osgraph.com/graphs/dev-activity/github/frank-zsy?repo-limit=10
- Open Source Partners Network
  - https://osgraph.com/graphs/dev-partner/github/frank-zsy?partner-limit=10
- Open Source Interests Network
  - https://osgraph.com/graphs/dev-interest/github/frank-zsy?repo-limit=3&topic-limit=5

All the `limit` parameters can be changed, we can just use the default number or set to a bit larger number.
