### ISSUE TITLE
[Report] HyperCRX Biweekly Report : 2024-10-23

### ISSUE THREAD

**Issue by HalloMelon** [hypertrons/hypertrons-crx#897]
### 📈 User Growth （ as of October 22, 2024 ）
- **Google Chrome Users** : The number of HyperCRX users on Google Chrome reached 1,096.
- **Microsoft Edge Users** :  The number of users on Microsoft Edge is 1127.

 ### ✍️ Update Summary
- **Version Update** : HyperCRX extension updated to version 1.9.12.
- **Bugs Fixed** ：
  - Fixed the issue where the tooltip failed to display when toggling between the starred and unstarred states in the repository.Thx @Xsy41 
    - https://github.com/hypertrons/hypertrons-crx/pull/877 
- **Features Improved** ：
  - We have updated the labels UI on repository pages to make it more aesthetically pleasing and streamlined. 🎉 Thx @frank-zsy @tyn1998 @wangyantong2000 @Xsy41 
      - https://github.com/hypertrons/hypertrons-crx/pull/880 
      - https://github.com/hypertrons/hypertrons-crx/pull/886 
    
![image](https://github.com/user-attachments/assets/8ab75209-7e40-4120-872f-f59d85080f4e)

    
  - Updated the linking and embedding method for osgraph icons. 🎉 Thx @frank-zsy @wangyantong2000 @Xsy41
    - https://github.com/hypertrons/hypertrons-crx/pull/888
    - https://github.com/hypertrons/hypertrons-crx/pull/890   
    
![image](https://github.com/user-attachments/assets/aad3c02c-40a8-4cda-8dcf-2f9e5c163ab8)
 

  - https://github.com/hypertrons/hypertrons-crx/pull/892 Thx @wangyantong2000 
  - https://github.com/hypertrons/hypertrons-crx/pull/893 Thx @wangyantong2000 
  - https://github.com/hypertrons/hypertrons-crx/pull/895 Thx @wangyantong2000

**Comment by wangyantong2000** [comment]
I think the periodic report of the project should not only list and summarize some data. We can add some project phase plans, as well as some personal thoughts and ideas (if any). Meanwhile, anyone is welcome to share their ideas, thoughts, suggestions, or anything else you want to say under this report.
At present, HyperCRX's short-term goals are to complete the complete launch of FastPR, the rapid refactoring and functional improvement of OSS-GPT, and the preparation for adaptation to the Gitee platform.
Expected to complete the launch of the new feature [FastPR](https://github.com/hypertrons/hypertrons-crx/issues/778) in November.

**Comment by Xsy41** [comment]
At present, I am trying to fix the #773 , welcome to discuss together.
