### ISSUE TITLE
[Feature] Whole new website of HyperCRX

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons-crx#908]
### Description

As FastPR #901 functionality launched, we need a website to help users to understand how to use HyperCRX.

The old domain `hypertrons.io` has expired and the old website is not good enough now.

I would like to launch a new website for HyperCRX with Docusaurus framework just like [OpenDigger website](https://open-digger.cn) and we can add documentation about how to use the extension and setup guidance.

**Comment by wangyantong2000** [comment]
Also provide a few additional examples. The laboratory has also developed several document websites using the mkdocs framework. Example: https://www.x-lab.info/oss101-bok/. Vitpress is also a great choice. Example: https://aide.nicepkg.cn/zh/, https://vitepress.dev/.

**Comment by frank-zsy** [comment]
@wangyantong2000 Great, which one do you prefer? I am familiar with Docusaurus and can build it quickly, would need learn for new frameworks.

**Comment by wangyantong2000** [comment]
Vitpress and docusaurus both look quite beautiful. Developers can use familiar ones

**Comment by wangyantong2000** [comment]
However, regardless, this proposal is very necessary. I mentioned in the laboratory six months ago that we could have a website similar to [Aide](https://aide.nicepkg.cn/zh/) that introduces the functionality of our plugins.

**Comment by frank-zsy** [comment]
OK, I will start with Docusaurus and it is fully customizable.

**Comment by frank-zsy** [comment]
The website framework has been uploaded to https://github.com/hypertrons/hypertrons-crx-website and deployed to https://hypercrx.cn
