### ISSUE TITLE
[Bug] Confused about the new extension permission

### ISSUE THREAD

**Issue by Leslie-Wong-H** [hypertrons/hypertrons-crx#930]
### Version

v1.9.15

### Current Behavior

![image](https://github.com/user-attachments/assets/bd953bf5-5dc6-4947-bd17-84c9f8804335)

Isn't the github website necessary to perform its core feature marked as `Hypertrons Chromium Extension for GitHub`? 

### Expected Behavior

Current solution to restrict the site access I supposed.

![image](https://github.com/user-attachments/assets/28ce0404-fb28-4dfb-b46b-7018811d0086)

### Environment

```markdown
- OS:
- Browser:
```

**Comment by wangyantong2000** [comment]
The functionality of hyperrx will not be limited to the GitHub platform. The newly launched feature has been extended to other document websites for use.

**Comment by Leslie-Wong-H** [comment]
Then, the new phase should probably be `Hypertrons Chromium Extension for GitHub and other document websites` to express its clarity to end users reaching the Chrome Web Store.

**Comment by wangyantong2000** [comment]
> Then, the new phase should probably be to express its clarity to end users reaching the Chrome Web Store.`Hypertrons Chromium Extension for GitHub and other document websites`

Thank you for your suggestion. We will make adjustments to this in the next release.
