### ISSUE TITLE
[Bug] "Activity and OpenRank Trends" on the personal page always displays the information of the currently logged-in user.

### ISSUE THREAD

**Issue by stevending1st** [hypertrons/hypertrons-crx#934]
### Version

1.9.13

### Current Behavior

No matter whose homepage I visit, it shows the same "Activity and OpenRank Trends."

![image](https://github.com/user-attachments/assets/0be129f3-99b0-46ed-9c63-800c9e676188)

![image](https://github.com/user-attachments/assets/252bc819-7268-4d52-9ccd-b9118b612aef)

### Environment

```markdown
- OS:
- Browser: Microsoft Edge 131.0.2903.63
```

**Comment by wangyantong2000** [comment]
This issue has been resolved in https://github.com/hypertrons/hypertrons-crx/pull/925. Just wait for the next version update.

**Comment by HalloMelon** [comment]
Maybe it is a network problem, I don't have this bug.
![image](https://github.com/user-attachments/assets/f2c1cc1c-808b-4829-8e80-62ff5a418d24)

![image](https://github.com/user-attachments/assets/85e9a82d-81dc-44d8-abd6-d9e151e16f51)
